### ISSUE TITLE
the backup snapshot is still 0 in 0.9.4

### ISSUE THREAD

**Issue by lynch0227** [influxdb/influxdb#4139] opened 2015-09-17 02:06 UTC
When I use the 0.9.4 new version, I add the below part into the configure file.
[snapshot]
enabled = true # Disabled by default if not set.

And then do the backup, then snapshot is still 0 size.
influxd backup /tmp/mysnapshot
-rw-r--r-- 1 root root 0 Sep 17 09:55 /tmp/mysnapshot

Can we fix this issue in the next 0.9.5 version?

**Comment by mjdesa** [comment] 2015-09-17 18:09
@lynch0227 thank you for reporting the issue.

When I run

```
~$ influxd backup snap
2015/09/17 11:07:43 influxdb backup
2015/09/17 11:07:43 backup complete
```

I get the following panic

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x3966f8]

goroutine 161 [running]:
github.com/boltdb/bolt.(*DB).beginTx(0x0, 0xc820342090, 0x0, 0x0)
	/Users/michaeldesa/go/src/github.com/boltdb/bolt/db.go:422 +0x2f8
github.com/boltdb/bolt.(*DB).Begin(0x0, 0x0, 0xd78ae8, 0x0, 0x0)
	/Users/michaeldesa/go/src/github.com/boltdb/bolt/db.go:415 +0x60
github.com/influxdb/influxdb/tsdb.appendShardSnapshotFile(0xc82011a560, 0xc8201dc3c0, 0xc82027cb62, 0x13, 0x0, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/tsdb/snapshot_writer.go:86 +0x1bd
github.com/influxdb/influxdb/tsdb.appendShardSnapshotFiles(0xc82011a560, 0xc820130000, 0x0, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/tsdb/snapshot_writer.go:70 +0x669
github.com/influxdb/influxdb/tsdb.NewSnapshotWriter.func1(0xc820288100, 0xea, 0x100, 0xc82011a560, 0xc820130000, 0x0, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/tsdb/snapshot_writer.go:31 +0x30d
github.com/influxdb/influxdb/tsdb.NewSnapshotWriter(0xc820288100, 0xea, 0x100, 0xc820130000, 0x0, 0x0, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/tsdb/snapshot_writer.go:20 +0x122
github.com/influxdb/influxdb/services/snapshotter.(*Service).writeSnapshot(0xc820015310, 0xdb53c0, 0xc82018a2a0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/services/snapshotter/service.go:131 +0x1c3
github.com/influxdb/influxdb/services/snapshotter.(*Service).handleConn(0xc820015310, 0xdb53c0, 0xc82018a2a0, 0x0, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/services/snapshotter/service.go:105 +0x1cd
github.com/influxdb/influxdb/services/snapshotter.(*Service).serve.func1(0xc820015310, 0xdb53c0, 0xc82018a2a0)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/services/snapshotter/service.go:89 +0xbf
created by github.com/influxdb/influxdb/services/snapshotter.(*Service).serve
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/services/snapshotter/service.go:92 +0x470
```

**Comment by rummand** [comment] 2015-09-17 18:37
+1

**Comment by beckettsean** [comment] 2015-09-18 21:15
duplicate of https://github.com/influxdb/influxdb/issues/3923

**Closed by beckettsean** 2015-09-18 21:15 UTC

**Comment by harryshayne** [comment] 2015-09-23 06:40
+1,when to fix it

**Comment by abolinhas** [comment] 2015-09-27 22:38
Same issue here with influx 0.9.3
root@stats-appliance:/home/artica/influx/backup# /opt/influxdb/influxd backup -host 10.95.254.99:8089 /home/artica/influx/backup/snapshot.db
2015/09/27 19:27:05 influxdb backup
2015/09/27 19:27:41 backup complete
root@stats-appliance:/home/artica/influx/backup# du -sh *
0       snapshot.db
root@stats-appliance:/home/artica/influx/backup#

Also influx crash after finish the backup process
