### ISSUE TITLE
InfluxDB 0.9.3 panics when running backups

### ISSUE THREAD

**Issue by jipperinbham** [influxdb/influxdb#3941] opened 2015-09-02 03:28 UTC
This seems to be related to when we are attempting to backup the database
```
/opt/influxdb/influxd backup /backup/{filename}.tar.gz
```

See the [full stacktrace](https://gist.github.com/jipperinbham/06b6654d418e6541dd40) for the gory details.

**Comment by beckettsean** [comment] 2015-09-02 17:54
duplicate of #3700, #3919, #3923.

**Closed by beckettsean** 2015-09-02 17:54 UTC

**Comment by abolinhas** [comment] 2015-09-27 22:38
Same issue here with influx 0.9.3
root@stats-appliance:/home/artica/influx/backup# /opt/influxdb/influxd backup -host 10.95.254.99:8089 /home/artica/influx/backup/snapshot.db
2015/09/27 19:27:05 influxdb backup
2015/09/27 19:27:41 backup complete
root@stats-appliance:/home/artica/influx/backup# du -sh *
0       snapshot.db
root@stats-appliance:/home/artica/influx/backup#

Also influx crash after finish the backup process
