### ISSUE TITLE
query  time is wrong 

### ISSUE THREAD

**Issue by lostz** [influxdb/influxdb#4213] opened 2015-09-24 03:32 UTC
My column time is 2015-09-24 11:31:41.827188331 +0800 CST 
but my query time is 1970-01-01T00:00:01.443065351Z

```
> select * from "cpu.guest.percentage";
name: cpu.guest.percentage
--------------------------
time				hostname	server		value
1970-01-01T00:00:01.443065048Z	dev14705	10.88.147.5	0
1970-01-01T00:00:01.443065049Z	dev14702	10.88.147.2	0.5113432753535297
1970-01-01T00:00:01.44306508Z	dev14703	10.88.147.3	3.1332769024929688
1970-01-01T00:00:01.443065099Z	dev14701	10.88.147.1	0.09858235792338346
1970-01-01T00:00:01.443065111Z	dev14704	10.88.147.4	2.5770033132899743
1970-01-01T00:00:01.443065168Z	dev14705	10.88.147.5	0
1970-01-01T00:00:01.443065169Z	dev14702	10.88.147.2	0.4944735311227458
1970-01-01T00:00:01.4430652Z	dev14703	10.88.147.3	2.4154125013731735
1970-01-01T00:00:01.443065219Z	dev14701	10.88.147.1	0.0958812739703185
1970-01-01T00:00:01.443065231Z	dev14704	10.88.147.4	2.1717683812446906
1970-01-01T00:00:01.443065288Z	dev14705	10.88.147.5	0
1970-01-01T00:00:01.443065289Z	dev14702	10.88.147.2	0.48886851936724857
1970-01-01T00:00:01.44306532Z	dev14703	10.88.147.3	2.641932134856019
1970-01-01T00:00:01.443065339Z	dev14701	10.88.147.1	0.09721142095322742
1970-01-01T00:00:01.443065351Z	dev14704	10.88.147.4	2.2482371465735604
```

**Comment by corylanou** [comment] 2015-09-24 14:08
Can you give us some information on how you are doing writes?  Are you using the client library?  Are you using a collection endpoint like graphite?  It would appear the data isn't being written properly.  We would need more information on how you are sending data to the server to understand the problem.

**Comment by corylanou** [comment] 2015-09-24 14:09
My guess would be that you are sending us time in one precision, and we are expecting it in anther precision when decoding it.  This can happen a number of ways when sending data, so once I understand how you are sending data I should be able to give examples of the proper way to send the data.

**Comment by beckettsean** [comment] 2015-09-25 20:18
@lostz this looks like a duplicate of https://github.com/influxdb/influxdb/issues/4185. If you are supplying date-times rather than UNIX epoch timestamps, please make sure you are not also using the `precision` query string parameter.

**Closed by beckettsean** 2015-09-25 20:18 UTC

**Comment by lostz** [comment] 2015-09-28 06:49
I fixed it by removing "precision" field
