### ISSUE TITLE
Continuos queries: group by time(1d) for arbitrary 24h

### ISSUE THREAD

**Issue by duerreda** [influxdb/influxdb#3113] opened 2015-06-23 20:33 UTC
For our use case, it is important to be able to define continuous queries that group data by time(1d), but considering data from 8am to 8am (or an arbitrary period of 24 hours), instead of 12am to 12am.

Would it be possible to add another argument to the time(...)-function that defines thet start of the 24h window for the grouping? This could even be generalized for every time period.

**Comment by beckettsean** [comment] 2015-07-15 00:48
Duplicate of https://github.com/influxdb/influxdb/issues/1837

**Closed by beckettsean** 2015-07-15 00:48 UTC
