### ISSUE TITLE
InfluxDB returns large results in batches, makes grafana think they are different series

### ISSUE THREAD

**Issue by victorhooi** [influxdb/influxdb#3242] opened 2015-07-06 13:31 UTC
This is for Grafana with InfluxDB 0.9.

For some reason, certain queries are returning multiple identically-named series from InfluxDB, instead of just one.

For example:
```
q=SELECT+counter1+FROM+%22clickLogger_clickMetric2%22++where+time+%3E+now()+-+3m+
```

will give you:
```
{
    results: [
        {
            series: [
                {
                    name: "clickLogger_clickMetric2",
                    columns: [
                        "time",
                        "counter1"
                    ],
                    values: [...]
                },
                {
                    name: "clickLogger_clickMetric2",
                    columns: [
                        "time",
                        "counter1"
                    ],
                    values: [...]
                }
            ]
        }
    ]
}
```

This was initially reported in the Grafana issue tracker - there's more details here:
* https://github.com/grafana/grafana/issues/2266
* https://github.com/grafana/grafana/issues/2291

**Comment by beckettsean** [comment] 2015-07-08 20:45
@victorhooi what specific version of InfluxDB? 0.9.0, 0.9.1, or a nightly build?

Roughly how many points are returned by that query?

**Comment by victorhooi** [comment] 2015-07-08 22:30
@beckettsean This is InfluxDB 0.9.1 on Ubuntu 15.04 (using the official packages).
```
ubuntu@ip-172-31-2-21:~$ /opt/influxdb/influx --version
InfluxDB shell 0.9.1
```

I think the issue seems to crop up around the 10,000 point mark.

Here is a screenshot from Grafana, showing the colour change:

<img width="1279" alt="screenshot 2015-07-09 08 15 06" src="https://cloud.githubusercontent.com/assets/243499/8583822/1414e22e-2614-11e5-9465-4c04f7464522.png">

```
> select count(value) from read_requests where device = 'sdb' and hostname = 'iapp79' and time > '2015-06-30T03:58:04Z' and time < '2015-06-30T07:06:04Z'
name: read_requests
-------------------
time				count
2015-06-30T01:35:59.745456Z	10418
```

Here is the query string Grafana sent:
```
db=insight&epoch=ms&p=root&q=SELECT+value+FROM+%22read_requests%22+WHERE+device+%3D+'sdb'+AND+hostname+%3D+'iapp79'+AND+time+%3E+1435584307s+and+time+%3C+1435772133s+ORDER+BY+asc&u=root
```
and here is a Gist of the response it received:

https://gist.githubusercontent.com/victorhooi/d231eb42f9b82213f714/raw/gistfile1.json

(Also, if you're wondering why I'm querying so many points, lol, it was because initially I had trouble getting aggregates to work - that was my fault, for not realising I hadn't cast them to int/floats, and that Grafana apparently will graph string values, but not string aggregates).

**Comment by beckettsean** [comment] 2015-07-09 19:00
It looks very much like the responses are chunked into 10000 point batches. I did not directly verify, but each point is roughly 20 characters (e.g. `[1435699625000, 0], `) and the `values` lines are each a bit over 200k characters long.

I don't know if this batching is a serious requirement or just an abundance of precaution, but it could be that other data consumers are confused or crippled by a single JSON line of nearly 3 million characters, which would be the `values` result of your query if not batched.

**Comment by gunnaraasen** [comment] 2015-07-16 00:57
The default chunk size is 10,000 points but can be set by passing `chunk_size` as a parameter in the URL when hitting the `/query` endpoint.

Chunked responses can also be completely disabled by setting `chunked=false` in the query parameter.

This is really a documentation issue so I've opened up https://github.com/influxdb/influxdb.com/issues/121.

**Comment by torkelo** [comment] 2015-07-16 18:00
whats the point of returning more than 10000 points to grafana? It will likely just hang the browser. Grafana sets the group by $interval so only 1 data point per graph pixel is returned

**Comment by gunnaraasen** [comment] 2015-07-16 18:45
Thanks @torkelo. I should have added a disclaimer to my comment. Returning more than 10,000 points to a browser is ill advised. Results should be downsampled using aggregate functions and continuous queries to less than 10,000 points before being sent to a browser.

**Comment by pauldix** [comment] 2015-07-16 19:33
This still feels like a problem to me. The example JSON he gave was in one result set, which means that it's not using chunking. If it's in a single result then each unique `name` + tagset should be in a series object.

@victorhooi: are you seeing this in a single result?

Basically, we might have a problem on our end, but even if we do, you should never be asking a browser to handle >10k points since it'll die.

**Comment by torkelo** [comment] 2015-08-14 07:46
Is this fixed? People are still reporting issues in Grafana repo for this issue (using InfluxDB 0.9)

**Comment by beckettsean** [comment] 2015-08-14 18:10
@torkelo Do you know if the users making those reports have disabled chunking by setting `chunked=false` in the query parameter? Can they set arbitrary query parameters form within Grafana?

**Comment by beckettsean** [comment] 2015-08-14 18:10
@pauldix do you want to reopen this? Looks like we never actually had that discussion.

**Comment by pauldix** [comment] 2015-08-14 18:13
Yeah, let's reopen. Chunking is disabled by default anyway. There was some rework that happened in the query engine so I'm not sure if this is still an issue.

**Comment by otoolep** [comment] 2015-08-14 18:18
@pauldix : ".....not sure if it’s an issue after @otoolep reworked the chunked responses stuff, but we should have a test for it basically, write in 10,001 points into a series. Do a query for all points, ensure that only one row of results with all 10,001 points comes through if chunking is disabled on the HTTP API
note that chunking should always happen internally between the mappers and reducers
but chunking for HTTP should only happen if specified."

**Comment by gunnaraasen** [comment] 2015-08-14 18:23
After looking at the linked Grafana issues, it seems like there is a separate issue where the `derivative` function always groups by 10s intervals regardless of the period specified in the `GROUP BY` clause.

**Comment by otoolep** [comment] 2015-08-17 18:05
OK, this still seems to be an issue. With 10,001 points, only 10,000 comes back in the first chunk.

**Comment by otoolep** [comment] 2015-08-17 18:06
https://github.com/influxdb/influxdb/pull/3697

**Comment by otoolep** [comment] 2015-08-17 18:29
OK, I see the issue. If no chunking is set at the HTTP level, the default chunking size of 10K is getting sent to the mappers. This is for use between mappers and reducers. However this chunking size is also getting applied to the HTTP response, which is not what should happen.

**Comment by otoolep** [comment] 2015-08-17 19:44
Actually, I was mistaken about the cause. This issue was present in 0.9.1 and since the code in question was copied to 0.9.2 as part of the refactor for Distributed Queries, it remains in the code base. The issue that while results are combined in RAM on the co-ordinating node, the results are not merged together fully if they come from the same series.

For example, we get output like this:

```
{
    "results": [
        {
            "series": [
                {
                    "name": "cpu",
                    "columns": [
                        "time",
                        "value"
                    ],
                    "values": [
                        [
                            "1970-01-01T00:00:00Z",
                            0
                        ],
                        [
                            "1970-01-01T00:00:00.000000001Z",
                            1
                        ],
                        [
                            "1970-01-01T00:00:00.000000002Z",
                            2
                        ],
                        [
                            "1970-01-01T00:00:00.000000003Z",
                            3
                        ]
                    ]
                },
                {
                    "name": "cpu",
                    "columns": [
                        "time",
                        "value"
                    ],
                    "values": [
                        [
                            "1970-01-01T00:00:00.000000004Z",
                            4
                        ]
                    ]
                }
            ]
        }
    ]
}
```

when we should get output like this:
```
{
    "results": [
        {
            "series": [
                {
                    "name": "cpu",
                    "columns": [
                        "time",
                        "value"
                    ],
                    "values": [
                        [
                            "1970-01-01T00:00:00Z",
                            0
                        ],
                        [
                            "1970-01-01T00:00:00.000000001Z",
                            1
                        ],
                        [
                            "1970-01-01T00:00:00.000000002Z",
                            2
                        ],
                        [
                            "1970-01-01T00:00:00.000000003Z",
                            3
                        ],
                        [
                            "1970-01-01T00:00:00.000000004Z",
                            4
                        ]
                    ]
                }
            ]
        }
    ]
}
```
I believe the code in question is: https://github.com/influxdb/influxdb/blob/master/services/httpd/handler.go#L289

**Comment by otoolep** [comment] 2015-08-17 20:44
Should be fixed by #3697.

**Comment by otoolep** [comment] 2015-08-18 20:23
All fixed, thanks for the report @victorhooi.

**Closed by otoolep** 2015-08-18 20:23 UTC
Labels: category/queries

**Comment by Menzer05** [comment] 2018-12-26 23:06
how to separate values and hours and date  by query
