### ISSUE TITLE
location of files

### ISSUE THREAD

**Issue by biskit** [influxdb/influxdb#3123] opened 2015-06-24 15:34 UTC
just a suggestion:
1. /etc/opt/influxdb - config
2. /var/opt/influxdb - data

the typical convention is not have the embedded /opt in it. sooner you change, better it is as during upgrade moving data location and config location may be difficult.

finally, symlinking from /etc/init.d/influxdb to /opt/influxdb/init.sh is kinda frowned upon...

**Comment by otoolep** [comment] 2015-06-24 15:39
>>finally, symlinking from /etc/init.d/influxdb to /opt/influxdb/init.sh is kinda frowned upon...

Can you provide a reference for this?

**Comment by biskit** [comment] 2015-06-24 15:40
lrwxrwxrwx 1 root root 21 Jun 23 17:42 /etc/init.d/influxdb -> /opt/influxdb/init.sh

centos 6.6, 0.9.0 latest download, installed from rpm

**Comment by otoolep** [comment] 2015-06-24 15:43
Thanks @biskit -- I know the symlink is there. :-) What I am looking for is a reference that it is bad practice to link from `/etc/` to `/opt`.

**Comment by biskit** [comment] 2015-06-24 15:49
ok :-) 
if you restore this file (/opt/influxdb/init.sh) the inode might change and this will be pointing to bad link

**Comment by jwilder** [comment] 2015-06-24 16:28
@otoolep See https://fedoraproject.org/wiki/Packaging:SysVInitScript and https://www.debian.org/doc/debian-policy/ch-opersys.html#s-sysvinit 

From Fedora SysV packaging guide:

> Packages with SysV-style initscripts must put them into /etc/rc.d/init.d. 

The debian policy manual has a different convention and says that files under `/etc/init.d` should be treated as configuration files.  Using a symlink likely violates that.  It also says:

> These scripts should not fail obscurely when the configuration files remain but the package has been removed, as 
> configuration files remain on the system after the package has been removed

If `/opt/influxdb/init.sh` was removed or changed.  The `/etc/init.d/influxd` script could break.

Another thing is that `update-rc.d` creates symlinks from `/etc/rc.d` to `/etc/init.d` scripts.  Having a symlink in `/etc/init.d` on those systems adds another level of indirection and complexity.  As @biskit mentioned, backup/restore of those files could cause the service to not to restart.  See: http://manpages.ubuntu.com/manpages/trusty/man8/update-rc.d.8.html

I think part of the problem is that we're using the same locations for deb and rpms but don't use the conventional locations for specific distributions.  We're also using SysV init scripts when some distributions use upstart or systemd.

**Comment by otoolep** [comment] 2015-06-24 16:52
Great, thanks for the references. If we're going to rework this, I want to
do The Right Thing.

**Comment by tcompart** [comment] 2015-06-25 18:58
It would also help when it could be possible to inject the configuraton instead of overwriting it. Currently I am not able to overwrite files of a different rpm. Therefore I cannot overwrite your config in /etc/opt/influxdb.

**Comment by dever860** [comment] 2015-06-25 22:19
https://github.com/influxdb/telegraf/issues/22 Is also relevant to this. Both projects should be rewritten at the same time, and be cognizant of each other as to not overwrite each others symlinks.

**Comment by cburroughs** [comment] 2015-07-16 20:43
As an admin I'm happy with things that keep to themselves in `/opt`.  And a traditional/normal layout is always nice, but a hybrid (/etc/opt) just feels like the worst of all worlds.

**Comment by otoolep** [comment] 2015-09-09 21:18
Nothing planned for this right now.

**Comment by blufor** [comment] 2015-10-01 13:27
fixed in #4288

**Comment by rossmcdonald** [comment] 2015-10-16 18:43
Closing in favor of #4479. Any further comments should be made on the PR.

**Closed by rossmcdonald** 2015-10-16 18:43 UTC
Labels: category/packages
