### ISSUE TITLE
Order by doesn't work at all

### ISSUE THREAD

**Issue by marcosnils** [influxdb/influxdb#2394] opened 2015-04-22 20:09 UTC
By default results are ordered by time ASC and that can't be changed. 

Even though you specify an order condition in the query either by time or any other column, seems like Influx totally ignores it.

**Comment by neonstalwart** [comment] 2015-04-22 21:17
duplicate of #2022

**Comment by neonstalwart** [comment] 2015-04-22 21:25
@marcosnils another thing you may find soon which doesn't work at all is stddev.  i've started on something in #2354 but [i'm stuck](https://github.com/influxdb/influxdb/pull/2354#issuecomment-94816679) because i have very limited experience with go.  maybe you could take a look and help me pull it over the line?

**Closed** 2015-04-22 21:25 UTC

**Comment by marcosnils** [comment] 2015-04-22 21:28
@neonstalwart I'm working into another issue with some other guy regarding collectd at this moment. We're pretty close to a conclusion on that, so as soon as I finish I can give you a hand with this.
