### ISSUE TITLE
[0.9.1] "DROP" problem

### ISSUE THREAD

**Issue by ninokop** [influxdb/influxdb#3283] opened 2015-07-10 03:02 UTC
[0.9.1] I have two problems. 

1.After I excuted "drop series from ", I tried to insert with same name. ------>"select * from cpu"  show nothing.
2.Then I restarted the influxd process and excuted "select * from cpu"------>show nothing again
3. Then I insert again and and excuted "select * from cpu"--------> show three series!!(the series that I dropped, the series that I inserted before restarting and the series that I inserted just now!)

\> select * from cpu
name: cpu
tags: host=local
time value
2015-07-09T16:54:40.740627311Z 0.6
\> drop series from cpu where host='local'
\> select * from cpu
\> insert cpu,host=local value=9.0
\> select * from cpu
\>
\> show series
\>

RESTARTING INFLUXD PROCESS

\> select * from cpu
\> insert cpu,host=local value=7.0
\> select * from cpu
name: cpu
tags: host=local
time value
2015-07-09T16:54:40.740627311Z 0.6
2015-07-09T16:55:27.193514255Z 9
2015-07-09T16:56:54.869625619Z 7

**Comment by samhatchett** [comment] 2015-07-10 18:46
probably a dupe of #3226

**Comment by beckettsean** [comment] 2015-07-13 21:51
It is indeed a duplicate of #3226.

**Closed by beckettsean** 2015-07-13 21:51 UTC
