### ISSUE TITLE
Duplicate Data with same timestamp

### ISSUE THREAD

**Issue by jhedlund** [influxdb/influxdb#3419] opened 2015-07-21 21:08 UTC
This is on a nightly release as of 7/17, I am down sampling manually because the continuous queries are broken for me (per #3368).

I am seeing some duplicate data even when using the same nanosecond timestamp, and same tag, etc, here is sample duplicate data:

                        [
                            1437511620000000000,
                            1.09415,
                            1.09426,
                            1.09421,
                            1.09426
                        ],
                        [
                            1437511620000000000,
                            1.09415,
                            1.09426,
                            1.09421,
                            1.09426
                        ],

Is there something I can do to ensure the data is overwritten?

Is there something I can do to clean this up?

Thanks,
Jeff

**Comment by otoolep** [comment] 2015-07-21 21:28
This implies that this data is not *exactly* the same. Are you sure both points have exactly the tag key-value pairs? Can you demonstrate this with a `curl` command?

**Comment by jhedlund** [comment] 2015-07-21 23:06
I only have one tag, and the above query is the result of choosing that tag.  So yes, I'm sure it has the same tag key-value pair.  

It doesn't happen all the time, I am using the HTTP POST to write the data (equivalent of curl but within a .NET application).

I am selecting the downsample via a HTTP query specified with nanoseconds and I am then entering that data into a new measurement with the same epoch that I get from the query.  So I'm not sure under what circumstances it can enter a duplicate timestamp row...

If there is something else I can query to show where the data is not the same I can give it a shot, but as far as I can tell it is the same tags,

**Comment by beckettsean** [comment] 2015-07-22 21:13
Seems like a duplicate of #3315 

@jhedlund can you give the results of `SHOW SERIES` on the database, as well as the exact query you are running?

**Comment by jhedlund** [comment] 2015-07-22 21:23
name: ohlctest
--------------
_key                    symbol
ohlctest,symbol=AUDCAD  AUDCAD
ohlctest,symbol=AUDCHF  AUDCHF
ohlctest,symbol=AUDJPY  AUDJPY
ohlctest,symbol=AUDNOK  AUDNOK
ohlctest,symbol=AUDNZD  AUDNZD
ohlctest,symbol=AUDSEK  AUDSEK
ohlctest,symbol=AUDUSD  AUDUSD
ohlctest,symbol=CADCHF  CADCHF
ohlctest,symbol=CADJPY  CADJPY
ohlctest,symbol=CADNOK  CADNOK
ohlctest,symbol=CADSEK  CADSEK
ohlctest,symbol=CHFJPY  CHFJPY
ohlctest,symbol=CHFNOK  CHFNOK
ohlctest,symbol=CHFSEK  CHFSEK
ohlctest,symbol=EURAUD  EURAUD
ohlctest,symbol=EURCAD  EURCAD
ohlctest,symbol=EURCHF  EURCHF
ohlctest,symbol=EURGBP  EURGBP
ohlctest,symbol=EURHKD  EURHKD
ohlctest,symbol=EURJPY  EURJPY
ohlctest,symbol=EURNOK  EURNOK
ohlctest,symbol=EURNZD  EURNZD
ohlctest,symbol=EURPLN  EURPLN
ohlctest,symbol=EURSEK  EURSEK
ohlctest,symbol=EURSGD  EURSGD
ohlctest,symbol=EURTRY  EURTRY
ohlctest,symbol=EURUSD  EURUSD
ohlctest,symbol=GBPAUD  GBPAUD
ohlctest,symbol=GBPCAD  GBPCAD
ohlctest,symbol=GBPCHF  GBPCHF
ohlctest,symbol=GBPJPY  GBPJPY
ohlctest,symbol=GBPNOK  GBPNOK
ohlctest,symbol=GBPNZD  GBPNZD
ohlctest,symbol=GBPSEK  GBPSEK
ohlctest,symbol=GBPUSD  GBPUSD
ohlctest,symbol=HKDJPY  HKDJPY
ohlctest,symbol=NOKSEK  NOKSEK
ohlctest,symbol=NZDCAD  NZDCAD
ohlctest,symbol=NZDCHF  NZDCHF
ohlctest,symbol=NZDJPY  NZDJPY
ohlctest,symbol=NZDUSD  NZDUSD
ohlctest,symbol=SEKJPY  SEKJPY
ohlctest,symbol=USDCAD  USDCAD
ohlctest,symbol=USDCHF  USDCHF
ohlctest,symbol=USDDKK  USDDKK
ohlctest,symbol=USDHKD  USDHKD
ohlctest,symbol=USDILS  USDILS
ohlctest,symbol=USDJPY  USDJPY
ohlctest,symbol=USDMXN  USDMXN
ohlctest,symbol=USDNOK  USDNOK
ohlctest,symbol=USDPLN  USDPLN
ohlctest,symbol=USDRUB  USDRUB
ohlctest,symbol=XPTUSD  XPTUSD
ohlctest,symbol=USDSEK  USDSEK
ohlctest,symbol=USDSGD  USDSGD
ohlctest,symbol=USDTRY  USDTRY
ohlctest,symbol=USDZAR  USDZAR
ohlctest,symbol=XAGUSD  XAGUSD
ohlctest,symbol=XAUUSD  XAUUSD
ohlctest,symbol=XPDUSD  XPDUSD
ohlctest,symbol=EURCZK  EURCZK
ohlctest,symbol=NZDSEK  NZDSEK


Query:

select * from ohlctest where symbol='EURUSD'

Duplicates:

2015-07-22T21:14:00Z    1.09276 1.09276 1.09294 1.09269
2015-07-22T21:14:00Z    1.09276 1.09276 1.09294 1.09269
2015-07-22T21:15:00Z    1.09263 1.09325 1.09277 1.09305
2015-07-22T21:15:00Z    1.09263 1.09325 1.09277 1.09305
2015-07-22T21:16:00Z    1.09265 1.09265 1.09279 1.09265
2015-07-22T21:16:00Z    1.09265 1.09265 1.09279 1.09265
2015-07-22T21:17:00Z    1.09269 1.09277 1.09282 1.09269
2015-07-22T21:17:00Z    1.09269 1.09277 1.09282 1.09269
2015-07-22T21:18:00Z    1.09274 1.09275 1.09283 1.09273
2015-07-22T21:18:00Z    1.09274 1.09275 1.09283 1.09273


(should only have 1 per minute)

The CLI doesn't allow me to show the nanoseconds, but I'm sure they are the same nanoseconds.  Can do a web query if you need to see it.

**Comment by jhedlund** [comment] 2015-07-22 21:24
FYI:  I'm working around it by doing a group by time(1m) and re-aggregating the values which forces one row per minute....

**Comment by beckettsean** [comment] 2015-07-22 21:28
Thanks, @jhedlund, this does seem like a duplicate of #3315. I'm going to close this in favor of that one. It seems very much like a bug but we don't have theories yet as to the cause.

**Closed by beckettsean** 2015-07-22 21:28 UTC
