### ISSUE TITLE
panic:Influx db is failing after few seconds

### ISSUE THREAD

**Issue by rahul9878** [influxdb/influxdb#4892] opened 2015-11-24 05:16 UTC
Hi,
We are working on influx db from one month, but now when i start the influx db server, after some time it shows its status "failed". and in the log file it show following content.

Log file content:

```
2015/11/24 00:06:14 InfluxDB starting, version 0.9.4.2, branch 0.9.4, commit da1b59e7d7764d36786253b2db13b97f42ed4e1d
2015/11/24 00:06:14 Go version go1.5, GOMAXPROCS set to 1
2015/11/24 00:06:15 Using configuration at: /etc/opt/influxdb/influxdb.conf
[metastore] 2015/11/24 00:06:15 Using data dir: /var/opt/influxdb/meta
[metastore] 2015/11/24 00:06:15 Skipping cluster join: already member of cluster: nodeId=1 raftEnabled=true peers=[localhost:8088]
[metastore] 2015/11/24 00:06:15 Node at localhost:8088 [Follower]
[metastore] 2015/11/24 00:06:16 Node at localhost:8088 [Leader]. peers=[localhost:8088]
[metastore] 2015/11/24 00:06:16 Updated node id=1 hostname=localhost:8088
[monitor] 2015/11/24 00:06:16 Starting monitor system
[monitor] 2015/11/24 00:06:16 'build' registered for diagnostics monitoring
[monitor] 2015/11/24 00:06:16 'runtime' registered for diagnostics monitoring
[monitor] 2015/11/24 00:06:16 'network' registered for diagnostics monitoring
[monitor] 2015/11/24 00:06:16 'system' registered for diagnostics monitoring
[store] 2015/11/24 00:06:16 Using data dir: /var/opt/influxdb/data
[monitor] 2015/11/24 00:06:16 Storing statistics in database '_internal' retention policy '', at interval 10s
[wal] 2015/11/24 00:06:16 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:16 WAL writing to /var/opt/influxdb/wal/_internal/monitor/61
[wal] 2015/11/24 00:06:16 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:16 WAL writing to /var/opt/influxdb/wal/_internal/monitor/64
[wal] 2015/11/24 00:06:16 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:16 WAL writing to /var/opt/influxdb/wal/_internal/monitor/65
[wal] 2015/11/24 00:06:16 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:16 WAL writing to /var/opt/influxdb/wal/_internal/monitor/66
[wal] 2015/11/24 00:06:16 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:16 WAL writing to /var/opt/influxdb/wal/_internal/monitor/67
[wal] 2015/11/24 00:06:16 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:16 WAL writing to /var/opt/influxdb/wal/eventdb/default/15
[wal] 2015/11/24 00:06:16 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:16 WAL writing to /var/opt/influxdb/wal/stagedb/default/14
[wal] 2015/11/24 00:06:16 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:16 WAL writing to /var/opt/influxdb/wal/stagedb/default/24
[wal] 2015/11/24 00:06:16 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:16 WAL writing to /var/opt/influxdb/wal/stagedb/default/34
[wal] 2015/11/24 00:06:16 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:16 WAL writing to /var/opt/influxdb/wal/stagedb/default/4
[wal] 2015/11/24 00:06:16 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:16 WAL writing to /var/opt/influxdb/wal/stagedb/default/46
[wal] 2015/11/24 00:06:16 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:16 WAL writing to /var/opt/influxdb/wal/stagedb/default/57
[wal] 2015/11/24 00:06:16 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:16 WAL writing to /var/opt/influxdb/wal/stagedb/default/6
[wal] 2015/11/24 00:06:16 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:16 WAL writing to /var/opt/influxdb/wal/stagedb/default/62
[wal] 2015/11/24 00:06:17 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:17 WAL writing to /var/opt/influxdb/wal/testdb/default/13
[wal] 2015/11/24 00:06:17 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:17 WAL writing to /var/opt/influxdb/wal/testdb/default/2
[wal] 2015/11/24 00:06:18 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:18 WAL writing to /var/opt/influxdb/wal/testdb/default/23
[wal] 2015/11/24 00:06:18 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:18 WAL writing to /var/opt/influxdb/wal/testdb/default/3
[wal] 2015/11/24 00:06:18 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:18 WAL writing to /var/opt/influxdb/wal/testdb/default/33
[wal] 2015/11/24 00:06:18 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:18 WAL writing to /var/opt/influxdb/wal/testdb/default/37
[wal] 2015/11/24 00:06:18 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:18 WAL writing to /var/opt/influxdb/wal/testdb/default/38
[wal] 2015/11/24 00:06:19 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:19 WAL writing to /var/opt/influxdb/wal/testdb/default/45
[wal] 2015/11/24 00:06:19 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:19 WAL writing to /var/opt/influxdb/wal/testdb/default/48
[wal] 2015/11/24 00:06:21 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:21 WAL writing to /var/opt/influxdb/wal/testdb/default/5
[wal] 2015/11/24 00:06:21 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:21 WAL writing to /var/opt/influxdb/wal/testdb/default/56
[wal] 2015/11/24 00:06:22 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/11/24 00:06:22 WAL writing to /var/opt/influxdb/wal/testdb/default/63
[wal] 2015/11/24 00:06:22 reading WAL files to flush to index
[retention] 2015/11/24 00:06:22 retention policy enforcement terminating
[monitor] 2015/11/24 00:06:22 shutting down monitor system
[monitor] 2015/11/24 00:06:22 terminating storage of statistics
run: open server: open tsdb store: failed to open shard 63: load metadata index: read block: EOF
```
can you please help me how to fix this issue
Thanks.

**Comment by timraymond** [comment] 2015-11-24 14:52
@beckettsean This log here looks similar to the one in #4566 . Same issue, perhaps?

**Comment by rahul9878** [comment] 2015-11-25 07:35
Issue is same but didn't find any solution for this.

**Comment by beckettsean** [comment] 2015-11-25 19:02
Closing as duplicate of https://github.com/influxdb/influxdb/issues/4566.

@rahul9878 there is no known solution right now, we are still trying to find a reliable repro case for this bug.

**Closed by beckettsean** 2015-11-25 19:02 UTC
