### ISSUE TITLE
Add timeout in the client

### ISSUE THREAD

**Issue by chmac** [influxdb/influxdb#1108] opened 2014-11-10 12:45 UTC
Under certain [failure scenarios](https://groups.google.com/forum/#!topic/influxdb/bZWj9jFuTwo), when the InfluxDB server accepts a connection but never responds, the Go client connects and waits forever (at least 12 hours). A rudimentary grep of the client code for "timeout" produces no results. It would be nice to be able to set a timeout, for example, if the server hasn't responded within 5 minutes, close the connection.

In our case, we're running a Go data collector from cron every minute, and under the failure scenario above, we have seen >600 processes running, all waiting for a response. :-(

**Comment by beckettsean** [comment] 2015-09-17 21:58
duplicate of #231

**Closed by beckettsean** 2015-09-17 21:58 UTC
Labels: 0 - Backlog
