### ISSUE TITLE
Influx 0.9.1 crashes when querying non-existent series from admin UI

### ISSUE THREAD

**Issue by buro1983** [influxdb/influxdb#3229] opened 2015-07-03 15:54 UTC
I have followed below command to install influx

wget https://s3.amazonaws.com/influxdb/influxdb-0.9.1-1.x86_64.rpm 
sudo rpm -ivh influxdb-0.9.1-1.x86_64.rpm

From UI if I execute "select * from SeriesName", Influx is crashing. SeriesName does not exist into DB. It suppose to return empty data set instead of crashing. Is there anything I am missing during installation?

**Comment by toddboom** [comment] 2015-07-03 15:56
@buro1983 are you running with the default configuration?

**Comment by buro1983** [comment] 2015-07-03 15:58
Yes

**Comment by otoolep** [comment] 2015-07-03 16:06
Just to be clear, InfluxDB does not panic when a non-existent series is selected:
```
$ curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE foo"
{"results":[{}]}
$ curl -G http://localhost:8086/query --data-urlencode 'q=SELECT * FROM cpu'
{"results":[{"error":"database name required"}]}
$ curl -G http://localhost:8086/query?db=foo --data-urlencode 'q=SELECT * FROM cpu'
{"results":[{"error":"measurement not found: \"foo\"..cpu"}]}
```
@buro1983 - if you can show a sequence similar to this that does crash, can you share it?

**Comment by toddboom** [comment] 2015-07-17 19:22
@buro1983 i can't reproduce this on master, so i'm going to close it out. if you're able to make it happen on `v0.9.2` or higher, please let me know!

**Closed by toddboom** 2015-07-17 19:22 UTC
Labels: category/queries
