### ISSUE TITLE
Basic math query panics server

### ISSUE THREAD

**Issue by corylanou** [influxdb/influxdb#4183] opened 2015-09-21 12:20 UTC
```
> create database math
> use math
Using database math
> insert mul a=1,b=2
> select * from mul
name: mul
---------
time                            a       b
2015-09-21T12:17:36.377625368Z  1       2

> select a*b as c from mul
ERR: Get http://localhost:8086/query?db=math&q=select+a%2Ab+as+c+from+mul: EOF
```

stack trace:

```
[query] 2015/09/21 07:17:47 SELECT a * b AS "c" FROM "math"."default".mul
panic: runtime error: index out of range

goroutine 44942 [running]:
github.com/influxdb/influxdb/influxql.newEchoProcessor.func1(0xc8202729e0, 0x2, 0x2, 0x0, 0x0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/influxql/result.go:98 +0x42
github.com/influxdb/influxdb/influxql.newBinaryExprEvaluator.func3(0xc8202729e0, 0x2, 0x2, 0x0, 0x0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/influxql/result.go:138 +0xb3
github.com/influxdb/influxdb/tsdb.processForMath(0xc820032070, 0x1, 0x1, 0xc820272a40, 0x1, 0x1, 0x0, 0x0, 0x0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tsdb/executor.go:995 +0x44c
github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).processValues(0xc82075a240, 0xc8203b0000, 0x1, 0x2710, 0x0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tsdb/executor.go:888 +0xdb1
github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).Flush(0xc82075a240)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tsdb/executor.go:789 +0xb5
github.com/influxdb/influxdb/tsdb.(*SelectExecutor).executeRaw(0xc8202d0ba0, 0xc8201825a0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tsdb/executor.go:252 +0x52b
created by github.com/influxdb/influxdb/tsdb.(*SelectExecutor).Execute
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tsdb/executor.go:95 +0xa1

goroutine 1 [chan receive, 4143 minutes]:
main.(*Main).Run(0xc8201c9f10, 0xc820078180, 0x0, 0x0, 0x0, 0x0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:91 +0xa16
main.main()
        /Users/corylanou/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:42 +0x29b

goroutine 17 [syscall, 4143 minutes, locked to thread]:
runtime.goexit()
        /usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 +0x1

goroutine 20 [syscall, 4143 minutes]:
os/signal.loop()
        /usr/local/Cellar/go/1.5.1/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/Cellar/go/1.5.1/libexec/src/os/signal/signal_unix.go:28 +0x37

goroutine 4 [IO wait, 4143 minutes]:
net.runtime_pollWait(0xd67d40, 0x72, 0xc8200780a0)
        /usr/local/Cellar/go/1.5.1/libexec/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82001a220, 0x72, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82001a220, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82001a1c0, 0x0, 0x1960000, 0xc820148000)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820032090, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820032090, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/tcpsock_posix.go:264 +0x3d
github.com/influxdb/influxdb/tcp.(*Mux).Serve(0xc820012d40, 0xd66dc0, 0xc820032090, 0x0, 0x0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tcp/mux.go:48 +0x4b
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1
        /Users/corylanou/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:347 +0xae9

goroutine 5 [chan receive, 4143 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc820032098, 0x0, 0x0, 0x0, 0x0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/meta.(*raftLayer).Accept(0xc820144150, 0x0, 0x0, 0x0, 0x0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/meta/store.go:2059 +0x51
github.com/hashicorp/raft.(*NetworkTransport).listen(0xc82001a2a0)
        /Users/corylanou/go/src/github.com/hashicorp/raft/net_transport.go:346 +0x79
created by github.com/hashicorp/raft.NewNetworkTransport
        /Users/corylanou/go/src/github.com/hashicorp/raft/net_transport.go:138 +0x284

goroutine 6 [select]:
github.com/hashicorp/raft.(*Raft).leaderLoop(0xc8200181c0)
        /Users/corylanou/go/src/github.com/hashicorp/raft/raft.go:807 +0xcce
github.com/hashicorp/raft.(*Raft).runLeader(0xc8200181c0)
        /Users/corylanou/go/src/github.com/hashicorp/raft/raft.go:779 +0x88e
github.com/hashicorp/raft.(*Raft).run(0xc8200181c0)
        /Users/corylanou/go/src/github.com/hashicorp/raft/raft.go:576 +0xbb
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.run)-fm()
        /Users/corylanou/go/src/github.com/hashicorp/raft/raft.go:241 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc8200181c0, 0xc820135750)
        /Users/corylanou/go/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
        /Users/corylanou/go/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 7 [select]:
github.com/hashicorp/raft.(*Raft).runFSM(0xc8200181c0)
        /Users/corylanou/go/src/github.com/hashicorp/raft/raft.go:490 +0x1022
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runFSM)-fm()
        /Users/corylanou/go/src/github.com/hashicorp/raft/raft.go:242 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc8200181c0, 0xc820135760)
        /Users/corylanou/go/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
        /Users/corylanou/go/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 8 [select, 1 minutes]:
github.com/hashicorp/raft.(*Raft).runSnapshots(0xc8200181c0)
        /Users/corylanou/go/src/github.com/hashicorp/raft/raft.go:1588 +0x493
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runSnapshots)-fm()
        /Users/corylanou/go/src/github.com/hashicorp/raft/raft.go:243 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc8200181c0, 0xc820135770)
        /Users/corylanou/go/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
        /Users/corylanou/go/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 9 [select, 4143 minutes]:
github.com/influxdb/influxdb/meta.(*localRaft).logLeaderChanges(0xc820014cd0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/meta/state.go:187 +0x4f5
created by github.com/influxdb/influxdb/meta.(*localRaft).open
        /Users/corylanou/go/src/github.com/influxdb/influxdb/meta/state.go:177 +0x1344

goroutine 10 [chan receive, 4143 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc8200320a0, 0x0, 0x0, 0x0, 0x0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/meta.(*Store).serveExecListener(0xc82013a000)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/meta/store.go:622 +0xa2
created by github.com/influxdb/influxdb/meta.(*Store).Open
        /Users/corylanou/go/src/github.com/influxdb/influxdb/meta/store.go:239 +0x364

goroutine 11 [chan receive, 4143 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc8200320a8, 0x0, 0x0, 0x0, 0x0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/meta.(*Store).serveRPCListener(0xc82013a000)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/meta/store.go:726 +0xa2
created by github.com/influxdb/influxdb/meta.(*Store).Open
        /Users/corylanou/go/src/github.com/influxdb/influxdb/meta/store.go:242 +0x3b6

goroutine 34 [select, 4143 minutes]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).monitorErrorChan(0xc82011e240, 0xc8200165a0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:493 +0x145
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1
        /Users/corylanou/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:353 +0xc67

goroutine 35 [select]:
github.com/influxdb/influxdb/monitor.(*Monitor).storeStatistics(0xc82011a680)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/monitor/service.go:333 +0x187c
created by github.com/influxdb/influxdb/monitor.(*Monitor).Open
        /Users/corylanou/go/src/github.com/influxdb/influxdb/monitor/service.go:134 +0x30c

goroutine 36 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc82023c000, 0xc820201020)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:605 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:241 +0x627

goroutine 37 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc82023c0e0, 0xc820201680)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:605 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:241 +0x627

goroutine 38 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc82023c1c0, 0xc820201aa0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:605 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:241 +0x627

goroutine 41 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc82023c460, 0xc8202e0600)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:605 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:241 +0x627

goroutine 42 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc82023c540, 0xc8202e0840)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:605 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:241 +0x627

goroutine 43 [select]:
github.com/influxdb/influxdb/services/hh.(*Service).retryWrites(0xc82013c000)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/services/hh/service.go:103 +0x314
created by github.com/influxdb/influxdb/services/hh.(*Service).Open
        /Users/corylanou/go/src/github.com/influxdb/influxdb/services/hh/service.go:67 +0x210

goroutine 44 [select, 3 minutes]:
github.com/influxdb/influxdb/services/hh.(*Service).expireWrites(0xc82013c000)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/services/hh/service.go:121 +0x2d1
created by github.com/influxdb/influxdb/services/hh.(*Service).Open
        /Users/corylanou/go/src/github.com/influxdb/influxdb/services/hh/service.go:68 +0x232

goroutine 45 [chan receive, 4143 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc8200320b0, 0x0, 0x0, 0x0, 0x0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/cluster.(*Service).serve(0xc82001a150)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/cluster/service.go:85 +0xdb
created by github.com/influxdb/influxdb/cluster.(*Service).Open
        /Users/corylanou/go/src/github.com/influxdb/influxdb/cluster/service.go:62 +0x135

goroutine 46 [select, 6 minutes]:
github.com/influxdb/influxdb/services/precreator.(*Service).runPrecreation(0xc820012a00)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/services/precreator/service.go:75 +0x44f
created by github.com/influxdb/influxdb/services/precreator.(*Service).Open
        /Users/corylanou/go/src/github.com/influxdb/influxdb/services/precreator/service.go:53 +0x21f

goroutine 47 [chan receive, 4143 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc8200320b8, 0x0, 0x0, 0x0, 0x0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/services/snapshotter.(*Service).serve(0xc820014820)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/services/snapshotter/service.go:75 +0xa9
created by github.com/influxdb/influxdb/services/snapshotter.(*Service).Open
        /Users/corylanou/go/src/github.com/influxdb/influxdb/services/snapshotter/service.go:48 +0x130

goroutine 48 [chan receive, 4143 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc8200320c0, 0x0, 0x0, 0x0, 0x0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/services/copier.(*Service).serve(0xc820012a80)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/services/copier/service.go:78 +0xa9
created by github.com/influxdb/influxdb/services/copier.(*Service).Open
        /Users/corylanou/go/src/github.com/influxdb/influxdb/services/copier/service.go:51 +0x130

goroutine 49 [IO wait, 4143 minutes]:
net.runtime_pollWait(0xd67c80, 0x72, 0xc8200780a0)
        /usr/local/Cellar/go/1.5.1/libexec/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82024ca70, 0x72, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82024ca70, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82024ca10, 0x0, 0x1960000, 0xc820137dc0)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc8201966c0, 0x55bd0, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc8201966c0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/tcpsock_posix.go:264 +0x3d
net/http.(*Server).Serve(0xc8200179e0, 0xd66dc0, 0xc8201966c0, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1887 +0xb3
net/http.Serve(0xd66dc0, 0xc8201966c0, 0xd68458, 0xc820135890, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1765 +0x85
github.com/influxdb/influxdb/services/admin.(*Service).serve(0xc820014910)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/services/admin/service.go:107 +0x12f
created by github.com/influxdb/influxdb/services/admin.(*Service).Open
        /Users/corylanou/go/src/github.com/influxdb/influxdb/services/admin/service.go:70 +0x491

goroutine 50 [select]:
github.com/influxdb/influxdb/services/continuous_querier.(*Service).backgroundLoop(0xc82013c120)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/services/continuous_querier/service.go:193 +0x565
created by github.com/influxdb/influxdb/services/continuous_querier.(*Service).Open
        /Users/corylanou/go/src/github.com/influxdb/influxdb/services/continuous_querier/service.go:127 +0x2a4

goroutine 51 [IO wait]:
net.runtime_pollWait(0xd67bc0, 0x72, 0xc8200780a0)
        /usr/local/Cellar/go/1.5.1/libexec/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82024cae0, 0x72, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82024cae0, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82024ca80, 0x0, 0x1960000, 0xc820272020)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc8201966c8, 0xc820174dc0, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc8201966c8, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/tcpsock_posix.go:264 +0x3d
net/http.(*Server).Serve(0xc8201df560, 0xd66dc0, 0xc8201966c8, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1887 +0xb3
net/http.Serve(0xd66dc0, 0xc8201966c8, 0x19a42d8, 0xc820116500, 0x0, 0x0)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1765 +0x85
github.com/influxdb/influxdb/services/httpd.(*Service).serve(0xc820016a80)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/services/httpd/service.go:133 +0x6e
created by github.com/influxdb/influxdb/services/httpd.(*Service).Open
        /Users/corylanou/go/src/github.com/influxdb/influxdb/services/httpd/service.go:101 +0x6ca

goroutine 52 [select, 3 minutes]:
github.com/influxdb/influxdb/services/retention.(*Service).deleteShardGroups(0xc820014aa0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/services/retention/service.go:69 +0x351
created by github.com/influxdb/influxdb/services/retention.(*Service).Open
        /Users/corylanou/go/src/github.com/influxdb/influxdb/services/retention/service.go:45 +0x1b4

goroutine 53 [select, 3 minutes]:
github.com/influxdb/influxdb/services/retention.(*Service).deleteShards(0xc820014aa0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/services/retention/service.go:102 +0x7a0
created by github.com/influxdb/influxdb/services/retention.(*Service).Open
        /Users/corylanou/go/src/github.com/influxdb/influxdb/services/retention/service.go:46 +0x1d9

goroutine 54 [chan receive, 1263 minutes]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).startServerReporting(0xc82011e240)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:444 +0x1eb
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1
        /Users/corylanou/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:380 +0x1265

goroutine 55 [select, 4143 minutes]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Command).monitorServerErrors(0xc820116200)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:138 +0x2c5
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run
        /Users/corylanou/go/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:120 +0xeeb

goroutine 56 [select, 4143 minutes, locked to thread]:
runtime.gopark(0x908958, 0xc82034ef28, 0x7c5e20, 0x6, 0x18, 0x2)
        /usr/local/Cellar/go/1.5.1/libexec/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc82034ef28, 0x0, 0x18)
        /usr/local/Cellar/go/1.5.1/libexec/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc82034ef28)
        /usr/local/Cellar/go/1.5.1/libexec/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
        /usr/local/Cellar/go/1.5.1/libexec/src/runtime/signal1_unix.go:227 +0x323
runtime.goexit()
        /usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 +0x1

goroutine 71 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc8203a21c0, 0xc82055c540)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:605 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:241 +0x627

goroutine 6379 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc8203a2000, 0xc820680480)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:605 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:241 +0x627

goroutine 18851 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc8203a20e0, 0xc820017500)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:605 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:241 +0x627

goroutine 44953 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc82023dc00, 0xc8200773e0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:605 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:241 +0x627

goroutine 36111 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc8203a22a0, 0xc820681920)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:605 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:241 +0x627

goroutine 44941 [chan receive]:
github.com/influxdb/influxdb/tsdb.(*QueryExecutor).executeSelectStatement(0xc820016720, 0x0, 0xc82075a180, 0xc820182540, 0x2710, 0x0, 0x0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tsdb/query_executor.go:288 +0xeb
github.com/influxdb/influxdb/tsdb.(*QueryExecutor).ExecuteQuery.func1(0xc820272200, 0xc82033a10e, 0x4, 0xc820016720, 0xc820182540, 0x2710)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tsdb/query_executor.go:162 +0x76c
created by github.com/influxdb/influxdb/tsdb.(*QueryExecutor).ExecuteQuery
        /Users/corylanou/go/src/github.com/influxdb/influxdb/tsdb/query_executor.go:216 +0x9b

goroutine 44940 [chan receive]:
github.com/influxdb/influxdb/services/httpd.(*Handler).serveQuery(0xc820116500, 0x19a4540, 0xc8202720e0, 0xc8203a2540, 0x0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:286 +0xc2c
github.com/influxdb/influxdb/services/httpd.(*Handler).(github.com/influxdb/influxdb/services/httpd.serveQuery)-fm(0x19a4540, 0xc8202720e0, 0xc8203a2540, 0x0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:98 +0x48
github.com/influxdb/influxdb/services/httpd.authenticate.func1(0x19a4540, 0xc8202720e0, 0xc8203a2540)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:673 +0x70
net/http.HandlerFunc.ServeHTTP(0xc820136da0, 0x19a4540, 0xc8202720e0, 0xc8203a2540)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.gzipFilter.func1(0x19a4468, 0xc8202720a0, 0xc8203a2540)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:734 +0x2af
net/http.HandlerFunc.ServeHTTP(0xc820136dc0, 0x19a4468, 0xc8202720a0, 0xc8203a2540)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.versionHeader.func1(0x19a4468, 0xc8202720a0, 0xc8203a2540)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:743 +0xc0
net/http.HandlerFunc.ServeHTTP(0xc820136de0, 0x19a4468, 0xc8202720a0, 0xc8203a2540)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.cors.func1(0x19a4468, 0xc8202720a0, 0xc8203a2540)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:776 +0x328
net/http.HandlerFunc.ServeHTTP(0xc820136e00, 0x19a4468, 0xc8202720a0, 0xc8203a2540)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.requestID.func1(0x19a4468, 0xc8202720a0, 0xc8203a2540)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:786 +0x15d
net/http.HandlerFunc.ServeHTTP(0xc820136e20, 0x19a4468, 0xc8202720a0, 0xc8203a2540)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.logging.func1(0x19a4468, 0xc820272080, 0xc8203a2540)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:794 +0x10b
net/http.HandlerFunc.ServeHTTP(0xc820136e40, 0x19a4468, 0xc820272080, 0xc8203a2540)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.recovery.func1(0x19a4408, 0xc8200ba4d0, 0xc8203a2540)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:813 +0x168
net/http.HandlerFunc.ServeHTTP(0xc820136e60, 0x19a4408, 0xc8200ba4d0, 0xc8203a2540)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1422 +0x3a
github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc820032060, 0x19a4408, 0xc8200ba4d0, 0xc8203a2540)
        /Users/corylanou/go/src/github.com/bmizerany/pat/mux.go:109 +0x244
github.com/influxdb/influxdb/services/httpd.(*Handler).ServeHTTP(0xc820116500, 0x19a4408, 0xc8200ba4d0, 0xc8203a2540)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:172 +0x357
net/http.serverHandler.ServeHTTP(0xc8201df560, 0x19a4408, 0xc8200ba4d0, 0xc8203a2540)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8200ba370)
        /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
        /usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1910 +0x3f6

```

**Comment by otoolep** [comment] 2015-09-21 15:20
Dupe of https://github.com/influxdb/influxdb/issues/4046, fix is not trivial and we should wait until we have the new engine in place before attempting a fix.

**Closed by otoolep** 2015-09-21 15:20 UTC
