### ISSUE TITLE
[0.9.0] Ubuntu 14.04 service crashing

### ISSUE THREAD

**Issue by maxcanada** [influxdb/influxdb#3016] opened 2015-06-17 09:49 UTC
Hi, 

Here is what I tried via the CLI interface : 
curl -i -XPOST 'http://localhost:8086/write?db=prncpss' -d 'cpu_load_short,host=server01,region=us-west value=0.64 1434055562000000000'

Here is the response : 
HTTP/1.1 204 No Content
Request-Id: 8656ddbd-14d4-11e5-8023-000000000000
X-Influxdb-Version: FIXME
Date: Wed, 17 Jun 2015 09:37:53 GMT

I tried to SELECT * from cpu_load_short, I got this : 

ERR: Get http://localhost:8086/query?db=&q=select+%2A+from+cpu_load_short: EOF

And the service was shut down. I had to restart it. Again, every time I try to select from cpu_load_short, the service crashes.

Thanks a lot,

**Comment by neonstalwart** [comment] 2015-06-17 14:19
this is a duplicate of #2932.  you're missing a database name in the query string. `?db=&q=select+%2A+from+cpu_load_short` - see the `db=&...`, it should be `db=prncpss&...`

**Comment by otoolep** [comment] 2015-06-17 15:33
Please add the database param as described by @neonstalwart

**Closed by otoolep** 2015-06-17 15:33 UTC
