### ISSUE TITLE
[0.9.4 built off master] Cant do arithmetic on multiple fields

### ISSUE THREAD

**Issue by mjdesa** [influxdb/influxdb#4046] opened 2015-09-09 00:11 UTC
Any mathematical expression involving two fields causes influx to crash
```
> insert m v1=1,v2=2
> select v1 - v2 from m
ERR: Get http://localhost:8086/query?db=idk&q=select+v1+-+v2+from+m: EOF
```

```
panic: runtime error: index out of range

goroutine 414 [running]:
github.com/influxdb/influxdb/influxql.func·027(0xc2090617e0, 0x2, 0x2, 0x0, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/influxql/result.go:151 +0x4a
github.com/influxdb/influxdb/influxql.func·029(0xc2090617e0, 0x2, 0x2, 0x0, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/influxql/result.go:173 +0xa8
github.com/influxdb/influxdb/influxql.func·029(0xc2090617e0, 0x2, 0x2, 0x0, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/influxql/result.go:172 +0x67
github.com/influxdb/influxdb/tsdb.processForMath(0xc20eadfe58, 0x1, 0x1, 0xc209061820, 0x1, 0x1, 0x0, 0x0, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/tsdb/executor.go:989 +0x4ad
github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).processValues(0xc20807c600, 0xc210b72000, 0x1, 0x2710, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/tsdb/executor.go:882 +0xf45
github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).Flush(0xc20807c600)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/tsdb/executor.go:783 +0xd6
github.com/influxdb/influxdb/tsdb.(*SelectExecutor).executeRaw(0xc210b5a7e0, 0xc210453620)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/tsdb/executor.go:251 +0x4e2
created by github.com/influxdb/influxdb/tsdb.(*SelectExecutor).Execute
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/tsdb/executor.go:94 +0x9a

goroutine 1 [chan receive]:
main.(*Main).Run(0xc20806bb40, 0xc20800a000, 0x0, 0x0, 0x0, 0x0)
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:91 +0x777
main.main()
	/Users/michaeldesa/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:42 +0xdc

goroutine 6 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/local/go/src/os/signal/signal_unix.go:27 +0x35
```

**Comment by otoolep** [comment] 2015-09-09 00:45
Dupe of https://github.com/influxdb/influxdb/issues/3200

**Comment by beckettsean** [comment] 2015-09-09 00:50
@otoolep this seems cleaner than #3200, which has a lot of confusion about duplicate field names. Should we close #3200 in favor of this one?

**Comment by otoolep** [comment] 2015-09-09 01:01
I'm OK with that @beckettsean

**Comment by corylanou** [comment] 2015-09-21 15:29
Adding math as a keyword on this issue.  It was what I searched on and couldn't find this issue, and resulted in my creating a dupe.

**Comment by stropa** [comment] 2015-10-11 16:16
+1

**Comment by kostya-sh** [comment] 2015-10-12 03:09
Also dup of #4352

**Comment by pfennema** [comment] 2015-10-21 13:47
Any idea when the issue of field calculations can be fixed? This functionality is for us an important factor to decide whether to continue with influxdb or not. Thanks! Again, really appreciating the work

**Comment by bww** [comment] 2015-11-05 00:15
Does anyone know in which version this regression was introduced? Obviously we can't have this service crashing every minute, so we need to roll back to the latest version that works correctly.

**Comment by otoolep** [comment] 2015-11-05 01:12
@bww -- I believe this bug was introduced after 0.9.1. The query engine is undergoing significant refactor at the moment and the fix for this issue in the latest code will have to wait until that is finished.

**Comment by otoolep** [comment] 2015-11-05 01:17
Blocked by the query refactor redesign here: https://github.com/influxdb/influxdb/issues/4631

**Comment by otoolep** [comment] 2015-11-07 02:06
@benbjohnson will be fixing this as part of his query engine refactor.

**Comment by malnor** [comment] 2015-11-26 12:22
+1

**Comment by otoolep** [comment] 2015-12-04 14:17
Should be fixed by https://github.com/influxdb/influxdb/pull/4984

**Closed by otoolep** 2015-12-04 14:17 UTC
Labels: panic, support

**Comment by mjdesa** [comment] 2015-12-04 18:26
@otoolep you sure? I'm still getting a panic on master.

**Comment by otoolep** [comment] 2015-12-04 18:30
Change was backed out pending CLA.

**Comment by otoolep** [comment] 2015-12-04 19:06
Merged now, build from master @mjdesa and let us know what you find.

**Comment by mjdesa** [comment] 2015-12-04 19:09
@otoolep works :+1:

**Comment by otoolep** [comment] 2015-12-04 19:10
Great! Thanks again to mengjinglei!
