### ISSUE TITLE
[0.9.5] show measurements broken

### ISSUE THREAD

**Issue by allen13** [influxdb/influxdb#4885] opened 2015-11-23 20:00 UTC
From the influxdb admin interface:
Server returned error: json: cannot unmarshal array into Go value of type tsdb.MapperOutputJSON

**Comment by otoolep** [comment] 2015-11-23 20:03
Thanks for the report, please be sure to look for similar issues though.

Dupe of https://github.com/influxdb/influxdb/issues/4550 and should be fixed by https://github.com/influxdb/influxdb/pull/4833

**Closed by otoolep** 2015-11-23 20:03 UTC
