### ISSUE TITLE
Weird performance downgrade from 0.8.8 to 0.9.2

### ISSUE THREAD

**Issue by dalibor** [influxdb/influxdb#3531] opened 2015-08-01 22:01 UTC
I see very weird (and huge) performance downgrade from 0.8.8 to 0.9.2 on 64bit Ubuntu 14.04.2 using pre-built packages (influxdb_0.8.8_amd64.deb and influxdb_0.9.2_amd64.deb). I use the default configs, start service, ensure blank DB (drop/create) and then do 10000 inserts via apache benchmark (same performance issue when testing with the ruby client).

- 0.8.8

```
ab -n 10000 -c 1 -p post1.txt 'http://localhost:8086/db/mydb/series?time_precision=s&u=root&p=root'
```

Total time is `5.746` seconds. post1.txt content:

```
[{"name":"emails","points":[[0,"email1@example.com","example","10.0.0.2"]],"columns":["duration","from","sld","ip"]}]
```

- 0.9.2

```
ab -n 10000 -c 1 -p post2.txt 'http://localhost:8086/write?db=mydb&precision=s&u=root&p=root'
```

Total time is `272.571` seconds. post2.txt content:

```
emails,type=example,sld=yahoo,ip=10.0.0.2 interval=123
```

I consistently get similar results (~ 50 times slower 0.9.2 vs 0.8.8) after switching versions multiple times. Any ideas what could be causing this?

One weird thing I notice in the log for 0.9.2 is that after every `stop` service command and then when starting the service I get one more line like below added vs the previous start (meaning on the last start I have that line printed out 70 times -- not sure if that could be somehow related).

```
[metastore] 2015/08/01 23:35:44 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
```

Thanks!

**Comment by beckettsean** [comment] 2015-08-03 18:54
10000 single inserts of the line protocol is a tremendously inefficient way to use it. Try batching those writes into groups of 1-5k and you should see the performance improve substantially.

We have an open [docs issue](https://github.com/influxdb/influxdb.com/issues/188) to describe how best to tune things for write performance. Otherwise this is not an actionable issue, closing.

**Closed by beckettsean** 2015-08-03 18:54 UTC

**Comment by dalibor** [comment] 2015-08-03 20:16
Thanks for your response Sean! Is the 50x performance downgrade expected? Did you do some benchmarks between 0.8.8 and 0.9.2 to share some numbers? It's weird for such a huge performance downgrade tbh, I'm still wondering if it's something with the pre-built Ubuntu package. :/

**Comment by beckettsean** [comment] 2015-08-03 22:35
We don't have performance benchmarks on comparable systems but those will be coming later next month. We do know that 0.9.2 is not yet back to the performance of version 0.8.8. There were a great many architectural changes in the 0.9 line and much of the internals have been fully re-written. I can certainly believe that a well tuned 0.8.8 instance would be many times as fast as an untuned 0.9.2 instance, especially with totally unbatched writes. 50x is high but not unimaginable.

Also, no one else has reported any Ubuntu-specific issue with performance, so I highly doubt there's anything wrong with the binary package.

**Comment by thetcc** [comment] 2015-08-05 16:10
It's bad performance on mac os,
10 threads to insert 10000 very simple data, cost more than 30 seconds.

**Comment by gunnaraasen** [comment] 2015-08-05 17:06
@thetcc which version did you test and are you batching writes into a single request?

Note that there is also some additional overhead when writing to a new series (unique measurement + tag set) for the first time.

**Comment by thetcc** [comment] 2015-08-14 10:13
@gunnaraasen 
Thank you for your reply，the version is 0.9.2.
I'm not doing a bulk write request, I know. That might be faster.
Like mysql database, insert records one by one, you can insert more than 10,000 records in one second, in my macbook pro.
But the 0.9.2 version of influxdb, 10000 records, one by one to write, takes more than 30 seconds.

If influxdb only batch write performance was high. I think influxdb upon receipt of written request should first cached, when accumulated to a certain amount, then a batch write. Rather than letting the caller must be accumulated to a certain amount in order to do batch write.

**Comment by beckettsean** [comment] 2015-08-14 18:31
@thetcc MySQL is over 20 years old. InfluxDB 0.9 is barely 6 months old. They address very different problems by design. Comparing their performance is mostly pointless, I think. However, if MySQL is giving you the features and performance you need with no modifications to your code perhaps that is the right tool for your use case. 

If you want to use InfluxDB, it is important to follow the best practices, which currently include batching your writes before sending them in. An upcoming release will most likely include an automatic internal batching system but it is not a high priority. The workaround is fairly trivial, which is to batch the writes client-side before sending them.

Some client libraries will batch for you, including https://github.com/influxdb/telegraf/.

**Comment by beckettsean** [comment] 2015-08-14 18:33
@thetcc in addition, 10000 inserts into InfluxDB means 10000 separate HTTP requests. That's a huge overhead to impose. That's why batching is important.
