### ISSUE TITLE
web client bug

### ISSUE THREAD

**Issue by kcrosswind** [influxdb/influxdb#3323] opened 2015-07-14 15:52 UTC
in 0.9 , the web client can not work , i use data explore to write data, but always tell me bad request

**Comment by gunnaraasen** [comment] 2015-07-14 16:21
Please provide some example points. Do the points return an error when written directly to the InfluxDB API via curl?

**Comment by kcrosswind** [comment] 2015-07-14 16:32
hi @gunnaraasen 
like curl -XPOST 'http://localhost:8086/write?db=mydb' -d 'cpu,host=server01,region=uswest value=1.0'
when i use the web client clike the database and clike data explore. there is a method to write data by JSON Payload . i do not know how to use it by the json data.like {table = cpu, value=1.0}

**Comment by kcrosswind** [comment] 2015-07-14 16:38
hi @gunnaraasen 
i have a problem, how can i cover the curl to java? what is the param like -d 'cpu,host=server01,region=uswest value=1.0'
thank you very much. I'm confused for a long time

**Comment by gunnaraasen** [comment] 2015-07-14 17:30
Writing points with the JSON protocol via the InfluxDB 0.9.1 web admin is not supported. There is an InfluxDB [Java client library](https://github.com/influxdb/influxdb-java).

Closing this issue since it there is no reproducible error. Questions like this should be sent to the [mailing list](https://groups.google.com/forum/#!forum/influxdb).

**Closed by gunnaraasen** 2015-07-14 17:30 UTC

**Comment by beckettsean** [comment] 2015-07-14 18:01
@kcrosswind when using `curl` to write in the line protocol you must use the `--data-binary` flag, not `-d`. For example:

`curl -XPOST 'http://localhost:8086/write?db=mydb' --data-binary 'cpu,host=server01,region=uswest value=1.0'`

**Comment by kcrosswind** [comment] 2015-07-15 06:24
@beckettsean @gunnaraasen 
i found points with the JSON protocol via the InfluxDB 0.9.1 web admin is not supported.
but the web client 8083 have the method, it is easy to confuse , if have method, but not support.

thank you for you help
