### ISSUE TITLE
Stack trace from the mailing list

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#3742] opened 2015-08-19 20:00 UTC
Can't reproduce this, but I'm guessing digging into the raw query executor will reveal why `chunkedOutput` here https://github.com/influxdb/influxdb/blob/master/tsdb/executor.go#L291 is nil.

At the very least we can check if it's nil and log an error. A query should never panic the server.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x591a31]

goroutine 3707 [running]:
github.com/influxdb/influxdb/tsdb.(*Executor).executeRaw(0xc20f27e000, 0xc20bd3da40)
        /root/go/src/github.com/influxdb/influxdb/tsdb/executor.go:291 +0xd41
created by github.com/influxdb/influxdb/tsdb.(*Executor).Execute
        /root/go/src/github.com/influxdb/influxdb/tsdb/executor.go:88 +0x9a

goroutine 1 [chan receive, 40 minutes]:
main.(*Main).Run(0xc20806bb00, 0xc20800a010, 0x4, 0x4, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:91 +0x777
main.main()
        /root/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:42 +0xdc

goroutine 6 [syscall, 41 minutes]:
os/signal.loop()
        /root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, 41 minutes, locked to thread]:
runtime.goexit()
        /root/.gvm/gos/go1.4.2/src/runtime/asm_amd64.s:2232 +0x1

goroutine 8 [IO wait, 41 minutes]:
net.(*pollDesc).Wait(0xc208010450, 0x72, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010450, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc2080103f0, 0x0, 0x7f625d464e30, 0xc2080fe000)
        /root/.gvm/gos/go1.4.2/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208038e90, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc208038e90, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:244 +0x4c
github.com/influxdb/influxdb/tcp.(*Mux).Serve(0xc2080e48a0, 0x7f625d4673c8, 0xc208038e90, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/tcp/mux.go:45 +0x57
```

**Comment by otoolep** [comment] 2015-08-19 20:17
Yeah, saw this go by on the mailing list. I'll take a look.

**Comment by nathanielc** [comment] 2015-08-21 20:17
I am able to reproduce this. I have a lot going on in my server but the error always follows a query like `select * from cpu`. I only have  a few minutes of data on the server hence why I didn't put a time range or anything on the query. Hope that helps. If I discover anything more specific to the error I'll post and update.

**Comment by otoolep** [comment] 2015-08-21 20:24
Thanks @nathanielc -- that might be a clue.

**Comment by pauldix** [comment] 2015-08-21 20:43
@nathanielc I just pushed something to master and the 0.9.3 branch that might do something with this. Can you confirm really quick? Is it easy for you to repro?

**Comment by nathanielc** [comment] 2015-08-21 20:46
@pauldix  Yeah, give me a sec.

**Comment by nathanielc** [comment] 2015-08-21 21:22
I still get the same nil pointer error with a build from a52a4be94c1d408e39db956e7684dfb1a1e25354. 
I can't reproduce it every time. Most of the time the query `select * from cpu` works but about 1 in 5 crashes the server. I get the error whether I am writing data or not to the cpu measurement.

**Comment by pkittenis** [comment] 2015-08-21 21:42
Interesting - have not been able to reproduce this at all. As far as I know it was just regular grafana generated queries that triggered it.

**Comment by otoolep** [comment] 2015-08-21 22:03
@nathanielc -- do you need to be writing data to the server to get the query to panic it? If not, would be you be willing to supply us the data sitting underneath your server? Or if it does require queries, can you supply those as well as the data?

**Comment by nathanielc** [comment] 2015-08-21 22:06
FWIW I am able to reproduce this better with smaller datasets. If I wipe the data (via rm on the data dir) and run the query after just a minute or two from startup I can get the error. The query has only caused a crash once in my tests if I wait for more than about 5 minutes after startup.

@otoolep Sure, its all test data from a vagrant env. Would you like a influxdb dump from the backup command or would a tar of the actual datadirs be better?

I don't have to be writing data but as mentioned above it seems somehow related to dataset size.

**Comment by nathanielc** [comment] 2015-08-21 22:15
@otoolep Here is a tarbal of the data and the binary I am using. Running the `select * from cpu` query crashes the server:

https://drive.google.com/file/d/0B6qYY1KbxS-uU3hHVndEbGRlbFU/view?usp=sharing

**Comment by otoolep** [comment] 2015-08-21 22:19
Great, thanks @nathanielc -- very helpful. Can I see your config file too?

**Comment by nathanielc** [comment] 2015-08-21 22:23
Ah yes:

```
reporting-disabled = true
[meta]
  dir = "/var/lib/influxdb/meta"
  bind-address = ":8088"
  retention-autocreate = true
  election-timeout = "1s"
  heartbeat-timeout = "1s"
  leader-lease-timeout = "500ms"
  commit-timeout = "50ms"

[data]
  dir = "/var/lib/influxdb/data"
  wal-dir = "/var/lib/influxdb/wal"
  max-wal-size = 104857600
  wal-flush-interval = "10m0s"
  wal-partition-flush-delay = "2s"
  wal-enable-logging = true
  wal-ready-series-size = 30720
  wal-compaction-threshold = 0.5
  wal-max-series-size = 1048576
  wal-flush-cold-interval = "5m0s"
  wal-partition-size-threshold = 20971520
  retention-auto-create = true
  retention-check-enabled = true
  retention-check-period = "10m0s"
  retention-create-period = "45m0s"

[cluster]
  shard-writer-timeout = "15s"
  write-timeout = "15s"

[retention]
  enabled = false
  #enabled = true
  #replication = 3
  check-interval = "10m0s"

[shard-precreation]
  enabled = true
  check-interval = "10m0s"
  advance-period = "30m0s"

[admin]
  enabled = true
  bind-address = ":8083"

[http]
  enabled = true
  bind-address = ":8086"
  auth-enabled = false
  log-enabled = true
  write-tracing = false
  pprof-enabled = false

[collectd]
  enabled = false
  bind-address = ":25826"
  database = "collectd"
  retention-policy = ""
  batch-size = 5000
  batch-timeout = "10s"
  typesdb = "/usr/share/collectd/types.db"

[opentsdb]
  enabled = true
  bind-address = ":4242"
  database = "collectd"
  retention-policy = ""
  consistency-level = "all"

[[udp]]
  enabled = false
  bind-address = ""
  database = ""
  batch-size = 0
  batch-timeout = "0"

[monitoring]
  enabled = false
  write-interval = "1m0s"

[continuous_queries]
  enabled = true
  recompute-previous-n = 2
  recompute-no-older-than = "10m0s"
  compute-runs-per-interval = 10
  compute-no-more-than = "2m0s"

[hinted-handoff]
  enabled = true
  dir = "/var/lib/influxdb/hh"
  max-size = 1073741824
  max-age = "168h0m0s"
  retry-rate-limit = 0
  retry-interval = "1s"
```

Should be pretty straight forward.

**Comment by otoolep** [comment] 2015-08-21 22:24
I have successfully installed your data under a system running the latest master code. I cannot repro the crash however.

```
InfluxDB shell 0.9
> show databases
name: databases
---------------
name
collectd

> use collectd
Using database collectd
> show measurements
name: measurements
------------------
name
cpu
df
disk
interface
load
loxyd
memory
my_app_name
processes
swap

> select * from cpu
> select * from cpu
> select * from cpu
> select * from cpu
> select * from cpu
> select * from cpu
> select * from cpu
> select * from cpu
> select * from cpu
> 
```
My server stays up during this entire time.

**Comment by otoolep** [comment] 2015-08-21 22:25
It does crash with the binary you built however.

Not sure what to say. Have you modified the source?

**Comment by otoolep** [comment] 2015-08-21 22:25
Can you try again with top-of-tree master?

**Comment by otoolep** [comment] 2015-08-21 22:26
Top-of-tree 0.9.3 branch works fine too.

**Comment by nathanielc** [comment] 2015-08-21 22:28
What about last nights nightly build? I am pretty sure I was able to repo with that binary too.

Rebuilding now...

**Comment by nathanielc** [comment] 2015-08-21 22:51
So I was unable to reproduce with a clean top-of-tree master build. I had built influxdb on my host before so maybe I had an old go env or something.

**Comment by otoolep** [comment] 2015-08-21 22:53
OK, thanks @nathanielc -- are you comfortable closing this? As you know, we had a ton of fixes go in during the last 24 hours, so I think it's fair if we close.

**Comment by nathanielc** [comment] 2015-08-21 22:56
Yep that sounds good. I'll test tomorrow once more with a nightly build so that I know my env is clean. If it fails I'll post here.

**Closed** 2015-08-21 22:58 UTC
Labels: category/queries
