### ISSUE TITLE
Wire up difference aggregate function

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#1590] opened 2015-02-12 15:50 UTC
Takes the difference between one group by interval and another. The user should be able to stack this to specify the behavior like this:

```sql
SELECT difference(mean(value)) from key_count
WHERE time > now() - 1h
GROUP BY time(5m)
```

If no group by time is given, then it should be a transformation function that takes the difference between one point and another. In that case they shouldn't be able to nest function calls like this.

**Comment by dgnorton** [comment] 2015-03-03 18:44
Closing.  Duplicate of #1825

**Closed by dgnorton** 2015-03-03 18:44 UTC
