### ISSUE TITLE
DELETE measure NOT RUN?

### ISSUE THREAD

**Issue by jmptrader** [influxdb/influxdb#3440] opened 2015-07-23 00:15 UTC
Dear,
The next query, not run in InfluxDB v0.9.1

delete from runtime where time>'2015-01-01' and time<'2015-07-22'

Please, any comments,

Thank's.

**Comment by beckettsean** [comment] 2015-07-23 00:23
There is an open issue to make DELETE work again. It has not worked in the 0.9.x line. 

Closing as a duplicate of https://github.com/influxdb/influxdb/issues/1647

**Closed by beckettsean** 2015-07-23 00:23 UTC
