### ISSUE TITLE
TSM1: panic: decode of short block: got 1, exp 9

### ISSUE THREAD

**Issue by fatmcgav** [influxdb/influxdb#4521] opened 2015-10-21 09:25 UTC
I am testing InfluxDB 0.9.5 Nightly with Sensu and Grafana, and have experienced a couple of InfluxDB crashes... 
I put the first one down to user error, however have now had a repeat. 

I am running: `InfluxDB shell 0.9.5-nightly-66a31ee` installed from nightly RPM on a CentOS 6.5 VM running in Parallels on OS X 10.11. 

The log file is here: https://gist.github.com/fatmcgav/b997941c053a0f155160

Let me know if you need any further info. 

Cheers
Gav

**Comment by fatmcgav** [comment] 2015-10-21 09:33
OK, so I just managed to reproduce the Panic by re-running the same query from Grafan... 

So it's something about this query that is causing InfluxDB to panic: 
`SELECT mean(system) AS "system", mean(iowait) AS "iowait", mean("user") AS "user", mean(idle) AS "idle" FROM "graphite"."default".cpu WHERE host =~ /sensu*/ AND time > now() - 1d GROUP BY time(1m), host`

**Comment by fatmcgav** [comment] 2015-10-21 13:22
OK, further testing suggest that it's the `AND time > now() - 1d` that's causing InfluxDB to panic... 

If I go shorter, e.g. ` - 1h`, or `- 15m` then the query works. 
Anything longer, and InfluxDB panic's... 
> [query] 2015/10/21 14:19:30 SELECT mean(system) AS "system", mean(iowait) AS "iowait", mean("user") AS "user", mean(idle) AS "idle" FROM "graphite"."default".cpu WHERE host =~ /sensu*/ AND time > now() - 1w GROUP BY time(5m), host
panic: decode of short block: got 1, exp 9

**Comment by jwilder** [comment] 2015-10-21 15:18
When you upgraded to the new nightly, did you delete your data and start with a clean DB?

**Comment by fatmcgav** [comment] 2015-10-21 15:21
@jwilder I haven't upgraded the nightly yet...

**Comment by jwilder** [comment] 2015-10-21 16:28
@fatmcgav I meant when you started running `66a31ee`.  Were you running an `0.9.5` (or any) nightly before that?  If so, did you remove your data files before upgrading to it?

**Comment by fatmcgav** [comment] 2015-10-21 16:30
Ah, ok… 

No, this was a fresh install with no previous data.

**Comment by jwilder** [comment] 2015-10-21 16:34
The panic looks like could be is an issue in the blocks that the TSM engine has written or the cursors.  A block to be decoded was too small so it panic'd.

**Comment by jwilder** [comment] 2015-10-27 19:22
This panic is caused by writing `NaN` float values.  #4587 should fix this.

**Comment by fatmcgav** [comment] 2015-10-27 21:59
Cheers for the quick fix. Will try the nightly tomorrow...

**Comment by jwilder** [comment] 2015-10-27 22:00
@fatmcgav Watch for #4587 to be merged.  It's not merged yet.

**Comment by fatmcgav** [comment] 2015-10-27 22:05
Ah, there's me trying to jump the gun... Will do, cheers...

**Closed** 2015-10-28 15:28 UTC
Labels: 2 - Working, tsm
