### ISSUE TITLE
[feature request] discontinuous queries on the timeline, e.g. group by hour of day

### ISSUE THREAD

**Issue by tecbea** [influxdb/influxdb#2241] opened 2015-04-11 13:28 UTC
It will be great to have a aggregation query for a time;

example:
I want to get a pattern of a value in a day, on a hour basis
so for a interval of time, give me the mean for each hour

result = hour0:mean = 1 , hour 1 : mean = 234 , ...

the idea is to get patterns from timeseries from a basic query;

discussed with Sean on groups:
" (effectively each query first selects a single hour of the day and then performs the aggregation, so the aggregated series are not continuous in time). "

**Comment by beckettsean** [comment] 2015-09-17 22:44
closing as dupe of #1871

**Closed by beckettsean** 2015-09-17 22:44 UTC
