### ISSUE TITLE
influx DB Backup/Snapshot not working

### ISSUE THREAD

**Issue by schavalmane** [influxdb/influxdb#4925] opened 2015-11-29 21:54 UTC
The influxdb also crashes.  is there a way I can copy some directory and save the data?
Also we should not have hardcodings  like ( /home/philip/.gvm/gos)

Comand ( any location)

./influxd backup /tmp/snapshot

Log Message:

     /home/philip/.gvm/gos/go1.5/src/io/io.go:427 +0xbd
bufio.(*Reader).fill(0xc820a4b0e0)
        /home/philip/.gvm/gos/go1.5/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc820a4b0e0, 0xc81ffa300a, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadLine(0xc820a4b0e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/bufio/bufio.go:357 +0x53
net/textproto.(*Reader).readLineSlice(0xc820828090, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/textproto/reader.go:55 +0x81
net/textproto.(*Reader).ReadLine(0xc820828090, 0x0, 0x0, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/textproto/reader.go:36 +0x40
net/http.ReadRequest(0xc820a4b0e0, 0xc820b9e000, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/http/request.go:653 +0xb6
net/http.(*conn).readRequest(0xc820097550, 0x0, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/http/server.go:633 +0x32f
net/http.(*conn).serve(0xc820097550)
        /home/philip/.gvm/gos/go1.5/src/net/http/server.go:1319 +0x727
created by net/http.(*Server).Serve
        /home/philip/.gvm/gos/go1.5/src/net/http/server.go:1910 +0x3f6

goroutine 360 [IO wait]:
net.runtime_pollWait(0x7f12c942d650, 0x72, 0xc8200101a0)
        /home/philip/.gvm/gos/go1.5/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820b3a060, 0x72, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820b3a060, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820b3a000, 0xc820019000, 0x1000, 0x1000, 0x0, 0x7f12c9427050, 0xc8200101a0)
        /home/philip/.gvm/gos/go1.5/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820818000, 0xc820019000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/net.go:172 +0xe4
net/http.(*liveSwitchReader).Read(0xc8200cc3b8, 0xc820019000, 0x1000, 0x1000, 0x500, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/http/server.go:219 +0xa4
io.(*LimitedReader).Read(0xc8207b4000, 0xc820019000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/io/io.go:427 +0xbd
bufio.(*Reader).fill(0xc820bb6000)
        /home/philip/.gvm/gos/go1.5/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc820bb6000, 0xffffffffffff910a, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadLine(0xc820bb6000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/bufio/bufio.go:357 +0x53
net/textproto.(*Reader).readLineSlice(0xc820e70090, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/textproto/reader.go:55 +0x81
net/textproto.(*Reader).ReadLine(0xc820e70090, 0x0, 0x0, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/textproto/reader.go:36 +0x40
net/http.ReadRequest(0xc820bb6000, 0xc8204f56c0, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/http/request.go:653 +0xb6
net/http.(*conn).readRequest(0xc8200cc370, 0x0, 0x0, 0x0)
        /home/philip/.gvm/gos/go1.5/src/net/http/server.go:633 +0x32f
net/http.(*conn).serve(0xc8200cc370)
        /home/philip/.gvm/gos/go1.5/src/net/http/server.go:1319 +0x727
created by net/http.(*Server).Serve
        /home/philip/.gvm/gos/go1.5/src/net/http/server.go:1910 +0x3f6
2015/11/29 16:49:00 InfluxDB starting, version 0.9.4.2, branch 0.9.4, commit da1b59e7d7764d36786253b2db13b97f42ed4e1d
2015/11/29 16:49:00 Go version go1.5, GOMAXPROCS set to 8

**Comment by otoolep** [comment] 2015-11-29 22:53
There were multiple fixes to backup in 0.9.5, you might have better luck if you try the latest code.

https://influxdb.com/download/index.html#download

Download and install 0.9.5.1.

**Comment by schavalmane** [comment] 2015-11-30 00:30
I will need steps to upgrade . How do I upgrade without destroying the data
?

Can we fix the backup in exiting version ?

On Sunday, November 29, 2015, otoolep <notifications@github.com> wrote:

> There were multiple fixes to backup in 0.9.5, you might have better luck
> if you try the latest code.
>
> https://influxdb.com/download/index.html#download
>
> Download and install 0.9.5.1.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/influxdb/influxdb/issues/4925#issuecomment-160479154>.
>


-- 
Regards
Sandarsh
650-862-3560

**Comment by schavalmane** [comment] 2015-11-30 01:27
version I have is 0.9.4.2. Before I try upgrade I want to backup data from 500+ servers . How do I do it?. is their a manual way to save this data?

**Comment by gunnaraasen** [comment] 2015-11-30 01:43
To make a back up on 0.9.4.2, stop the InfluxDB process and make a full copy of everything in the `/var/opt/influxdb/` directory, e.g. `tar cvzf backup.tar.gz /var/opt/influxdb/*`. Data will not be destroyed during an upgrade on minor 0.9 versions and there have been no reports of data loss when upgrading from 0.9.4.2 to 0.9.5.1.

Critical bug fixes are only released for current stable versions and no new development happens once a version is announce as stable, so...

- Development is currently in progress for version 0.9.6
- Critical bug fixes will be released for version 0.9.5 (such as 0.9.5.1, the current stable release)
- No more development or bug fixes occur for versions <= 0.9.4.2

The recommendation is to always update to the latest stable release as soon as possible, at least until InfluxDB hits 1.0.

**Comment by beckettsean** [comment] 2015-12-01 00:09
Closing as duplicate of https://github.com/influxdb/influxdb/issues/3700

**Closed by beckettsean** 2015-12-01 00:09 UTC
