### ISSUE TITLE
[0.9.0] Panic if database is not specified on query via API

### ISSUE THREAD

**Issue by fromYukki** [influxdb/influxdb#2957] opened 2015-06-12 13:11 UTC
I opened a influx console tool and forgot to run `USE db_name. Than selected something `select * from response_codes` and everything that I got: 
`ERR: Get http://localhost:8086/query?db=&q=select+%2A+from+response_codes: EOF` and influxdd panics.
Is it ok that every one can kill my influx server this way?

**Comment by otoolep** [comment] 2015-06-12 18:53
Dupe of issue #2932.

**Closed by otoolep** 2015-06-12 18:53 UTC
