### ISSUE TITLE
Add regex filtering for SHOW MEASUREMENTS

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#4351] opened 2015-10-07 06:04 UTC
To help Grafana users make the transition from 0.8 to 0.9, we need to add the ability to filter measurement names based on a regex. Syntax should look like:

```
SHOW MEASUREMENTS WHERE name =~ /.*some regex.*/
```

**Comment by dgnorton** [comment] 2015-10-07 18:02
Would this be better or worse?
```
SHOW MEASUREMENTS FROM /.*some regex.*/
```

**Comment by beckettsean** [comment] 2015-10-07 23:41
closing as duplicate of https://github.com/influxdb/influxdb/issues/3523

**Comment by beckettsean** [comment] 2015-10-07 23:42
And for the record, I prefer Paul's syntax as it matches the other SHOW queries. In them `FROM` refers to the database or the measurement, not the where conditions.

**Closed by beckettsean** 2015-10-07 23:41 UTC

**Comment by dgnorton** [comment] 2015-10-08 01:12
The problem with `WHERE name...` is that `name` can no longer be used as a tag key.

**Comment by beckettsean** [comment] 2015-10-08 05:10
@dgnorton that's a very good point. 

What about `SHOW MEASUREMENTS WHERE MEASUREMENT =~ /.../`?

**Comment by kostya-sh** [comment] 2015-10-08 13:47
How about `SHOW MEASUREMENTS LIKE /.../`?
