### ISSUE TITLE
Authentication on 0.9.0-rc18

### ISSUE THREAD

**Issue by damm** [influxdb/influxdb#2172] opened 2015-04-06 01:27 UTC
Hi,

I configured authentication and using the influx cli I was able to setup a few users; however I don't seem to know how to change the root password? or drop it? 

Thanks!

P.S. I suspect #2158 would help in this but the root user is invisible in show users?

**Comment by n1tr0g** [comment] 2015-04-08 13:02
you will be able to change the root password ,however you are right if you run show users; you are unable to see it. Also I think the current authentication is broken anyway, because whatever credentials you use it will work ;)

**Comment by pauldix** [comment] 2015-04-08 13:28
@damm have you enabled authentication in the config? Without that it doesn't bother with auth even if you've created users.

@n1tr0g there is no longer any root user. The only users that exist are ones you create. By default authentication is turned off and there are no users.

**Comment by n1tr0g** [comment] 2015-04-08 13:33
AHA ok that makes much more sense :) tnx @pauldix

**Comment by beckettsean** [comment] 2015-04-08 19:02
Effectively a dupe of #2193.

**Closed by beckettsean** 2015-04-08 19:02 UTC

**Comment by damm** [comment] 2015-04-08 20:15
@pauldix honestly this issue was more about being unable to change root's password.  This isn't a dupe of #2193 at all (imo)

^^ @beckettsean 

Please re-open the issue

**Comment by beckettsean** [comment] 2015-04-08 20:26
@damm there is no longer a root user at all. Authentication is disabled at install and you must explicitly create all users, including a 'root' user, if you want one.

**Comment by damm** [comment] 2015-04-09 00:13
That's very strange; because I started with authentication off.  Created the users than restarted and I still could login with root/root.  Trying to login unauthenticated gave me errors

Trying to set the password of root was not possible as it was not listed as a `user`.

**Comment by beckettsean** [comment] 2015-04-09 17:25
@damm any chance you could try to repro that situation using RC 20? If possible use curl statements and copy/paste them here so we can also repro.

**Comment by damm** [comment] 2015-04-10 00:33
Let me try and reproduce it (with a fresh dataset) and see with RC20

**Comment by nicholaswyoung** [comment] 2015-05-25 04:54
On RC31, regardless of whether authentication is enabled or not, I'm able to login with root / null. What am I missing? I didn't create a user, and yet, I can still sign in.

**Comment by damm** [comment] 2015-05-25 05:50
@nicholaswyoung not sure how; just tried on RC31 with authentication enabled running show series you should get a 401.

```
> show series
ERR: received status code 401 from server
```

It really does work like they say it does :)

**Comment by n1tr0g** [comment] 2015-05-25 07:55
I think if there are no users even if authentication is enabled you will be granted full access (https://github.com/influxdb/influxdb/blob/master/httpd/handler.go#L896)

**Comment by nicholaswyoung** [comment] 2015-05-25 12:55
@n1tr0g If I had only went to the source, I would've seen that. Thank you. 

I admit, it's a strange behavior in some ways, but totally logical in others.  I'll just be glad when it's documented!

**Comment by damm** [comment] 2015-05-25 20:05
@n1tr0g doesn't appear to the the case in RC31.  I had no users; restarted with authentication and only got a 401.
