### ISSUE TITLE
[0.9.3] Retention policy not found, when it exists

### ISSUE THREAD

**Issue by BGraco** [influxdb/influxdb#3924] opened 2015-09-01 13:19 UTC
SHOW RETENTION POLICIES ON sys_log
Returns:
```
name	duration	replicaN	default
default	"0"	1	false
rp_30d	"720h0m0s"	1	true
```
When I do an insert on the point below
```
{'database': 'sys_log', 'retentionPolicy': 'rp_30d', 'points': [{'fields': {'message': '200 GET /app/dashboard (127.0.0.1) 1441.11ms', 'line': 355}, 'measurement': 'syslog', 'time': 1441112616255, 'tags': {'module_name': 'wsgi', 'level_num': '20', 'file': 'wsgi.py', 'log_name': 'tornado.access'}, 'precision': 'ms'}]}
```
I get: database.influxdb.client.InfluxDBClientError: 500: b'{"error":"retention policy not found"}\n'

I am currently running 4 databases, the other three have no issues, but are using different retention policies. (rp_32d, rp_90d, rp_800d)

Running on v0.9.3, same code worked with v0.9.2.

Debian ARM 32, 512MB RAM
```
### Welcome to the InfluxDB configuration file.

# Once every 24 hours InfluxDB will report anonymous data to m.influxdb.com
# The data includes raft id (random 8 bytes), os, arch, version, and metadata.
# We don't track ip addresses of servers reporting. This is only used
# to track the number of instances running and the versions, which
# is very helpful for us.
# Change this option to true to disable reporting.
reporting-disabled = true

###
### [meta]
###
### Controls the parameters for the Raft consensus group that stores metadata
### about the InfluxDB cluster.
###

[meta]
  dir = "/data/influxdb/meta"
  hostname = "localhost"
  bind-address = ":8087"
  retention-autocreate = true
  election-timeout = "1s"
  heartbeat-timeout = "1s"
  leader-lease-timeout = "500ms"
  commit-timeout = "50ms"

###
### [data]
###
### Controls where the actual shard data for InfluxDB lives and how it is
### flushed from the WAL. "dir" may need to be changed to a suitable place
### for your system, but the WAL settings are an advanced configuration. The
### defaults should work for most systems.
###

[data]
  dir = "/data/influxdb/data"

  # The following WAL settings are for the b1 storage engine used in 0.9.2. They won't
  # apply to any new shards created after upgrading to a version > 0.9.3.
  # max-wal-size = 104857600 # Maximum size the WAL can reach before a flush. Defaults to 100MB.
  # wal-flush-interval = "10m" # Maximum time data can sit in WAL before a flush.
  # wal-partition-flush-delay = "2s" # The delay time between each WAL partition being flushed.

  # These are the WAL settings for the storage engine >= 0.9.3
  wal-dir = "/data/influxdb/wal"
  wal-enable-logging = true

  # When a series in the WAL in-memory cache reaches this size in bytes it is marked as ready to
  # flush to the index
  wal-ready-series-size = 6400

  # Flush and compact a partition once this ratio of series are over the ready size
  wal-compaction-threshold = 0.6

  # Force a flush and compaction if any series in a partition gets above this size in bytes
  wal-max-series-size = 524288

  # Force a flush of all series and full compaction if there have been no writes in this
  # amount of time. This is useful for ensuring that shards that are cold for writes don't
  # keep a bunch of data cached in memory and in the WAL.
  wal-flush-cold-interval = "10m"

  # Force a partition to flush its largest series if it reaches this approximate size in
  # bytes. Remember there are 5 partitions so you'll need at least 5x this amount of memory.
  # The more memory you have, the bigger this can be.
  wal-partition-size-threshold = 5242880

###
### [cluster]
###
### Controls non-Raft cluster behavior, which generally includes how data is
### shared across shards.
###

[cluster]
  shard-writer-timeout = "5s" # The time within which a shard must respond to write.
  write-timeout = "5s" # The time within which a write operation must complete on the cluster.

###
### [retention]
###
### Controls the enforcement of retention policies for evicting old data.
###

[retention]
  enabled = true
  check-interval = "10m"

###
### [admin]
###
### Controls the availability of the built-in, web-based admin interface. If HTTPS is
### enabled for the admin interface, HTTPS must also be enabled on the [http] service.
###

[admin]
  enabled = false
  bind-address = ":8083"
  https-enabled = false
  https-certificate = "/etc/ssl/influxdb.pem"

###
### [http]
###
### Controls how the HTTP endpoints are configured. These are the primary
### mechanism for getting data into and out of InfluxDB.
###

[http]
  enabled = true
  bind-address = ":8086"
  auth-enabled = false
  log-enabled = true
  write-tracing = false
  pprof-enabled = false
  https-enabled = false
  https-certificate = "/etc/ssl/influxdb.pem"

###
### [[graphite]]
###
### Controls one or many listeners for Graphite data.
###

[[graphite]]
  enabled = false
  # bind-address = ":2003"
  # protocol = "tcp"
  # consistency-level = "one"
  # name-separator = "."

  # These next lines control how batching works. You should have this enabled
  # otherwise you could get dropped metrics or poor performance. Batching 
  # will buffer points in memory if you have many coming in.

  # batch-size = 1000 # will flush if this many points get buffered
  # batch-timeout = "1s" # will flush at least this often even if we haven't hit buffer limit

  ## "name-schema" configures tag names for parsing the metric name from graphite protocol;
  ## separated by `name-separator`.
  ## The "measurement" tag is special and the corresponding field will become
  ## the name of the metric.
  ## e.g. "type.host.measurement.device" will parse "server.localhost.cpu.cpu0" as
  ## {
  ##     measurement: "cpu",
  ##     tags: {
  ##         "type": "server",
  ##         "host": "localhost,
  ##         "device": "cpu0"
  ##     }
  ## }
  # name-schema = "type.host.measurement.device"

  ## If set to true, when the input metric name has more fields than `name-schema` specified,
  ## the extra fields will be ignored.
  ## Otherwise an error will be logged and the metric rejected.
  # ignore-unnamed = true

###
### [collectd]
###
### Controls the listener for collectd data.
###

[collectd]
  enabled = false
  # bind-address = ""
  # database = ""
  # typesdb = ""

  # These next lines control how batching works. You should have this enabled
  # otherwise you could get dropped metrics or poor performance. Batching 
  # will buffer points in memory if you have many coming in.

  # batch-size = 1000 # will flush if this many points get buffered
  # batch-timeout = "1s" # will flush at least this often even if we haven't hit buffer limit

###
### [opentsdb]
###
### Controls the listener for OpenTSDB data.
###

[opentsdb]
  enabled = false
  # bind-address = ""
  # database = ""
  # retention-policy = ""

###
### [[udp]]
###
### Controls the listeners for InfluxDB line protocol data via UDP.
###

[[udp]]
  enabled = false
  # bind-address = ""
  # database = ""

  # These next lines control how batching works. You should have this enabled
  # otherwise you could get dropped metrics or poor performance. Batching 
  # will buffer points in memory if you have many coming in.

  # batch-size = 1000 # will flush if this many points get buffered
  # batch-timeout = "1s" # will flush at least this often even if we haven't hit buffer limit

###
### [monitoring]
###

[monitoring]
  enabled = false
  write-interval = "24h"

###
### [continuous_queries]
###
### Controls how continuous queries are run within InfluxDB.
###

[continuous_queries]
  enabled = true
  recompute-previous-n = 2
  recompute-no-older-than = "10m"
  compute-runs-per-interval = 10
  compute-no-more-than = "2m"

###
### [hinted-handoff]
###
### Controls the hinted handoff feature, which allows nodes to temporarily
### store queued data when one node of a cluster is down for a short period
### of time.
###

[hinted-handoff]
  enabled = false
  dir = "/data/influxdb/hh"
  # max-size = 1073741824
  # max-age = "168h"
  # retry-rate-limit = 0
  # retry-interval = "1s"
```

**Comment by beckettsean** [comment] 2015-09-01 18:04
@BGraco if you insert a simplified point does it succeed? If you insert using the line protocol does it succeed?

**Comment by BGraco** [comment] 2015-09-02 20:35
I was able to insert points into the same database and retention policy but with different keys/values/tags.

I can insert the original points using the line protocol.

I suppose moving my project to the line protocol is the best option as that is the direction influx is heading.

**Comment by beckettsean** [comment] 2015-09-02 20:38
@BGraco it does sound like the problem is coming from an interaction between the JSON write and the contents of the strings in that particular point. The JSON write protocol is deprecated and will not be present in 1.0, so moving to the line protocol makes sense.

**Comment by beckettsean** [comment] 2015-09-08 19:02
@BGraco we aren't going to be fixing bugs like this in the JSON write path so now is the time to move to the line protocol. Send us a note at support@influxdb.com if you need assistance with that.

**Closed by beckettsean** 2015-09-08 19:02 UTC
Labels: category/writes
