### ISSUE TITLE
Allow "SHOW STATS" to query other servers

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#1945] opened 2015-03-14 00:27 UTC
Commands such as `SHOW STATS servera` and `SHOW STATS 192.68.1.3` need to be supported. Right now `SHOW STATS` only works with the local node.

**Comment by pauldix** [comment] 2015-03-20 14:32
This is a duplicate of #1470

**Closed by pauldix** 2015-03-20 14:32 UTC
