### ISSUE TITLE
[0.9.2] failed to write point batch to database 

### ISSUE THREAD

**Issue by deric** [influxdb/influxdb#3710] opened 2015-08-18 07:30 UTC
Influxdb crashes after not being able to write a batch.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x5e1305]
```
After several attempts of restart I've managed to start the process.

The issue might be related to #3699, #3603.

I have 2 databases, for the first one the datasource is `collectd`, for the other one it's `graphite`. Both databases have retention policy, though the second one is unlimited:
```
> show retention policies on collectd
name    duration        replicaN        default
default 336h0m0s        1               true

> show retention policies on graphite
name    duration        replicaN        default
default 0               1               true
``` 

part of the log:
```
[collectd] 2015/08/18 06:45:57 failed to write batch: timeout
[collectd] 2015/08/18 06:46:02 failed to write batch: timeout
[collectd] 2015/08/18 06:46:07 failed to write batch: timeout
[run] 2015/08/18 06:46:10 signal received, initializing clean shutdown...
[run] 2015/08/18 06:46:10 waiting for clean shutdown...
[snapshot] 2015/08/18 06:46:10 snapshot listener closed
[tcp] 2015/08/18 06:46:10 cluster service accept error: network connection closed
[collectd] 2015/08/18 06:46:12 failed to write batch: timeout
[metastore] 2015/08/18 06:46:12 [INFO] raft: Node at 127.0.0.1:8088 [Follower] entering Follower state
[metastore] 2015/08/18 06:46:12 read local node id: 1
[metastore] 2015/08/18 06:46:14 [WARN] raft: Heartbeat timeout reached, starting election
[metastore] 2015/08/18 06:46:14 [INFO] raft: Node at 127.0.0.1:8088 [Candidate] entering Candidate state
[metastore] 2015/08/18 06:46:14 [DEBUG] raft: Votes needed: 1
[metastore] 2015/08/18 06:46:14 [DEBUG] raft: Vote granted. Tally: 1
[metastore] 2015/08/18 06:46:14 [INFO] raft: Election won. Tally: 1
[metastore] 2015/08/18 06:46:14 [INFO] raft: Node at 127.0.0.1:8088 [Leader] entering Leader state
[metastore] 2015/08/18 06:46:14 [INFO] raft: Disabling EnableSingleNode (bootstrap)
[metastore] 2015/08/18 06:46:14 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
[metastore] 2015/08/18 06:46:14 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
[metastore] 2015/08/18 06:46:14 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
[metastore] 2015/08/18 06:46:14 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
[metastore] 2015/08/18 06:46:14 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
[metastore] 2015/08/18 06:46:14 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
[metastore] 2015/08/18 06:46:14 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
[metastore] 2015/08/18 06:46:14 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
[metastore] 2015/08/18 06:46:14 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
[metastore] 2015/08/18 06:46:14 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
[metastore] 2015/08/18 06:46:14 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
[metastore] 2015/08/18 06:46:14 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
[metastore] 2015/08/18 06:46:14 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
[metastore] 2015/08/18 06:46:14 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
[graphite] 2015/08/18 06:46:15 failed to write point batch to database "graphite": timeout
[collectd] 2015/08/18 06:46:17 failed to write batch: timeout
[graphite] 2015/08/18 06:46:20 failed to write point batch to database "graphite": timeout
[collectd] 2015/08/18 06:46:22 failed to write batch: timeout
[snapshot] 2015/08/18 06:46:23 snapshot listener closed
[shard-precreation] 2015/08/18 06:46:23 precreation service terminating
[collectd] 2015/08/18 06:46:23 collectd UDP closed
[tcp] 2015/08/18 06:46:23 cluster service accept error: network connection closed
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x5e1305]

goroutine 1 [running]:
github.com/influxdb/influxdb/services/graphite.(*Service).Close(0xc20805a0c0, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/services/graphite/service.go:124 +0x45
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Close(0xc2080aa0e0, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:357 +0x147
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open(0xc2080aa0e0, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:333 +0x85
github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run(0xc208011b90, 0xc20800a010, 0x4, 0x4, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:97 +0x7ab
main.(*Main).Run(0xc20806fa80, 0xc20800a010, 0x4, 0x4, 0x0, 0x0)
        /root/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:76 +0x3bc
main.main()
        /root/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:38 +0xdc

goroutine 6 [syscall]:
os/signal.loop()
        /root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
        /root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /root/.gvm/gos/go1.4.2/src/runtime/asm_amd64.s:2232 +0x1

goroutine 14 [select]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).monitorErrorChan(0xc2080aa0e0, 0xc20802c240)
        /root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:421 +0x14a
created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
        /root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:304 +0x919
[graphite] 2015/08/18 06:46:25 failed to write point batch to database "graphite": timeout
[collectd] 2015/08/18 06:46:27 failed to write batch: timeout
[graphite] 2015/08/18 06:46:30 failed to write point batch to database "graphite": timeout
[collectd] 2015/08/18 06:46:32 failed to write batch: timeout
[graphite] 2015/08/18 06:46:35 failed to write point batch to database "graphite": timeout
[collectd] 2015/08/18 06:46:37 failed to write batch: timeout
[run] 2015/08/18 06:46:40 time limit reached, initializing hard shutdown
[metastore] 2015/08/18 06:56:14 [INFO] raft: Node at 127.0.0.1:8088 [Follower] entering Follower state
[metastore] 2015/08/18 06:56:14 read local node id: 1
[metastore] 2015/08/18 06:56:16 [WARN] raft: Heartbeat timeout reached, starting election
[metastore] 2015/08/18 06:56:16 [INFO] raft: Node at 127.0.0.1:8088 [Candidate] entering Candidate state
[metastore] 2015/08/18 06:56:16 [DEBUG] raft: Votes needed: 1
[metastore] 2015/08/18 06:56:16 [DEBUG] raft: Vote granted. Tally: 1
[metastore] 2015/08/18 06:56:16 [INFO] raft: Election won. Tally: 1
[metastore] 2015/08/18 06:56:16 [INFO] raft: Node at 127.0.0.1:8088 [Leader] entering Leader state
[metastore] 2015/08/18 06:56:16 [INFO] raft: Disabling EnableSingleNode (bootstrap)
```

**Comment by jwilder** [comment] 2015-08-18 15:22
Can you try a nightly build?  This might have been fixed by 089d94

**Comment by deric** [comment] 2015-08-18 19:45
@jwilder I'll try the nightly build. It seems a bit random issue, I'm not sure if I'm able to reproduce similar situation.

**Comment by deric** [comment] 2015-08-20 16:19
Btw. nightly version from (AWS)[wget https://s3.amazonaws.com/influxdb/influxdb_nightly_amd64.deb
] seems to be outdated, it is tagged as `0.9.1-rc1-61-g656fc0d`

**Comment by otoolep** [comment] 2015-08-20 16:22
@deric -- can you show me where you get that tag? Everything looks fine to me.

```
~/n $ wget https://s3.amazonaws.com/influxdb/influxdb_nightly_amd64.deb
--2015-08-20 09:21:39--  https://s3.amazonaws.com/influxdb/influxdb_nightly_amd64.deb
Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.81.107
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.81.107|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7362992 (7.0M) [application/x-debian-package]
Saving to: ‘influxdb_nightly_amd64.deb’

influxdb_nightly_amd64.deb            100%[===========================================================================>]   7.02M   440KB/s   in 16s    

2015-08-20 09:21:55 (436 KB/s) - ‘influxdb_nightly_amd64.deb’ saved [7362992/7362992]

~/n $ ls
influxdb_nightly_amd64.deb
~/n $ ar xv influxdb_nightly_amd64.deb 
x - debian-binary
x - control.tar.gz
x - data.tar.gz
~/n $ tar xvfv data.tar.gz 
drwx------ 0/0               0 2015-08-19 21:00 ./
drwxr-xr-x 0/0               0 2015-08-19 21:00 ./usr/
drwxr-xr-x 0/0               0 2015-08-19 21:00 ./usr/share/
drwxr-xr-x 0/0               0 2015-08-19 21:00 ./usr/share/doc/                                                                                        
drwxr-xr-x 0/0               0 2015-08-19 21:00 ./usr/share/doc/influxdb/                                                                               
-rw-r--r-- 0/0             153 2015-08-19 21:00 ./usr/share/doc/influxdb/changelog.Debian.gz                                                            
drwxr-xr-x 0/0               0 2015-08-19 21:00 ./etc/                                                                                                  
drwxr-xr-x 0/0               0 2015-08-19 21:00 ./etc/opt/                                                                                              
drwxr-xr-x 0/0               0 2015-08-19 21:00 ./etc/opt/influxdb/                                                                                     
-rw-r--r-- 0/0            7146 2015-08-19 21:00 ./etc/opt/influxdb/influxdb.conf                                                                        
drwxr-xr-x 0/0               0 2015-08-19 21:00 ./opt/                                                                                                  
drwxr-xr-x 0/0               0 2015-08-19 21:00 ./opt/influxdb/                                                                                         
drwxr-xr-x 0/0               0 2015-08-19 21:00 ./opt/influxdb/versions/                                                                                
drwxr-xr-x 0/0               0 2015-08-19 21:00 ./opt/influxdb/versions/0.9.3-nightly-4753346/                                                          
-rwxr-xr-x 0/0        10823664 2015-08-19 21:00 ./opt/influxdb/versions/0.9.3-nightly-4753346/influx                                                    
drwxr-xr-x 0/0               0 2015-08-19 21:00 ./opt/influxdb/versions/0.9.3-nightly-4753346/scripts/                                                  
-rwxr-xr-x 0/0            5452 2015-08-19 21:00 ./opt/influxdb/versions/0.9.3-nightly-4753346/scripts/init.sh                                           
-rwxr-xr-x 0/0        16447032 2015-08-19 21:00 ./opt/influxdb/versions/0.9.3-nightly-4753346/influxd                                                   
~/n $ ls                                                                                                                                                
control.tar.gz  data.tar.gz  debian-binary  etc  influxdb_nightly_amd64.deb  opt  usr                                                                   
~/n $ opt/influxdb/versions/0.9.3-nightly-4753346/
influx   influxd  scripts/                                                                                                                              
~/n $ opt/influxdb/versions/0.9.3-nightly-4753346/influxd version
InfluxDB v0.9.3-nightly-4753346 (git: master 47533465a7ce9d590c7e20587f8cdf04236ced00)
~/n $ 
```

**Comment by deric** [comment] 2015-08-20 17:00
oh, sorry, mine fault. wget saved it with extension `.1` and I was looking at older file.

**Comment by beckettsean** [comment] 2015-08-25 21:29
cannot reproduce

**Closed by beckettsean** 2015-08-25 21:29 UTC
Labels: category/plugins, category/writes

**Comment by aheusingfeld** [comment] 2015-09-01 23:39
@deric did you solve your issue? I seem to have exactly the same problem with the 0.9.3 deb package running in the https://registry.hub.docker.com/u/tutum/influxdb/ container having the /data/meta folder mounted onto my case-insensitive OS X filesystem. 

@beckettsean Will try to build an image where it is reproducible

**Comment by deric** [comment] 2015-09-02 07:40
I've upgraded to some nightly release, lost most of my data (that release was behaving really strangely, parts of timeseries were missing). Anyway now I'm running on `0.9.3-rc3` and the same error haven't occurred yet.
