### ISSUE TITLE
CQ unit test needs to be re-enabled

### ISSUE THREAD

**Issue by otoolep** [influxdb/influxdb#1643] opened 2015-02-19 06:14 UTC
At some point we need to look into why this change had to be made:

https://github.com/influxdb/influxdb/pull/1640/files

and fix the underlying issue.

@corylanou @pauldix

**Comment by corylanou** [comment] 2015-02-19 16:08
My bad, I should of logged an issue when I did the PR.  I'll be more diligent moving forward.

**Comment by corylanou** [comment] 2015-04-07 19:41
Duplicate of #1666

**Closed by corylanou** 2015-04-07 19:41 UTC
