### ISSUE TITLE
0.9.0-rc28 Cluster nodes crash with panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by rberger** [influxdb/influxdb#2454] opened 2015-04-29 21:16 UTC
I can't seem to get a 0.9.0 cluster up using Chef (updating the chef cookbook). I suspect I'm not getting the config right. Its not 100% clear what the join-urls should be.

This is how I have it setup:
* the initial node has join-urls = ""
* the other two nodes have it set to the first node: `join-urls = "influxdb-000.example.com"

Here's the experiment:
* Running 0.9.0-rc29
* On AWS t2.medium instances
* Unique FQDN for hostname in each node's config
* Can ping all the "hostname" from each member of the cluster
* Set the influxdb toml configuration to use /data/influxdb/{db,raft}

1. rm -rf /data/influxdb/* on all three nodes
2. start one node: influxdb-000.example.com
    * Its join-url = ""
3. Start the next node influxdb-001.example.com
    *Its join-url = "influxdb-000.example.com"
4. Start the next node influxdb-002.example.com
    *Its join-url = "influxdb-000.example.com"

(full configs and logs at https://gist.github.com/rberger/862a2c26cc2d5a98e66b)

Eventually one of 001 and/or 002 nodes does:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x518a17]

goroutine 160 [running]:
github.com/influxdb/influxdb.(*Stats).Walk(0x0, 0xc208174ce8)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/stats.go:89 +0x137
github.com/influxdb/influxdb.func·010(0x0, 0xc208167c80, 0x0, 0x0, 0x0)
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/server.go:374 +0xc5
github.com/influxdb/influxdb.func·011()
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/server.go:394 +0x3aa
created by github.com/influxdb/influxdb.(*Server).StartSelfMonitoring
        /root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/server.go:412 +0x241
```

On the initial node (000) I see:

```
[messaging] 2015/04/29 20:42:58 connected to broker: http://influxdb-000-staging.mistsys.net:8086/messaging/messages?index=0&streaming=true&topicID=1
[srvr] 2015/04/29 20:48:07 broker cq: error hitting data node: http://influxdb-001-staging.mistsys.net:8086: request returned status 307 Temporary Redirect
[raft] 2015/04/29 20:49:07 leader[1]: leaderLoop: send heartbeat: error: cnt=1 Get http://influxdb-001-staging.mistsys.net:8086/raft/heartbeat?commitIndex=927&leaderID=1&term=1: dial tcp 172.31.50.50:8086: connection refused
[raft] 2015/04/29 20:49:08 leader[1]: append to writers error: write tcp 172.31.50.50:47351: connection reset by peer
[raft] 2015/04/29 20:49:08 leader[1]: writer removed: id=2 idx=0
[srvr] 2015/04/29 20:49:08 broker cq: error hitting data node: http://influxdb-001-staging.mistsys.net:8086: Post http://influxdb-001-staging.mistsys.net:8086/data/process_continuous_queries: dial tcp 172.31.50.50:8086: connection refused
```

Am I doing something wrong?
Thanks!

**Comment by otoolep** [comment] 2015-04-29 22:07
Thanks @rberger -- this is a dupe of issue #2449

**Closed by otoolep** 2015-04-29 22:07 UTC

**Comment by otoolep** [comment] 2015-04-29 22:08
Until RC29 is released, you can work around this issue by disabling monitoring.

**Comment by rberger** [comment] 2015-04-29 23:30
Thanks, setting `'reporting-disabled' = true` fixed things
