### ISSUE TITLE
[0.9.2] Unable to use Influx QL reserved words in Graphite metrics processed with the Graphite plugin

### ISSUE THREAD

**Issue by omer653** [influxdb/influxdb#3787] opened 2015-08-21 14:16 UTC
It looks like we are allowed to use the reserved words in the query language as long as they are double-quoted.

However, when we try to use the reserved words ( i.e .xxx.group.yyy.measurement* ) in one of the Graphite templates to process graphite metrics, the tag is created but the value  is null. 
When I try to query data in the measurement table containing  one of those keywords, I get

{
    "results": [
        {
            "error": "found USER, expected identifier, string, number, bool at line 1, char 214"
        }
    ]
    
}    
{
	"results": [
        {
            "error": "found GROUP, expected identifier, string, number, bool at line 1, char 164"
        }
	]
{

Are you planning to support reserved words in the templates or we should not use them at all ?

Keywords

ALL          ALTER        AS           ASC          BEGIN        BY
CREATE       CONTINUOUS   DATABASE     DATABASES    DEFAULT      DELETE
DESC         DROP         DURATION     END          EXISTS       EXPLAIN
FIELD        FROM         GRANT        GROUP        IF           IN
INNER        INSERT       INTO         KEY          KEYS         LIMIT
SHOW         MEASUREMENT  MEASUREMENTS OFFSET       ON           ORDER
PASSWORD     POLICY       POLICIES     PRIVILEGES   QUERIES      QUERY
READ         REPLICATION  RETENTION    REVOKE       SELECT       SERIES
SLIMIT       SOFFSET      TAG          TO           USER         USERS
VALUES       WHERE        WITH         WRITE

--- Reserved words in InfluxSQL --

Use of any of the InfluxQL Reserved Words as Identifiers or Strings will require quoting of the identifier or string in every use. It can lead to non-intuitive errors and is not recommended.

https://influxdb.com/docs/v0.9/guides/troubleshooting.html
https://github.com/influxdb/influxdb/blob/master/influxql/INFLUXQL.md#keywords

--- Reserved words in InfluxSQL --

**Comment by beckettsean** [comment] 2015-08-21 18:09
@omer653 what version of the database are you running?

**Comment by omer653** [comment] 2015-08-21 20:30
It`s 0.9.2.1 running on OL 6.5/6.3

**Comment by mic-kul** [comment] 2015-08-31 18:08
Same problem with Grafana and nightlies

**Comment by fatmcgav** [comment] 2015-10-20 16:20
Same issue here with Grafana 2.1 and InfluxDB nightly... Any progress?

**Comment by jwilder** [comment] 2015-10-20 16:23
Not sure what the issue is.  Reserved words are not excluded in graphite templates. Can someone provide a template and graphite metric that is causing problems?

**Comment by jwilder** [comment] 2015-10-20 16:24
The issue description looks like reserved words are not quoted in a query.

**Comment by fatmcgav** [comment] 2015-10-20 16:26
@jwilder Does this help: https://gist.github.com/fatmcgav/56eab3b31ce50207ac2a

**Comment by jwilder** [comment] 2015-10-20 16:51
@fatmcgav You have some invalid queries in that Grafana dashboard.

https://gist.github.com/fatmcgav/56eab3b31ce50207ac2a#file-grafana-dashboard-L82

Instead of:
```
SELECT mean(system), mean(iowait), mean(idle), mean(user) FROM \"cpu\" WHERE \"host\" =~ /sensu*/ AND $timeFilter GROUP BY time($interval), \"host\"",
```

You need to quote the reserved words (`user`):

```
SELECT mean(system), mean(iowait), mean(idle), mean("user") FROM \"cpu\" WHERE \"host\" =~ /sensu*/ AND $timeFilter GROUP BY time($interval), \"host\"",
```

You may need to edit the query manually in Grafana if it does not quote the the reserved words automatically.

Closing this since there does not seem to be an issue with the graphite plugin or the query engine.

**Closed by jwilder** 2015-10-20 16:51 UTC
Labels: category/plugins, category/writes

**Comment by fatmcgav** [comment] 2015-10-20 17:22
@jwilder Cheers for the swift response. Will raise a bug on grafana...
