### ISSUE TITLE
USE statement result isn't correct.

### ISSUE THREAD

**Issue by yuokada** [influxdb/influxdb#4886] opened 2015-11-23 20:24 UTC
OS Ver: CentOS6.7
influxdb ver: influxdb-0.9.5-0.1.rc2.x86_64

```
$ influx
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.9.5-rc2
InfluxDB shell 0.9.5-rc2
> show databases
name: databases
---------------
name
_internal
mydb

> use stress
Using database stress
```

I have expect a statement like `Database "stress" not found`.

**Comment by beckettsean** [comment] 2015-11-23 23:44
dupe of https://github.com/influxdb/influxdb/issues/2758

**Closed by beckettsean** 2015-11-23 23:44 UTC
