### ISSUE TITLE
memory leak in 0.8.2

### ISSUE THREAD

**Issue by prune998** [influxdb/influxdb#941] opened 2014-09-16 12:17 UTC
I still have a memory leak in Influxdb 0.8.2

![image](https://cloud.githubusercontent.com/assets/1110398/4286796/416346ac-3d9a-11e4-9df6-525647f32024.png)

Servers are VMWARE hosts, ubuntu 14.04 LTS : 
````Linux poplar 3.13.0-29-generic #53-Ubuntu SMP Wed Jun 4 21:00:20 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux````

It is a two node cluster with dedicated servers (nothing else is running except admin tools like logstash and diamond, not using much CPU or RAM). 
The database have a one day shard with replication = 2 and split = 1

Here is the influxdb process info : 
````
ps auxwww | grep infl
belisar+ 851041 12.5 13.3 1574544 540452 ?      Sl   Sep15 121:19 /opt/data/apps/influxdb/current/influxdb -pidfile /opt/data/apps/influxdb/shared/influxdb.pid -config /opt/data/influxdb/shared/config.toml
````
limits on the process :
````
cat /proc/851041/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        0                    10240000             bytes
Max resident set          unlimited            unlimited            bytes
Max processes             31450                31450                processes
Max open files            64000                64000                files
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       31450                31450                signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us
````
process mapping : 
````
cat /proc/851041/maps                                                                                                                                                                                            [49/1929]
00400000-01000000 r-xp 00000000 00:21 138854                             /opt/data/apps/influxdb/versions/0.8.2/influxdb
01000000-01027000 rw-p 00c00000 00:21 138854                             /opt/data/apps/influxdb/versions/0.8.2/influxdb
01027000-0105d000 rw-p 00000000 00:00 0
013af000-0219c000 rw-p 00000000 00:00 0                                  [heap]
c000000000-c00006e000 rw-p 00000000 00:00 0
c206494000-c2236c0000 rw-p 00000000 00:00 0
7fdf14000000-7fdf14287000 rw-p 00000000 00:00 0
7fdf14287000-7fdf18000000 ---p 00000000 00:00 0
7fdf1c000000-7fdf1ca64000 rw-p 00000000 00:00 0
7fdf1ca64000-7fdf20000000 ---p 00000000 00:00 0
7fdf20000000-7fdf20c50000 rw-p 00000000 00:00 0
7fdf20c50000-7fdf24000000 ---p 00000000 00:00 0
7fdf24000000-7fdf24bac000 rw-p 00000000 00:00 0
7fdf24bac000-7fdf28000000 ---p 00000000 00:00 0
7fdf28000000-7fdf2893d000 rw-p 00000000 00:00 0
7fdf2893d000-7fdf2c000000 ---p 00000000 00:00 0
7fdf2c000000-7fdf2c30f000 rw-p 00000000 00:00 0
7fdf2c30f000-7fdf30000000 ---p 00000000 00:00 0
7fdf30000000-7fdf300bf000 rw-p 00000000 00:00 0
7fdf300bf000-7fdf34000000 ---p 00000000 00:00 0
7fdf34000000-7fdf343ba000 rw-p 00000000 00:00 0
7fdf343ba000-7fdf38000000 ---p 00000000 00:00 0
7fdf39a46000-7fdf39ffc000 rw-p 00000000 00:00 0
7fdf39ffc000-7fdf39ffd000 ---p 00000000 00:00 0
7fdf39ffd000-7fdf3a7fd000 rw-p 00000000 00:00 0                          [stack:851598]
7fdf3a7fd000-7fdf3a7fe000 ---p 00000000 00:00 0
7fdf3a7fe000-7fdf3affe000 rw-p 00000000 00:00 0                          [stack:851412]
7fdf3affe000-7fdf3afff000 ---p 00000000 00:00 0
7fdf3afff000-7fdf3b7ff000 rw-p 00000000 00:00 0
7fdf3b7ff000-7fdf3b800000 ---p 00000000 00:00 0
7fdf3b800000-7fdf3c9ac000 rw-p 00000000 00:00 0                          [stack:851331]
7fdf3c9ac000-7fdf40000000 ---p 00000000 00:00 0
7fdf40000000-7fdf4076c000 rw-p 00000000 00:00 0
7fdf4076c000-7fdf44000000 ---p 00000000 00:00 0
7fdf44000000-7fdf444d4000 rw-p 00000000 00:00 0
7fdf444d4000-7fdf48000000 ---p 00000000 00:00 0
7fdf4801c000-7fdf4823c000 rw-p 00000000 00:00 0
7fdf48277000-7fdf483d8000 rw-p 00000000 00:00 0
7fdf483d8000-7fdf483d9000 ---p 00000000 00:00 0
7fdf483d9000-7fdf48bd9000 rw-p 00000000 00:00 0                          [stack:851330]
7fdf48bd9000-7fdf48bda000 ---p 00000000 00:00 0
7fdf48bda000-7fdf493da000 rw-p 00000000 00:00 0                          [stack:851329]
7fdf493da000-7fdf493db000 ---p 00000000 00:00 0
7fdf493db000-7fdf49bdb000 rw-p 00000000 00:00 0                          [stack:851328]
7fdf49bdb000-7fdf49bdc000 ---p 00000000 00:00 0
7fdf49bdc000-7fdf4a3dc000 rw-p 00000000 00:00 0                          [stack:851048]
7fdf4a3dc000-7fdf4a3dd000 ---p 00000000 00:00 0
7fdf4a3dd000-7fdf4abdd000 rw-p 00000000 00:00 0                          [stack:851047]
7fdf4abdd000-7fdf4abf4000 r-xp 00000000 fc:00 275675                     /lib/x86_64-linux-gnu/libresolv-2.19.so
7fdf4abf4000-7fdf4adf4000 ---p 00017000 fc:00 275675                     /lib/x86_64-linux-gnu/libresolv-2.19.so
7fdf4adf4000-7fdf4adf5000 r--p 00017000 fc:00 275675                     /lib/x86_64-linux-gnu/libresolv-2.19.so
7fdf4adf5000-7fdf4adf6000 rw-p 00018000 fc:00 275675                     /lib/x86_64-linux-gnu/libresolv-2.19.so
7fdf4adf6000-7fdf4adf8000 rw-p 00000000 00:00 0
7fdf4adf8000-7fdf4adfd000 r-xp 00000000 fc:00 275664                     /lib/x86_64-linux-gnu/libnss_dns-2.19.so
7fdf4adfd000-7fdf4affc000 ---p 00005000 fc:00 275664                     /lib/x86_64-linux-gnu/libnss_dns-2.19.so
7fdf4affc000-7fdf4affd000 r--p 00004000 fc:00 275664                     /lib/x86_64-linux-gnu/libnss_dns-2.19.so
7fdf4affd000-7fdf4affe000 rw-p 00005000 fc:00 275664                     /lib/x86_64-linux-gnu/libnss_dns-2.19.so
7fdf4affe000-7fdf4afff000 ---p 00000000 00:00 0
7fdf4afff000-7fdf4b7ff000 rw-p 00000000 00:00 0                          [stack:851046]
7fdf4b7ff000-7fdf4b800000 ---p 00000000 00:00 0
7fdf4b800000-7fdf4c0c8000 rw-p 00000000 00:00 0                          [stack:851045]
7fdf4c0c8000-7fdf50000000 ---p 00000000 00:00 0
7fdf50000000-7fdf50021000 rw-p 00000000 00:00 0
7fdf50021000-7fdf54000000 ---p 00000000 00:00 0
7fdf54000000-7fdf54021000 rw-p 00000000 00:00 0
7fdf54021000-7fdf58000000 ---p 00000000 00:00 0
7fdf58005000-7fdf58025000 rw-p 00000000 00:00 0
7fdf5802c000-7fdf580ec000 rw-p 00000000 00:00 0
7fdf580ec000-7fdf580f7000 r-xp 00000000 fc:00 275661                     /lib/x86_64-linux-gnu/libnss_files-2.19.so
7fdf580f7000-7fdf582f6000 ---p 0000b000 fc:00 275661                     /lib/x86_64-linux-gnu/libnss_files-2.19.so
7fdf582f6000-7fdf582f7000 r--p 0000a000 fc:00 275661                     /lib/x86_64-linux-gnu/libnss_files-2.19.so
7fdf582f7000-7fdf582f8000 rw-p 0000b000 fc:00 275661                     /lib/x86_64-linux-gnu/libnss_files-2.19.so
7fdf582f8000-7fdf58318000 rw-p 00000000 00:00 0                          [stack:851043]
7fdf58318000-7fdf58319000 ---p 00000000 00:00 0
7fdf58319000-7fdf58b19000 rw-p 00000000 00:00 0
7fdf58b19000-7fdf58b1a000 ---p 00000000 00:00 0
7fdf58b1a000-7fdf5941a000 rw-p 00000000 00:00 0
7fdf5941a000-7fdf5941b000 ---p 00000000 00:00 0
7fdf5941b000-7fdf59c1b000 rw-p 00000000 00:00 0                          [stack:851042]
7fdf59c1b000-7fdf59dd7000 r-xp 00000000 fc:00 275659                     /lib/x86_64-linux-gnu/libc-2.19.so
7fdf59dd7000-7fdf59fd6000 ---p 001bc000 fc:00 275659                     /lib/x86_64-linux-gnu/libc-2.19.so
7fdf59fd6000-7fdf59fda000 r--p 001bb000 fc:00 275659                     /lib/x86_64-linux-gnu/libc-2.19.so
7fdf59fda000-7fdf59fdc000 rw-p 001bf000 fc:00 275659                     /lib/x86_64-linux-gnu/libc-2.19.so
7fdf59fdc000-7fdf59fe1000 rw-p 00000000 00:00 0
7fdf59fe1000-7fdf59ff7000 r-xp 00000000 fc:00 259939                     /lib/x86_64-linux-gnu/libgcc_s.so.1
7fdf59ff7000-7fdf5a1f6000 ---p 00016000 fc:00 259939                     /lib/x86_64-linux-gnu/libgcc_s.so.1
7fdf5a1f6000-7fdf5a1f7000 rw-p 00015000 fc:00 259939                     /lib/x86_64-linux-gnu/libgcc_s.so.1
7fdf5a1f7000-7fdf5a210000 r-xp 00000000 fc:00 275676                     /lib/x86_64-linux-gnu/libpthread-2.19.so
7fdf5a210000-7fdf5a40f000 ---p 00019000 fc:00 275676                     /lib/x86_64-linux-gnu/libpthread-2.19.so
7fdf5a40f000-7fdf5a410000 r--p 00018000 fc:00 275676                     /lib/x86_64-linux-gnu/libpthread-2.19.so
7fdf5a410000-7fdf5a411000 rw-p 00019000 fc:00 275676                     /lib/x86_64-linux-gnu/libpthread-2.19.so
7fdf5a411000-7fdf5a415000 rw-p 00000000 00:00 0
7fdf5a415000-7fdf5a424000 r-xp 00000000 fc:00 259980                     /lib/x86_64-linux-gnu/libbz2.so.1.0.4
7fdf5a424000-7fdf5a623000 ---p 0000f000 fc:00 259980                     /lib/x86_64-linux-gnu/libbz2.so.1.0.4
7fdf5a623000-7fdf5a624000 r--p 0000e000 fc:00 259980                     /lib/x86_64-linux-gnu/libbz2.so.1.0.4
7fdf5a624000-7fdf5a625000 rw-p 0000f000 fc:00 259980                     /lib/x86_64-linux-gnu/libbz2.so.1.0.4
7fdf5a625000-7fdf5a63d000 r-xp 00000000 fc:00 259674                     /lib/x86_64-linux-gnu/libz.so.1.2.8
7fdf5a63d000-7fdf5a83c000 ---p 00018000 fc:00 259674                     /lib/x86_64-linux-gnu/libz.so.1.2.8
7fdf5a83c000-7fdf5a83d000 r--p 00017000 fc:00 259674                     /lib/x86_64-linux-gnu/libz.so.1.2.8
7fdf5a83d000-7fdf5a83e000 rw-p 00018000 fc:00 259674                     /lib/x86_64-linux-gnu/libz.so.1.2.8
7fdf5a83e000-7fdf5a943000 r-xp 00000000 fc:00 275662                     /lib/x86_64-linux-gnu/libm-2.19.so
7fdf5a943000-7fdf5ab42000 ---p 00105000 fc:00 275662                     /lib/x86_64-linux-gnu/libm-2.19.so
7fdf5ab42000-7fdf5ab43000 r--p 00104000 fc:00 275662                     /lib/x86_64-linux-gnu/libm-2.19.so
7fdf5ab43000-7fdf5ab44000 rw-p 00105000 fc:00 275662                     /lib/x86_64-linux-gnu/libm-2.19.so
7fdf5ab44000-7fdf5ab4b000 r-xp 00000000 fc:00 275677                     /lib/x86_64-linux-gnu/librt-2.19.so
7fdf5ab4b000-7fdf5ad4a000 ---p 00007000 fc:00 275677                     /lib/x86_64-linux-gnu/librt-2.19.so
7fdf5ad4a000-7fdf5ad4b000 r--p 00006000 fc:00 275677                     /lib/x86_64-linux-gnu/librt-2.19.so
7fdf5ad4b000-7fdf5ad4c000 rw-p 00007000 fc:00 275677                     /lib/x86_64-linux-gnu/librt-2.19.so
7fdf5ad4c000-7fdf5ad6f000 r-xp 00000000 fc:00 275658                     /lib/x86_64-linux-gnu/ld-2.19.so
7fdf5ad8a000-7fdf5af0c000 rw-p 00000000 00:00 0                          [stack:851044]
7fdf5af1c000-7fdf5af62000 rw-p 00000000 00:00 0
7fdf5af63000-7fdf5af6e000 rw-p 00000000 00:00 0
7fdf5af6e000-7fdf5af6f000 r--p 00022000 fc:00 275658                     /lib/x86_64-linux-gnu/ld-2.19.so
7fdf5af6f000-7fdf5af70000 rw-p 00023000 fc:00 275658                     /lib/x86_64-linux-gnu/ld-2.19.so
7fdf5af70000-7fdf5af71000 rw-p 00000000 00:00 0
7fff98598000-7fff985b9000 rw-p 00000000 00:00 0                          [stack]
7fff985f5000-7fff985f7000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]


````
global mem info :
````
cat /proc/meminfo
MemTotal:        4048272 kB
MemFree:          235096 kB
Buffers:           33284 kB
Cached:          2913560 kB
SwapCached:        20944 kB
Active:          2443780 kB
Inactive:        1238768 kB
Active(anon):     384684 kB
Inactive(anon):   351076 kB
Active(file):    2059096 kB
Inactive(file):   887692 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:       1000444 kB
SwapFree:         893720 kB
Dirty:              1132 kB
Writeback:             0 kB
AnonPages:        728136 kB
Mapped:            21720 kB
Shmem:                48 kB
Slab:              70076 kB
SReclaimable:      54644 kB
SUnreclaim:        15432 kB
KernelStack:        1472 kB
PageTables:         6256 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     3024580 kB
Committed_AS:    1127708 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      282128 kB
VmallocChunk:   34359411292 kB
HardwareCorrupted:     0 kB
AnonHugePages:    258048 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       69568 kB
DirectMap2M:     4124672 kB
````

Let me know if I can provide more info... or tell me how to memory dump if this is what you need....

**Comment by imcom** [comment] 2015-01-06 03:18
excuse me @toddboom Just noticed you added this thread to 0.9.0 milestone, does that mean this is not gonna be fixed with 0.8.x releases? I am running 0.8.3 in production because of aggregation functions errors (which fixed in 0.8.8 I assume) but as far as I know you have quite a different approach starting from 0.9.0, so I don't think I will migrate to 0.9.x in near future : ( So what would be the cause or is there any workaround to reduce or free the memory used by influxdb other than restart the instance?

**Comment by imcom** [comment] 2015-01-07 09:43
Hi @toddboom @jvshahid , I can confirm one situation will cause huge memory consumption, leaking. I am using the stressing tool provided by @dgnorton , with 10 writers and 10 readers, write batch is 3000 series per second per writer and there are total 30000 series. Two instances run as a cluster on two ubuntu 12.04 precise servers. LRU for leveldb is 500m and other configs are pretty much the default ones from installation. I noticed the memory only leaks when I have queries like below:

```
var queryTemplates = []string{
  "list series",
  "select * from {{randSeries}} where time > now() - 30m",
  "select {{randAggregate}} from {{randSeries}}",
  "select derivative(value) from {{randSeries}} where time > now() - 5m group by time(1m)",
  "select derivative(value) from {{randSeries}} where time > now() - 15m group by time(5m)",
  "select derivative(value) from {{randSeries}} where time > now() - 30m group by time(10m)",
  "select derivative(value) from /^_minute.writer1*/ where time > now() - 30m group by time(1m)",
}
```
I am inclined that the last query
```
select derivative(value) from /^_minute.writer1*/ where time > now() - 30m group by time(1m)
```
is the trouble maker here, also I have similar queries in my production which will eventually use up all memory on the server.

The query aforementioned involves 3000 series in the db and once the query got executed things start going south... I can see memory usage ever increasing.

In a nut shell, what I've seen is whenever InfluxDB gets stuck in query involves a large number of series will trigger the memory exhaustion. So the idea would be to manually control the query size to avoid memory issue?

Also the split setting in shard config has impacts on following servers I assume.

**Comment by imcom** [comment] 2015-01-07 10:16
Hi @jvshahid , could you post instructions how to build a influxdb binary with profiling enabled? because the version you posted above was compiled against GLIBC_2.17 which I do not have on Ubuntu 12.04. So I will have to build the binary on my own with my environment.
Thanks in advance.

**Comment by toddboom** [comment] 2015-03-14 00:26
Current testing of v0.9.0 shows that this is no longer an issue, so we're closing it out.

**Closed by toddboom** 2015-03-14 00:26 UTC
Labels: 0 - Backlog, bug, datastore, need more info
