### ISSUE TITLE
[0.9.4]upgrade to influxdb 0.9.4 has no http port open

### ISSUE THREAD

**Issue by huhongbo** [influxdb/influxdb#4100] opened 2015-09-15 02:30 UTC
cents 7.1 
influxdb upgrade from 0.9.3
and the systemctl status influxdb show store statistics always say timeout
Sep 15 10:25:36 test influxd[39674]: [monitor] 2015/09/15 10:25:36 failed to store statistics: timeout
Sep 15 10:25:46 test influxd[39674]: [monitor] 2015/09/15 10:25:46 failed to store statistics: timeout
Sep 15 10:25:56 test influxd[39674]: [monitor] 2015/09/15 10:25:56 failed to store statistics: timeout
Sep 15 10:26:06 test influxd[39674]: [monitor] 2015/09/15 10:26:06 failed to store statistics: timeout
I find there is no http 8086 open

**Comment by huhongbo** [comment] 2015-09-15 02:53
fresh install works fine

**Comment by beckettsean** [comment] 2015-09-15 21:25
@mjdesa can you repro the issue with CentOS and 0.9.3 to 0.9.4 upgrade?

**Comment by mjdesa** [comment] 2015-09-15 21:32
@rkuchan

**Comment by rkuchan** [comment] 2015-09-16 00:15
Thanks, @huhongbo. The same thing happens to me. After upgrading to 0.9.4, I get:

```
[root@testingcentos ~]# /opt/influxdb/influx
Connected to http://localhost:8086 version
InfluxDB shell 0.9.4
> show databases
ERR: Get http://localhost:8086/query?db=&q=show+databases: dial tcp [::1]:8086: getsockopt: connection refused
> show series
ERR: Get http://localhost:8086/query?db=&q=show+series: dial tcp [::1]:8086: getsockopt: connection refused
```

**Comment by rkuchan** [comment] 2015-09-16 00:15
@otoolep

**Comment by otoolep** [comment] 2015-09-16 03:21
Can you ping me tomorrow, and I'll take a look at your system.

**Comment by beckettsean** [comment] 2015-09-16 21:11
@otoolep the test server @rkuchan used is on DO: https://cloud.digitalocean.com/droplets/7430710 (45.55.28.147). Let me know if you want help accessing it.

**Comment by otoolep** [comment] 2015-09-17 19:21
```
# service influxdb start
Starting the process influxdb [ OK ]
influxdb process was started [ OK ]
```

and

```
# /opt/influxdb/influx
Connected to http://localhost:8086 version 0.9.4
InfluxDB shell 0.9.4
> show diagnostics
name: system
------------
PID     currentTime                     started                         uptime
17193   2015-09-17T19:21:01.018215613Z  2015-09-17T19:20:26.310881793Z  34.707334606s


name: build
-----------
Branch  Commit                                          Version
0.9.4   d81618c57fae135d9b1c1a8fb3403722ceb29354        0.9.4


name: runtime
-------------
GOARCH  GOMAXPROCS      GOOS    version
amd64   1               linux   go1.5


name: network
-------------
hostname
testingcentos
```

**Comment by otoolep** [comment] 2015-09-17 19:21
Works for me.

**Comment by rkuchan** [comment] 2015-09-17 19:41
Never mind. Works for me as well. Not sure what happened earlier.

@huhongbo, if this is still is still happening please send me the steps to reproduce. Thanks!

**Comment by rossmcdonald** [comment] 2015-09-30 22:19
Closing since we couldn't reproduce the issue. Feel free to re-open if the problem returns though!

**Closed by rossmcdonald** 2015-09-30 22:19 UTC
Labels: category/packages

**Comment by lin-credible** [comment] 2017-03-31 07:35
version:
```
# influx
Connected to http://localhost:8086 version 1.2.0
InfluxDB shell version: 1.2.0
```

```
# influx
Failed to connect to http://localhost:8086: Get http://localhost:8086/ping: dial tcp [::1]:8086: getsockopt: connection refused
Please check your connection settings and ensure 'influxd' is running.
```

**Comment by nkolchakov** [comment] 2018-04-13 08:46
I had to run `influxd.exe` prior to `influx.exe` .
