### ISSUE TITLE
Query should validate that tag keys aren't in select clause on certain aggregates

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#1855] opened 2015-03-05 19:47 UTC
During the query planning phase, we should validate that tag keys are not specified in certain aggregate queries. For instance if they do:

```sql
SELECT mean(value), host
FROM CPU
```

We should return an error and suggest that maybe they meant to put `host` in the group by clause.

However, that is a valid query with the aggregates: `first`, `last`, `min`, `max`.

**Comment by beckettsean** [comment] 2015-09-17 22:42
Fixed in 0.9.4 (actually 0.9.2, I think)

```
> select mean(value), cpu from cpu_idle
ERR: error parsing query: mixing aggregate and non-aggregate queries is not supported
```

Does not behave as intended for selector functions:

```
> select max(value), cpu from cpu_idle
ERR: error parsing query: mixing aggregate and non-aggregate queries is not supported
> select max(value) from cpu_idle
name: cpu_idle
--------------
time			max
1970-01-01T00:00:00Z	3.93996178125e+06

```

Should be mitigated by https://github.com/influxdb/influxdb/issues/1577, which presumably will return all tags for the point, as well.

@corylanou ^^

**Closed by beckettsean** 2015-09-17 22:42 UTC
Labels: RFC
