### ISSUE TITLE
[0.9.5] Query returning values for ORDER BY ASC but not ORDER BY DESC

### ISSUE THREAD

**Issue by jlark** [influxdb/influxdb#5225] opened 2015-12-26 13:42 UTC
I'm running into some problems where the latest data I'm pushing to Influx is not appearing in queries. 
While debugging the issue I'm running the query

`SELECT "value" FROM "battery_voltage"  WHERE time > now() - 6h ORDER BY time ASC`

Which returns values fine. However the query:
`SELECT "value" FROM "battery_voltage"  WHERE time > now() - 6h ORDER BY time DESC`

returns 0 values.

The expected behavior would be to get the values sorted in the opposite order.

**Comment by jlark** [comment] 2015-12-26 14:01
Another interesting result. This query is returning results from 6 days ago

SELECT "value" FROM "pv_production"  ORDER BY time DESC LIMIT 10
2015-12-20T23:59:17Z is the top value

But Bizarly when again I rerun the same query with ORDER BY time ASC without a limit.
If I look down at the values I see data points from this morning!
2015-12-26T08:41:09Z	708.358

Having a hard time understanding what's going on.

**Comment by beckettsean** [comment] 2015-12-28 19:12
@jlark what version of the database?

**Comment by jlark** [comment] 2015-12-29 06:21
I'm sorry should have mentioned it.

v0.9.5 @beckettsean 

Alp

**Comment by beckettsean** [comment] 2015-12-30 00:05
@jlark any chance you are running a cluster?

Do you always get the same result for the `ORDER BY DESC` queries, or do they eventually "catch up" with new data points?

This is a duplicate of https://github.com/influxdb/influxdb/issues/4944, which I found when researching https://github.com/influxdb/influxdb/issues/4235, an issue that was fixed in 0.9.5. 

@corylanou there are now two reports of `ORDER BY DESC` missing values.

**Closed by beckettsean** 2015-12-30 00:05 UTC
Labels: category/queries

**Comment by jlark** [comment] 2015-12-30 06:40
Hi All,
No not running a cluster single instance. Also I'm only pushing around 20 measurements in with 5 minute intervals so it's not a  a lot of data going in.

I just re ran the query

SELECT "value" FROM "pv_production" ORDER BY time DESC LIMIT 10
2015-12-27T23:57:29Z	is the top value

So it's catching up but it's still 3 days behind.

Could this be a low memory issue. I'm running on a small vm and did have influx crash due to an out of memory exception yesterday.

Alp
