### ISSUE TITLE
RC32: Drop measurement has no effect after restart

### ISSUE THREAD

**Issue by srini-raju** [influxdb/influxdb#2822] opened 2015-06-08 16:41 UTC
Steps to replicate:
* Create few measurements.
* Run "select" - Show return data
* Drop measurement
* Run "select" - No Data returned

* Now restart server
* Show measurements shows all the previously dropped measurements
* Run "select" - Shows all the data

Let me know what data i can provide.

**Comment by otoolep** [comment] 2015-06-08 17:44
Is this on a single node? Or a cluster?

**Comment by srini-raju** [comment] 2015-06-08 17:45
Single Node - MacOS

**Comment by otoolep** [comment] 2015-06-08 19:55
I cannot reproduce this. Here are the commands I ran:

```
curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE foo"
curl -G http://localhost:8086/query --data-urlencode "q=CREATE RETENTION POLICY bar ON foo DURATION 1h REPLICATION 1 DEFAULT"

curl -XPOST -H "Content-Type: application/json" 'http://localhost:8086/write' -d '
{
    "database": "foo",
    "retentionPolicy": "bar",
    "points": [
        {
            "measurement": "cpu_load_short",
            "tags": {
                "host": "server01",
                "region": "us-west"
            },
            "time": "2009-11-10T23:00:00Z",
            "fields": {
                "value": 0.64
            }
        }
    ]
}
'

curl -G http://localhost:8086/query?pretty=true --data-urlencode "db=foo" --data-urlencode "q=SELECT value from cpu_load_short"

curl -G http://localhost:8086/query --data-urlencode "db=foo" --data-urlencode 'q=DROP MEASUREMENT cpu_load_short'

curl -G http://localhost:8086/query?pretty=true --data-urlencode "db=foo" --data-urlencode "q=SELECT value from cpu_load_short"
```

Then restart my single node.

```
curl -G http://localhost:8086/query?pretty=true --data-urlencode "db=foo" --data-urlencode "q=SELECT value from cpu_load_short"
{
    "results": [
        {
            "error": "measurement not found: \"foo\"..cpu_load_short"
        }
    ]
}
```

**Comment by otoolep** [comment] 2015-06-08 19:57
Can you please show a sequence similar to above? Otherwise we may have to close this.

**Comment by srini-raju** [comment] 2015-06-08 20:50
@otoolep :
I repeated the steps above exactly like you had but i get see data after restart. See below.

srinis-MacBook-Pro:interfaces raju$ curl -G http://localhost:8086/query?pretty=true --data-urlencode "db=foo" --data-urlencode "q=SELECT value from cpu_load_short"
{
    "results": [
        {
            "error": "measurement not found: \"foo\"..cpu_load_short"
        }
    ]
}srinis-MacBook-Pro:interfaces raju$ curl -G http://localhost:8086/query?pretty=true --data-urlencode "db=foo" --data-urlencode "q=SEECT value from cpu_load_short"
{
    "results": [
        {
            "series": [
                {
                    "name": "cpu_load_short",
                    "columns": [
                        "time",
                        "value"
                    ],
                    "values": [
                        [
                            "2009-11-10T23:00:00Z",
                            0.64
                        ]
                    ]
                }
            ]
        }
    ]
}

**Comment by srini-raju** [comment] 2015-06-08 20:57
@otoolep :
Just a note that it is not happening consistently. Also, i get this error "{"results":[{"error":"bucket not found"}]}" every time i drop a measurement.

If you want you can close this ticket and i will re-open when i can repeatedly reproduce.

Thanks,
Raju

**Comment by otoolep** [comment] 2015-06-09 04:19
Thanks @srini-raju -- can you show me a sequence of `curl` commands showing the "bucket not found" error? I mean the entire sequence -- start with an empty database, and create everything starting with the database.

**Comment by beckettsean** [comment] 2015-06-10 00:21
@srini-raju we'll reopen when you can reproduce, thanks for testing!

**Closed by beckettsean** 2015-06-10 00:21 UTC
