### ISSUE TITLE
Unabled to use some words in a select statement

### ISSUE THREAD

**Issue by jgerschk** [influxdb/influxdb#3707] opened 2015-08-18 03:15 UTC
For example

select * from read ..... fails with the error error parsing query: found READ, expected identifier at line 1, char 15

select * from read_avg works ...

select * from write .... fails with error parsing query: found WRITE, expected identifier at line 1, char 15

read and right are valid entries when doing show measurements and further, they are performance counters for some items.

Why do those two, and I am sure others will fail, just not found them -- is this a known issue, bug?

**Comment by otoolep** [comment] 2015-08-18 03:45
They are probably colliding with the READ and WRITE privilege tokens. Try
quoting them.

**Comment by jgerschk** [comment] 2015-08-18 03:54
@otoolep I've tried everything I can think of

select * from /read/
select * from 'read'
select * from "read"

I mean I would have expected /read/ to work, as it works for /read_avg/.  Any other "quoting" suggestions than the above?

**Comment by otoolep** [comment] 2015-08-18 03:58
Try fully qualifying it i.e. <database>.<retention policy >.read

**Comment by jgerschk** [comment] 2015-08-18 04:07
@otoolep Just gave that a try produces the same result.

select * from checkmk.month.read

error parsing query: found READ, expected identifier at line 1, char 29

I think it is fair to say that read/write within the from statement don't work, which seems like a bug to me at this point.

**Comment by DanielMorsing** [comment] 2015-08-18 18:52
Looks like this was fixed by #3560. I can't reproduce on master with the following shell script
```
> create database foo
> use foo
Using database foo
> insert read value=30
> select * from "read"
name: read
----------
time				value
2015-08-18T18:48:26.055963007Z	30

> 
```

Try the nightly builds. I should be fixed in there.

**Comment by beckettsean** [comment] 2015-08-18 19:14
Confirmed fixed in latest nightly:

```
root@sean-test:~# /opt/influxdb/influx
Connected to http://localhost:8086 version 0.9.3-nightly-1548f62
InfluxDB shell 0.9.3-nightly-1548f62
> use foo
Using database foo
> insert read value=30
> select * from read
ERR: error parsing query: found READ, expected identifier at line 1, char 15
> select * from "read"
name: read
----------
time				value
2015-08-18T19:13:46.641839765Z	30
```

**Closed by beckettsean** 2015-08-18 19:14 UTC

**Comment by jgerschk** [comment] 2015-08-18 19:20
@DanielMorsing , @beckettsean   I do agree, using the latest night corrected the issue on my end as well.

Thank you everyone.
