### ISSUE TITLE
Crash with "panic: interface conversion: interface is string, not float64"

### ISSUE THREAD

**Issue by cmorse** [influxdb/influxdb#2543] opened 2015-05-11 23:42 UTC
When I run the following query from Grafana on InfluxDB 0.9.0-rc29, I get a crash with "panic: interface conversion: interface is string, not float64"

    SELECT mean(value) FROM "Zmq(Input1)Msgs" WHERE $timeFilter AND name='Zmq Bridge' GROUP BY time($interval) ORDER BY ASC;

The query URL that causes the crash is: `http://localhost:8086/query?db=stats_db&p=test_user&q=SELECT+mean(value)+FROM+"Zmq(Input1)Msgs"+WHERE+time+>+now()+-+6h+AND+name='Zmq+Bridge'+GROUP+BY+time(30m)+ORDER+BY+asc&u=test_user`

This is on 64-bit Centos 7.0.1406 and was installed from the pre-built rpm.

I have posted a copy of the stacktrace from the crash here: http://pastebin.com/eNTPXFR0

**Comment by toddboom** [comment] 2015-05-11 23:51
@cmorse it looks like you might be trying to take the mean of a column that has string data - is that possible?

**Comment by beckettsean** [comment] 2015-05-11 23:52
@cmorse Does the query work if entered directly into the admin UI or when issued as a curl command from the command line? 

If it does work, can you please provide a subset of your data?

If it gives the same panic even without grafana involved chances are very good your data is stored as strings, not numbers.

**Comment by beckettsean** [comment] 2015-05-11 23:53
Possible dupe of #2299

**Comment by cmorse** [comment] 2015-05-12 00:07
@toddboom Now that I think about it, I am trying to take the mean of a column that has string data. I didn't realize that it differentiated on that.

**Comment by beckettsean** [comment] 2015-05-12 00:12
Thanks, @cmorse, closing this as a dupe. Do you have any suggestions as to how we can improve the error message (other than it shouldn't actually panic the db)?

**Closed by beckettsean** 2015-05-12 00:12 UTC

**Comment by cmorse** [comment] 2015-05-12 00:15
Something like "Cannot take mean of column with string data" would be helpful.

**Comment by beckettsean** [comment] 2015-05-12 00:21
The error is bubbling up from a lower level than the specific aggregation, so ideally it would be generic to all aggregations. Perhaps something like "Cannot perform aggregation on string data"

**Comment by cmorse** [comment] 2015-05-12 15:57
"Cannot perform aggregation on string data" sounds good to me as well. It would be nice to have some documentation about how InfluxDB stores the records. From going over the introduction and the first page of the API section, it wasn't clear that the db stores the data with static types. I was under the impression that it was some sort of dynamic typing behind the scenes.

**Comment by beckettsean** [comment] 2015-05-12 18:03
The first point written to a series determines the data types for that series. All subsequently written points must match the data type. I've made a note to be more explicit about this in the docs, which are still woefully sparse but we're improving them daily.

**Comment by cmorse** [comment] 2015-05-12 19:03
Ohhhh. Yeah, a note like that would be helpful. Documentation is one of the hardest things to do for a project.
