### ISSUE TITLE
[0.9.0-rc30] creating an already existing database returns status code 200

### ISSUE THREAD

**Issue by georgijd** [influxdb/influxdb#2621] opened 2015-05-20 18:40 UTC
Hi guys,

I recently switched to the newest version of InfluxDB (v0.9.0-rc30) and noticed that when I try to create a database that is already existing, the response code is 200, which feels wrong.

My system details:
```
OS:
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.04
Release:	15.04
Codename:	vivid

Kernel:
Linux georgijd 3.19.0-16-generic #16-Ubuntu SMP Thu Apr 30 16:09:58 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

InfluxDB version:
[srvr] 2015/05/20 19:20:07 influxdb started, version 0.9.0-rc30, commit acf2dd6ba5429e95ad6a156afe7afbdc6b861979
```

Steps to reproduce:
```
# create database
curl -G 'http://localhost:8086/query' --data-urlencode "q=CREATE DATABASE mydb"
# create the same database again
curl -G 'http://localhost:8086/query' --data-urlencode "q=CREATE DATABASE mydb" --verbose
```
Result of the second command:
```
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8086 (#0)
> GET /query?q=CREATE%20DATABASE%20mydb HTTP/1.1
> User-Agent: curl/7.38.0
> Host: localhost:8086
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< Request-Id: d7349ef5-ff1e-11e4-835d-000000000000
< X-Influxdb-Version: 0.9.0-rc30
< Date: Wed, 20 May 2015 18:34:25 GMT
< Content-Length: 41
< 
* Connection #0 to host localhost left intact
{"results":[{"error":"database exists"}]}
```
Shouldn't the response code be in the 400 range? 

Regards,
Georgi

**Comment by beckettsean** [comment] 2015-05-20 18:54
closing as duplicate of #2560

**Closed by beckettsean** 2015-05-20 18:54 UTC
