### ISSUE TITLE
Does wildcard really works in influxdb 0.9.0-rc30

### ISSUE THREAD

**Issue by lokeshverizon** [influxdb/influxdb#2777] opened 2015-06-04 21:54 UTC
Hi I am trying to use wildcard and having empty reply. If I don't use wild card, I can see the data hence I wanted to filter it out. Does any one has any idea to use correct syntax. 
I spent lot of time, to use it but no success. 

following works:
`curl -G http://localhost:8086/query --data-urlencode 'db=logging'  --data-urlencode "q=select * from  HOSTOS_logs   limit 10 "`

However following does not work:
`curl -G http://localhost:8086/query --data-urlencode 'db=logging'  --data-urlencode "q=select * from  HOSTOS_logs where msg =~ /INFO.*/  limit 10  "`

`curl -G http://localhost:8086/query --data-urlencode 'db=logging'  --data-urlencode "q=select * from  HOSTOS_logs where msg =~ /.*INFO.*/  limit 10  "`

output from 1)
```
{"results":[{"series":[{"name":"HOSTOS_logs","columns":["time","msg"],"values":[["2015-06-04T17:06:24Z","INFO|node-c4346bc00cc8|10.1.125.1|HOSTOS|17116|docker||1433437584255977|ERROR|df84d8b85858|1|||logconsumer|main.go:97|2015/06/04 17:06:24|Unable to Receive Message:kafka server: The requested offset is outside the range of offsets maintained by the server for the given topic/partition.\n"],["2015-06-04T17:06:27Z","INFO|node-c4346bc00cc8|10.1.125.1|HOSTOS|58586|fleetd||1433437586103462|INFO reconcile.go:267: AgentReconciler task chain failed: chain={marathon-haproxy-bridge.service (StartUnit, \"unit currently loaded but desired state is launched\")} err=task already in flight\n"],["2015-06-04T17:06:27Z","INFO|node-c4346bc13018|10.1.132.1|HOSTOS|956|fleetd||1433437586204714|INFO reconcile.go:267: AgentReconciler task chain failed: chain={logrotate.service (StartUnit, \"unit currently loaded but desired state is launched\")} err=task already in flight\n"],["2015-06-04T17:06:27Z","INFO|node-c4346bc13018|10.1.132.1|HOSTOS|1295|docker||1433437586296355|App:btheado-socat-serviceclient Port:20008 not in valid port range of 10000-20000. Not adding to the haproxy.cfg\n"],["2015-06-04T17:06:28Z","INFO|node-c4346bc00cc8|10.1.125.1|HOSTOS|17116|docker||1433437586513480|ERROR|df84d8b85858|1|||logconsumer|main.go:97|2015/06/04 17:06:26|Unable to Receive Message:kafka server: The requested offset is outside the range of offsets maintained by the server for the given topic/partition.\n"],["2015-06-04T17:06:29Z","INFO|node-c4346bc00cc8|10.1.125.1|HOSTOS|17116|docker||1433437588271316|ERROR|df84d8b85858|1|||logconsumer|main.go:97|2015/06/04 17:06:28|Unable to Receive Message:kafka server: The requested offset is outside the range of offsets maintained by the server for the given topic/partition.\n"],["2015-06-04T17:06:29Z","INFO|node-c4346bc13018|10.1.132.1|HOSTOS|1295|docker||1433437588344212|Port Collision detected for thingspace_product_kafka-20003 with [20003]\n"],["2015-06-04T17:06:30Z","INFO|node-c4346bc00cc8|10.1.125.1|HOSTOS|17116|docker||1433437589246122|ERROR|df84d8b85858|1|||logconsumer|main.go:97|2015/06/04 17:06:29|Unable to Receive Message:kafka server: The requested offset is outside the range of offsets maintained by the server for the given topic/partition.\n"],["2015-06-04T17:06:30Z","INFO|node-c4346bc13018|10.1.132.1|HOSTOS|1295|docker||1433437590008190|Port Collision detected for vrr_ssd-poc_node2-10000 with [10000]\n"],["2015-06-04T17:06:31Z","INFO|node-c4346bc00cc8|10.1.125.1|HOSTOS|17116|docker||1433437590502149|ERROR|df84d8b85858|1|||logconsumer|main.go:97|2015/06/04 17:06:30|Unable to Receive Message:kafka server: The requested offset is outside the range of offsets maintained by the server for the given topic/partition.\n"]]}]}]}
```

If I add, where clause with regex, I don't get anything
```
curl -G http://localhost:8086/query --data-urlencode 'db=logging'  --data-urlencode "q=select * from  HOSTOS_logs where msg =~ /.*INFO.*/  limit 10  "

{"results":[{"series":[{"name":"HOSTOS_logs","columns":["time","msg"]}]}]}
```

```
curl -G http://localhost:8086/query --data-urlencode 'db=logging'  --data-urlencode "q=select * from  HOSTOS_logs where msg =~ /INFO.*/  limit 10  "
{"results":[{"series":[{"name":"HOSTOS_logs","columns":["time","msg"]}]}]}
```

**Comment by beckettsean** [comment] 2015-06-05 21:23
this is a duplicate of #2593, regex cannot be applied to fields, only tags.

**Closed by beckettsean** 2015-06-05 21:23 UTC
