### ISSUE TITLE
[0.9.5.1] panic after querying: select field_a / field_b from db

### ISSUE THREAD

**Issue by mail2fish** [influxdb/influxdb#4985] opened 2015-12-04 08:48 UTC
[query] 2015/12/04 08:45:12 SELECT total / count FROM "test_master"."default".Requests WHERE time > (now() - 26h) AND time < (now() - 1d) 
panic: runtime error: index out of range

goroutine 162 [running]:
github.com/influxdb/influxdb/influxql.func·005(0xc209348740, 0x2, 0x2, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/influxql/result.go:98 +0x4a
github.com/influxdb/influxdb/influxql.func·010(0xc209348740, 0x2, 0x2, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/influxql/result.go:147 +0xa8
github.com/influxdb/influxdb/tsdb.processForMath(0xc208030ad8, 0x1, 0x1, 0xc209aaac00, 0x25, 0x40, 0x0, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/tsdb/raw.go:652 +0x4ad
github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).processValues(0xc209153680, 0xc208d32000, 0x25, 0x2710, 0x0)
	/root/go/src/github.com/influxdb/influxdb/tsdb/raw.go:536 +0xf45
github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).Flush(0xc209153680)
	/root/go/src/github.com/influxdb/influxdb/tsdb/raw.go:437 +0xd6
github.com/influxdb/influxdb/tsdb.(*RawExecutor).execute(0xc209b6b290, 0xc209552360)
	/root/go/src/github.com/influxdb/influxdb/tsdb/raw.go:143 +0x4e2
created by github.com/influxdb/influxdb/tsdb.(*RawExecutor).Execute
	/root/go/src/github.com/influxdb/influxdb/tsdb/raw.go:59 +0x5a

**Comment by otoolep** [comment] 2015-12-04 14:06
Dupe of https://github.com/influxdb/influxdb/issues/4046

**Closed by otoolep** 2015-12-04 14:06 UTC
