### ISSUE TITLE
[0.9] cannot drop series with tag in where clause on cluster

### ISSUE THREAD

**Issue by ziyel** [influxdb/influxdb#2982] opened 2015-06-15 04:06 UTC
Reproduce issue with below statements.

    curl -G "http://host:port/query" --data-urlencode "q=create database test"
    curl -G "http://host:port/query" --data-urlencode 'q=CREATE RETENTION POLICY  myrp ON "test" DURATION 30d REPLICATION 3 DEFAULT'
    curl -i -XPOST "http://host:port/write?db=test" -d 'cpu.idle,host=op-host.net value=99.00 1434055562000000000'
    curl -G "http://host:port/query" --data-urlencode "q=drop series from \"cpu.idle\" where host='op-host.net'" --data-urlencode "db=test"

The error message is below:

    {"results":[{"error":"database not open"}]}%

**Comment by beckettsean** [comment] 2015-06-15 18:49
Very strange bug. I can repro in the CLI:

```
> create database drop_series
> use drop_series
Using database drop_series
> insert cpu.idle,host=op-host.net value=99.00 1434055562000000000
> insert cpu.idle,host=op-host.net1 value=99.00 1434055562000000000
> insert cpu.idle,host=opet1 value=99.00 1434055562000000000
> insert cpu.idle,host=foo value=99.00 1434055562000000000
> select * from "cpu.idle"
name: cpu.idle
tags: host=foo
time			value
----			-----
2015-06-11T20:46:02Z	99

name: cpu.idle
tags: host=op-host.net
time			value
----			-----
2015-06-11T20:46:02Z	99

name: cpu.idle
tags: host=op-host.net1
time			value
----			-----
2015-06-11T20:46:02Z	99

name: cpu.idle
tags: host=opet1
time			value
----			-----
2015-06-11T20:46:02Z	99

> drop series from "cpu.idle" where host='foo'
ERR: database not open
> drop series from "cpu.idle" where host=foo
ERR: database not open
> use drop_series
Using database drop_series
> drop series from "cpu.idle" where host=foo
ERR: database not open
> drop series from "cpu.idle" where host='foo'
ERR: bucket not found
> show series
name: cpu.idle
--------------
_key				host
cpu.idle,host=op-host.net	op-host.net
cpu.idle,host=op-host.net1	op-host.net1
cpu.idle,host=opet1		opet1
cpu.idle,host=foo		foo
```

**Comment by ziyel** [comment] 2015-06-16 07:48
@beckettsean , yes, we are testing in a 3-node cluster.

**Comment by otoolep** [comment] 2015-06-17 16:43
https://github.com/influxdb/influxdb/blob/master/tsdb/query_executor.go#L154

This statement is not yet support on clusters. It will be supported when https://github.com/influxdb/influxdb/issues/3009 is fixed.

**Comment by jwilder** [comment] 2015-08-13 17:55
Can't reproduce this in single node 0.9.3 master.

**Comment by beckettsean** [comment] 2015-08-18 23:19
Verified fixed in single-node with 0.9.3 nightly:

```
> create database drop_series
> use drop_series
Using database drop_series
> insert cpu.idle,host=op-host.net value=99.00 1434055562000000000
> insert cpu.idle,host=op-host.net1 value=99.00 1434055562000000000
> insert cpu.idle,host=opet1 value=99.00 1434055562000000000
> insert cpu.idle,host=foo value=99.00 1434055562000000000
> select * from "cpu.idle"
name: cpu.idle
tags: host=foo
time			value
----			-----
2015-06-11T20:46:02Z	99


name: cpu.idle
tags: host=op-host.net
time			value
----			-----
2015-06-11T20:46:02Z	99


name: cpu.idle
tags: host=op-host.net1
time			value
----			-----
2015-06-11T20:46:02Z	99


name: cpu.idle
tags: host=opet1
time			value
----			-----
2015-06-11T20:46:02Z	99

> drop series from "cpu.idle" where host='foo'
> drop series from "cpu.idle" where host='foo'
> select * from "cpu.idle"
name: cpu.idle
tags: host=op-host.net
time			value
----			-----
2015-06-11T20:46:02Z	99


name: cpu.idle
tags: host=op-host.net1
time			value
----			-----
2015-06-11T20:46:02Z	99


name: cpu.idle
tags: host=opet1
time			value
----			-----
2015-06-11T20:46:02Z	99

> 
```

**Comment by beckettsean** [comment] 2015-08-18 23:19
@mjdesa can you please try to repro in a cluster? Might be a cluster-only bug at this point.

**Comment by mjdesa** [comment] 2015-08-18 23:46
@beckettsean cant repro in a cluster.

**Comment by mjdesa** [comment] 2015-08-18 23:47
Everything was all good

```
~$ curl -G "http://54.176.125.158:8086/query"
{"error":"missing required parameter \"q\""}
~$
~$ curl -G "http://54.176.125.158:8086/query" --data-urlencode "q=create database test"
{"results":[{}]}
~$
~$ curl -G "http://54.176.125.158:8086/query" --data-urlencode 'q=CREATE RETENTION POLICY  myrp ON "test" DURATION 30d REPLICATION 3 DEFAULT'
{"results":[{}]}
~$
~$ curl -i -XPOST "http://54.176.125.158:8086/write?db=test" -d 'cpu.idle,host=op-host.net value=99.00 1434055562000000000'
HTTP/1.1 204 No Content
Request-Id: 2d93f597-4603-11e5-8007-000000000000
X-Influxdb-Version: 0.9.3-nightly-8de66eb
Date: Tue, 18 Aug 2015 23:45:16 GMT

~$ curl -G "http://54.176.125.158:8086/query" --data-urlencode "q=drop series from \"cpu.idle\" where host='op-host.net'" --data-urlencode "db=test"
{"results":[{}]}
~$
```

**Comment by beckettsean** [comment] 2015-08-19 00:56
cannot repro in 0.9.3 nightly, closing

**Comment by beckettsean** [comment] 2015-08-19 00:57
@mjdesa can you verify the point was actually dropped?

**Closed by beckettsean** 2015-08-19 00:56 UTC
Labels: category/clustering, category/queries

**Comment by mjdesa** [comment] 2015-08-19 18:00
@beckettsean yeah it actually gets dropped.
