### ISSUE TITLE
first() and last() return wrong time with the value

### ISSUE THREAD

**Issue by prashleo** [influxdb/influxdb#4294] opened 2015-10-01 21:04 UTC
I have time series named 'sla' with only 2 time ranges.
below query, returns 2 value for each group by:

`select  value from sla where machine='120' and parent='machine'  group by resource_type`
```
sla
resource_type:disk

time	value
2015-10-01T20:35:33Z	0
2015-10-01T20:42:28Z	0
sla
resource_type:nic

time	value
2015-10-01T20:35:33Z	0
2015-10-01T20:42:28Z	0
```

which is exactly what I expected.

But using last() which should  return me 1 value in each group, which indeed it does 
but with the  wrong time '1970-01-01T00:00:00Z'  instead of  '2015-10-01T20:42:28Z' 

`select  last(value) from sla where machine='120' and parent='machine' group by resource_type

```
sla
resource_type:disk

time	last
1970-01-01T00:00:00Z	0
sla
resource_type:nic

time	last
1970-01-01T00:00:00Z	0
```

Thanks,
Prashanth

**Comment by beckettsean** [comment] 2015-10-01 21:22
duplicate of https://github.com/influxdb/influxdb/issues/1577

**Closed by beckettsean** 2015-10-01 21:22 UTC
