### ISSUE TITLE
the problem of cli

### ISSUE THREAD

**Issue by kcrosswind** [influxdb/influxdb#3342] opened 2015-07-16 02:00 UTC
os: centos 5.5 
use 9.0.1 rpm to install
/opt/influxdb.influx in cli
i can do `use mydb` and  `select * from cpu` it is right.
but use `select * from cpu` immediately, and not use database. return `ERR: Get http://localhost:8086/query?db=&q=select+%2A+from+cpu: EOF` . and the server will shut down . i think it is too week.

**Comment by beckettsean** [comment] 2015-07-16 17:54
Duplicate of #3112 which was closed. If you can reproduce this with 0.9.1 please show the direct CLI output.

**Closed by beckettsean** 2015-07-16 17:54 UTC

**Comment by beckettsean** [comment] 2015-07-16 18:05
Fresh Ubuntu box with brand new InfluxDB install doesn't panic when selecting a non-existent measurement, whether or not a non-existent database is already selected, or even if the database does exist:

```
root@sean3:~# sudo dpkg -i influxdb_0.9.1_amd64.deb
Selecting previously unselected package influxdb.
(Reading database ... 86964 files and directories currently installed.)
Preparing to unpack influxdb_0.9.1_amd64.deb ...
Unpacking influxdb (0.9.1) ...
Setting up influxdb (0.9.1) ...
 Removing any system startup links for /etc/init.d/influxdb ...
 Adding system startup for /etc/init.d/influxdb ...
   /etc/rc0.d/K20influxdb -> ../init.d/influxdb
   /etc/rc1.d/K20influxdb -> ../init.d/influxdb
   /etc/rc6.d/K20influxdb -> ../init.d/influxdb
   /etc/rc2.d/S20influxdb -> ../init.d/influxdb
   /etc/rc3.d/S20influxdb -> ../init.d/influxdb
   /etc/rc4.d/S20influxdb -> ../init.d/influxdb
   /etc/rc5.d/S20influxdb -> ../init.d/influxdb
root@sean3:~# /etc/init.d/influxdb start
Starting the process influxd [ OK ]
influxd process was started [ OK ]
root@sean3:~# /opt/influxdb/influx
Connected to http://localhost:8086 version 0.9.1
InfluxDB shell 0.9.1
> select * from foo
ERR: database name required
Warning: It is possible this error is due to not setting a database.
Please set a database with the command "use <database>".
> use mydb
Using database mydb
> select * from foo
ERR: database not found: mydb
> create database mydb
> select * from foo
ERR: measurement not found: "mydb"..foo
> 

```

**Comment by kcrosswind** [comment] 2015-07-17 11:26
···
Linux version 2.6.32-220.23.2.ali927.el5.x86_64 (ads@localhost.localdomain) (gcc version 4.1.2 20080704 (Red Hat 4.1.2-50)) #1 SMP Mon Jan 28 14:57:06 CST 2013

/opt/influxdb/influx
Connected to http://localhost:8086 version FIXME
InfluxDB shell 0.9.0
> select * from mydb
ERR: Get http://localhost:8086/query?db=&q=select+%2A+from+mydb: EOF
> select * from mydb
ERR: Get http://localhost:8086/query?db=&q=select+%2A+from+mydb: dial tcp 127.0.0.1:8086: connection refused
···

**Comment by beckettsean** [comment] 2015-07-17 18:20
@kcrosswind You are running an older version. Please upgrade to 0.9.1 or newer. This is a known bug that has been fixed.
