### ISSUE TITLE
unexpected derivative behavior

### ISSUE THREAD

**Issue by rjjanuary** [influxdb/influxdb#4931] opened 2015-11-30 21:07 UTC
Below is an example of an issue I'm running into using the latest 0.9.5 release, after upgrading from 0.9.3.

The first two queries work as anticipated, the third I would expect to return a derivative value, however appears to be producing blank results. 

The first two illustrate that the involved functions and predicates work correctly. The third is a derived example against the _internal database which I would expect to produce a result.

```
> use _internal
Using database _internal
> select non_negative_derivative(Mallocs) from runtime where time > now() - 2h group by hostname
name: runtime
tags: hostname=nic-vtxprd-oradb04
time			non_negative_derivative
----			-----------------------
1448904492000000000	2162.9
1448904502000000000	100173.9
1448904512000000000	1105.1
1448904522000000000	2800.7
1448904532000000000	100077.8
1448904542000000000	2160.5
1448904552000000000	2169.1
1448904562000000000	99258.8
...

> select max(Mallocs) from runtime where time > now() - 2h group by hostname, time(5m);
name: runtime
tags: hostname=nic-vtxprd-oradb04
time			max
----			---
1448907600000000000	101040082
1448907900000000000	101657647
1448908200000000000	102948985
1448908500000000000	103561243
1448908800000000000	104161009
1448909100000000000	104777980
...


> select non_negative_derivative(max(Mallocs)) from runtime where time > now() - 2h group by hostname, time(5m)
name: runtime
tags: hostname=nic-vtxprd-oradb04
time			non_negative_derivative
----			-----------------------
1448907900000000000	
1448908200000000000	
1448908500000000000	
1448908800000000000	
1448909100000000000	
1448909400000000000	
1448909700000000000	
```

**Comment by otoolep** [comment] 2015-11-30 21:11
This appears to be a dupe of https://github.com/influxdb/influxdb/issues/4849

**Closed by otoolep** 2015-11-30 21:11 UTC

**Comment by rjjanuary** [comment] 2015-11-30 21:12
Excellent.  I apologize I missed it.  Thank you.
