### ISSUE TITLE
Derivative problem

### ISSUE THREAD

**Issue by allertec** [influxdb/influxdb#1314] opened 2015-01-12 17:10 UTC
Hello,

I`m trying to run following query against my database:
select derivative("server01.value" + "server02.value") from "server01" INNER JOIN "server02" group by time(1m)

However I don`t get any output, graph, message etc. Literally nothing. Is this a bug, or wrong query?
If this is a bug, then is there any work around?

My InfluxDB version is 0.8.6. 

Thank you

**Comment by davidblewett** [comment] 2015-01-27 17:55
Possible duplicate of #438.

**Comment by damm** [comment] 2015-02-01 03:41
@allertec try adding `fill(0)` to your query.

I find without `fill(0)` or `fill(null)` there is nothing returned.

**Closed** 2015-04-15 23:51 UTC
