### ISSUE TITLE
DERIVATIVE is broken in 0.9.4.1 (Stable)

### ISSUE THREAD

**Issue by imcom** [influxdb/influxdb#4207] opened 2015-09-23 02:49 UTC
I understand that it is nice to have DERIVATIVE support aggregation functions, but you guys just made it only work with aggregation functions. It is not viable to use field_keys in DERIVATIVE in this version. Please fix it ASAP. I do not know how many serious users/customers you've got. BUT, do NOT break usable functions any more!

**Comment by imcom** [comment] 2015-09-23 02:54
Nice dudes, the nightly build fixed it. Be careful please and when do you plan to cut a release on the nightly build ?

**Comment by imcom** [comment] 2015-09-23 02:57
Oh, that's strange, why should I always use an aggregation function when I have `time` condition in WHERE clause??? 

```
select derivative(rxbytes) from l3stats_total where idc='kafka-l3stats-us' and time >= '02:00:00'
```

gives me the error

Server returned error: error parsing query: aggregate function required inside the call to derivative

**Comment by HakShak** [comment] 2015-09-23 14:55
See https://github.com/grafana/grafana/issues/2802

**Comment by beckettsean** [comment] 2015-09-25 20:04
closing as dupe of https://github.com/influxdb/influxdb/issues/4187

**Closed by beckettsean** 2015-09-25 20:04 UTC
