### ISSUE TITLE
Unbalanced quote in tag value leads to "unable to parse"

### ISSUE THREAD

**Issue by undera** [influxdb/influxdb#5204] opened 2015-12-22 20:00 UTC
The issue happens with tag values having unbalanced quote in it. I'm writing points like this:
```
t143,label=hey\ "ya a=1i,value=0i
t143,label=another a=2i,value=1i 1
```

And getting:
```
HTTP Code 400 {"error":"unable to parse 't143,label=hey\\ \"ya a=1i,value=0i\nt143,label=another a=2i,value=1i 1': invalid number"}
```

My experiments show that to reproduce it you need to have space before quote in tag value.

**Comment by jsternberg** [comment] 2015-12-22 20:22
@undera what version of InfluxDB are you running? I'm getting this error from it:

```
{"error":"unable to parse 't143,label=hey\\ \"ya a=1i,value=0i t143,label=another a=2i,value=1i 1': bad timestamp"}
```

My error message appears to have two backslashes after "hey" while yours has a single backslash. Can you tell me how you sent this data to the server? I wrote the first code block to a test file named `test.txt` and then sent the data using curl.

```
curl -i -XPOST 'http://localhost:8086/write?db=db' --data-binary @test.txt
```

**Comment by undera** [comment] 2015-12-22 20:26
The extra backslashes is JSON escaping, I probably removed some of them when I was composing the report. Wanted to make it clearer :)

I double-checked with the sniffer that the data sent to server is what I shown.

I'm sending data using influxdb-php library. My version is 0.9.6.1 under Ubuntu.

**Comment by jsternberg** [comment] 2015-12-22 20:46
I think your syntax may be incorrect for the format you're writing the data in. I'm not sure why you're getting a different error message from me, but let me explain how to read the line you gave me. Quotes are only meaningful in a field value within a string as documented [here](https://docs.influxdata.com/influxdb/v0.9/write_protocols/line/).

Only one `key,tags fields timestamp` measurement can be on a line at a time. In your query, it looks like you might be trying to send two writes on the same line. Either way, the input doesn't follow the format.

The way your write gets parsed is as:

```
key: t143,label=hey\ "ya
fields: a=1i,value=0i
timestamp: t143,label=another a=2i,value=1i 1
```

Since that last one isn't a valid timestamp, the writer rejects it as an error. What values are you intending to send?

**Comment by undera** [comment] 2015-12-22 21:37
Ah, so sorry for my carelessness. It's my logging facility that eliminates \n. Actual data I sent is two lines:
```
t159,label=hey\ "ya a=1i,value=0i
t159,label=another a=2i,value=1i 1
```

Single line don't reproduce it, only these two lines

**Comment by jsternberg** [comment] 2015-12-22 22:31
Ok. I'm able to reproduce it now. It looks like it only happens when it's those two lines are done in sequence. I can't reproduce when it's each one individually.

Thank you for your bug report. I'll be looking into it.

**Comment by beckettsean** [comment] 2015-12-22 23:24
I think this is a duplicate of https://github.com/influxdb/influxdb/issues/3465

**Comment by beckettsean** [comment] 2015-12-22 23:26
@undera the syntax requires double-quotes in tags to be escaped:

```
t159,label=hey\ \"ya a=1i,value=0i
t159,label=another a=2i,value=1i 1
```

**Comment by beckettsean** [comment] 2015-12-22 23:29
not really a dupe, reopening for @jsternberg to continue investigating

**Comment by undera** [comment] 2015-12-23 05:26
At least docs should be fixed, since there're no mention on this escaping need: https://influxdb.com/docs/v0.9/write_protocols/write_syntax.html#escaping-characters

And because it is not specified in docs, the client libraries don't implement it. I use this library: https://github.com/influxdb/influxdb-php

**Comment by jwilder** [comment] 2015-12-23 06:12
Tag keys and values don't need to escape quotes.  This looks like a parsing bug.

**Closed** 2016-01-04 20:01 UTC
Labels: 2 - Working
