### ISSUE TITLE
[0.9.3] influxdb just stops when backing up 

### ISSUE THREAD

**Issue by airyland** [influxdb/influxdb#3919] opened 2015-09-01 06:46 UTC

**Comment by beckettsean** [comment] 2015-09-01 17:57
@airyland can you give the command you ran to start the backup, as well as the last lines in the log?

When you say "stopped" does that mean the process died, or that the process is up but totally unresponsive, or something else? Can you please clarify a bit more?

**Comment by beckettsean** [comment] 2015-09-02 17:53
closing as duplicate of #3700

**Closed by beckettsean** 2015-09-02 17:53 UTC
