### ISSUE TITLE
[0.9.2] Unable to have field or tag names as `default`

### ISSUE THREAD

**Issue by jhorwit2** [influxdb/influxdb#3622] opened 2015-08-11 12:16 UTC
Steps to reproduce 
```
curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb" 
curl -i -XPOST 'http://localhost:8086/write?db=mydb' --data-binary 'cpu_load_short,host=server01,region=us-west default=true,value=0.64 1434055562000000000'
```

I don't remember ever reading this restriction in the docs, but I get the following error:
`Server returned error: found DEFAULT, expected identifier, string, number, bool at line 1, char 60`

**Comment by beckettsean** [comment] 2015-08-11 18:44
Duplicate of https://github.com/influxdb/influxdb/issues/3547, will be fixed in 0.9.3 and is in the nightlies already.

**Closed by beckettsean** 2015-08-11 18:44 UTC
