### ISSUE TITLE
Why does influxDB collectd plugin create timeseries like "HOST/dsname/disk_ops" 

### ISSUE THREAD

**Issue by thefallentree** [influxdb/influxdb#1880] opened 2015-03-07 12:37 UTC
I'm trying out the new native influxdb collected plugin, and I found that it is creating time series named as 'HOST/dsname/disk_ops" , why is that? the relevant field is already present in the time series itself as "host" and 'dsname" field. why repeat it in the name?

IMHO, this only makes it doesn't look very efficient to write my query as select * from /.+disk_ops/ instead of  select * from disk_ops (I'm also sure there are plenty of regexp cost).

Thanks

**Comment by kimor79** [comment] 2015-03-09 17:29
I did it that way to keep it consistent with how collectd's rrdtool plugin formats the metric name and my understanding that using where clauses on those fields wasn't very performant on v0.8. v0.9 changes this so it's closer to just "disk_ops".

**Comment by corylanou** [comment] 2015-03-09 17:54
Based on how we re-wrote some of the logic for parsing the collectd endpoint to match up with our new tags, it seems like there are some use cases that we don't work nicely with.  I think it makes sense to allow for some additional configuration to let the endpoint know how to better parse the collectd fields.

**Comment by ecki** [comment] 2015-06-30 20:32
Is this a 'duplicate' of issue #1148? Can maybe both be closed with a link to the new schema (and possibly config location).

**Comment by beckettsean** [comment] 2015-09-17 22:04
closing as dupe of #1148

**Closed by beckettsean** 2015-09-17 22:04 UTC
