### ISSUE TITLE
[0.9.3] panic after I tried to create first backup

### ISSUE THREAD

**Issue by esecules** [influxdb/influxdb#4224] opened 2015-09-24 22:56 UTC
It created an empty snapshot and crashed influx
here's the beginning of the trace
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x726688]

goroutine 5870 [running]:
github.com/boltdb/bolt.(*DB).beginTx(0x0, 0xc2813d3950, 0x0, 0x0)
	/root/go/src/github.com/boltdb/bolt/db.go:422 +0x358
github.com/boltdb/bolt.(*DB).Begin(0x0, 0x0, 0x7fdeaf2de530, 0x0, 0x0)
	/root/go/src/github.com/boltdb/bolt/db.go:415 +0x6d
github.com/influxdb/influxdb/tsdb.appendShardSnapshotFile(0xc2813d4c20, 0xc222f14c60, 0xc2244d55c8, 0x1f, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/tsdb/snapshot_writer.go:86 +0x1b9
github.com/influxdb/influxdb/tsdb.appendShardSnapshotFiles(0xc2813d4c20, 0xc20803a820, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/tsdb/snapshot_writer.go:70 +0x651
github.com/influxdb/influxdb/tsdb.func·013(0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/tsdb/snapshot_writer.go:31 +0x446
github.com/influxdb/influxdb/tsdb.NewSnapshotWriter(0xc2813d8000, 0x1578, 0x1b00, 0xc20803a820, 0x0, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/tsdb/snapshot_writer.go:36 +0x141
github.com/influxdb/influxdb/services/snapshotter.(*Service).writeSnapshot(0xc208060e60, 0x7fdeaf2e4020, 0xc20815af90, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/services/snapshotter/service.go:131 +0x1c7
github.com/influxdb/influxdb/services/snapshotter.(*Service).handleConn(0xc208060e60, 0x7fdeaf2e4020, 0xc20815af90, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/services/snapshotter/service.go:105 +0x1cd
github.com/influxdb/influxdb/services/snapshotter.func·001(0x7fdeaf2e4020, 0xc20815af90)
	/root/go/src/github.com/influxdb/influxdb/services/snapshotter/service.go:89 +0xaf
created by github.com/influxdb/influxdb/services/snapshotter.(*Service).serve
	/root/go/src/github.com/influxdb/influxdb/services/snapshotter/service.go:92 +0x465

goroutine 1 [chan receive, 24 minutes]:
main.(*Main).Run(0xc20807dac0, 0xc20800a010, 0x2, 0x2, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:91 +0x777
main.main()
	/root/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:42 +0xdc

goroutine 6 [syscall, 42 minutes]:
os/signal.loop()
	/root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, 42 minutes, locked to thread]:
runtime.goexit()
	/root/.gvm/gos/go1.4.2/src/runtime/asm_amd64.s:2232 +0x1
```

**Comment by esecules** [comment] 2015-09-24 23:08
probably duplicate of #3700 

Is there a workaround for now?

**Comment by beckettsean** [comment] 2015-09-25 20:41
closing as dupe of #3700. I'm unaware of a workaround. There appear to be some fundamental bugs in the backup code.

**Closed** 2015-09-25 23:31 UTC
Labels: category/internal
