### ISSUE TITLE
Unable to write to non-existent series in rc-29

### ISSUE THREAD

**Issue by tbaudais-va** [influxdb/influxdb#2512] opened 2015-05-07 20:23 UTC
Steps to reproduce:

1. Try to create a point on a non-existent series
```
curl -XPOST 'http://1.2.3.4:8086/write?u=vinflux&p=pass' -d '{"database": "repcore-dev","retentionPolicy": "default","points": [{"name": "foo","tags": {},"fields": {"count":666}}]}'
```

2. Note error
```
{"error":"series not found"}
```

Notes:
- Auth is enabled

**Comment by beckettsean** [comment] 2015-05-07 23:32
Series are automatically created when points are written to them. Did the database and retention policy already exist? Did you perhaps previously create and then drop the series "foo"

I had no difficulty running your curl statement against a clean database, although I was not using auth. The point was written and is query-able.

**Comment by beckettsean** [comment] 2015-05-07 23:34
Further investigation shows that error message lives in only one place in the code, and the most likely explanation was that in between when the write was accepted and when it was written to the shard the series "foo" was deleted.

Can you repro this with a set of curl statements?

**Comment by tbaudais-va** [comment] 2015-05-08 15:13
I'll do more poking around today. I'm pretty sure we didn't delete the series at all but I'll double check.

**Comment by beckettsean** [comment] 2015-05-12 23:50
@tbaudais-va were you running these tests on a single instance or a cluster?

**Comment by tbaudais-va** [comment] 2015-05-13 15:20
Single instance

**Comment by beckettsean** [comment] 2015-05-13 18:05
I'm fresh out of ideas on how to repro this. Our best theory involved a race condition in clustering along with a node failure, but on a single instance the race condition cannot happen.

**Comment by beckettsean** [comment] 2015-05-19 20:38
cannot reproduce, closing issue. Opening issue #2613 to make the error a panic, since this should be unreachable code.

**Closed by beckettsean** 2015-05-19 20:38 UTC
