### ISSUE TITLE
Add series alteration

### ISSUE THREAD

**Issue by sbouchex** [influxdb/influxdb#4146] opened 2015-09-17 09:47 UTC
Here is a feature request that could be very helpful to manage series

Add the ability to alter series by adding, removing tags.

Example:
- The db contains a serie "my_metric" without any tag and you want to add a tag to all data.
- The simple query will do that : ALTER SERIE "my_metric" ADD TAG "tag=1, tag2=2"

Other possibilities:
- Move data from one series to another
- Remove tag to a serie

**Comment by rkuchan** [comment] 2015-09-17 17:27
@sbouchex,

Could you give me a specific use case for this feature?

Thanks!

**Comment by beckettsean** [comment] 2015-09-17 18:48
closing as duplicate of #3904

**Closed by beckettsean** 2015-09-17 18:48 UTC
