### ISSUE TITLE
Ubuntu 0.9.5-rc3 Package Won't Upgrade from 0.9.4.2

### ISSUE THREAD

**Issue by mpetersen42** [influxdb/influxdb#4827] opened 2015-11-17 20:46 UTC
I've never run influxdb on this system.  I noticed that one of the cluster warnings was resolved so I thought I'd try 0.9.5-rc3 instead of 0.9.4.2.  It appears some pre-install script should test for/create /etc/influxdb (it used to be /etc/opt/influxdb?)

user@influx02:~$ sudo dpkg -i ./influxdb_0.9.5-rc3_amd64.deb
Preparing to unpack ./influxdb_0.9.5-rc3_amd64.deb ...
cp: cannot create regular file ‘/etc/influxdb/’: Not a directory

user@influx02:~$ sudo mkdir /etc/influxdb

user@influx02:~$ sudo dpkg -i ./influxdb_0.9.5-rc3_amd64.deb 
(Reading database ... 87378 files and directories currently installed.)
Preparing to unpack ./influxdb_0.9.5-rc3_amd64.deb ...
Unpacking influxdb (0.9.5-rc3) over (0.9.5-rc3) ...
 Removing any system startup links for /etc/init.d/influxdb ...
   /etc/rc0.d/K20influxdb
   /etc/rc1.d/K20influxdb
   /etc/rc2.d/S20influxdb
   /etc/rc3.d/S20influxdb
   /etc/rc4.d/S20influxdb
   /etc/rc5.d/S20influxdb
   /etc/rc6.d/K20influxdb
Setting up influxdb (0.9.5-rc3) ...
 Removing any system startup links for /etc/init.d/influxdb ...
 Adding system startup for /etc/init.d/influxdb ...
   /etc/rc0.d/K20influxdb -> ../init.d/influxdb
   /etc/rc1.d/K20influxdb -> ../init.d/influxdb
   /etc/rc6.d/K20influxdb -> ../init.d/influxdb
   /etc/rc2.d/S20influxdb -> ../init.d/influxdb
   /etc/rc3.d/S20influxdb -> ../init.d/influxdb
   /etc/rc4.d/S20influxdb -> ../init.d/influxdb
   /etc/rc5.d/S20influxdb -> ../init.d/influxdb

**Comment by rossmcdonald** [comment] 2015-11-17 21:33
@otoolep Verified. This is caused by the `pre-install.sh` script (incorrectly) assuming the `/etc/influxdb` directory is already there. I've created a PR for a fix in #4828.

**Comment by rossmcdonald** [comment] 2015-11-17 22:08
#4828 has now been merged and cherry-picked into the 0.9.5 branch, so this will be fixed with the next release.

@mpetersen42 Thanks for reporting this!

**Closed by rossmcdonald** 2015-11-17 22:08 UTC
Labels: blocking release
