### ISSUE TITLE
golang client corrupts time

### ISSUE THREAD

**Issue by abligh** [influxdb/influxdb#4371] opened 2015-10-08 16:27 UTC
Using server 0.9.4.1 on OS-X from brew, and Client commit 73a630dfa64003c27782a1b0a6b817e839c5c3ea from github, the time is transmitted incorrectly if a precision is specified. Removing the precision fixes the issue.

IE using this example from the client home page here: https://github.com/influxdb/influxdb/tree/master/client

    for i := 0; i < sampleSize; i++ {
        pts[i] = client.Point{
            Measurement: "shapes",
            Tags: map[string]string{
                "color": strconv.Itoa(rand.Intn(len(colors))),
                "shape": strconv.Itoa(rand.Intn(len(shapes))),
            },
            Fields: map[string]interface{}{
                "value": rand.Intn(sampleSize),
            },
            Time: time.Now(),
            Precision: "s",
        }
    }

fails unless `Precision: "s"` is removed, as the inserted date looks like: `1970-01-01T00:00:01.444320501Z` i.e. is a factor of 1,000,000 out.

**Comment by johnjelinek** [comment] 2015-10-08 21:46
This is also the case for `0.9.4.1` via Docker (image: `tutum/influxdb`) based on Ubuntu Trusty.

**Comment by beckettsean** [comment] 2015-10-08 21:48
duplicate of https://github.com/influxdb/influxdb/issues/4281

**Closed by beckettsean** 2015-10-08 21:48 UTC
