### ISSUE TITLE
Write request causes "500: timeout" error after drop measurement

### ISSUE THREAD

**Issue by ityaptin** [influxdb/influxdb#4526] opened 2015-10-21 11:54 UTC
When we trying to delete measurement due intensive data writing (thousands of points/s) it causes a write lock in database which raises a "500: timeout" error for the all further write requests. 
So, after this I can't write or get data until the restarting InfluxDB.
It reproduced on 0.9.4 and on the 0.9.5-nightly-6f80d69.

Trace logs after the DROP MEASUREMENT http://pastebin.com/RxAcUBcc

**Comment by jwilder** [comment] 2015-10-29 15:53
I believe this is fixed by #4580.  Can't reproduce with 4cec36c.

**Closed by jwilder** 2015-10-29 15:53 UTC
