### ISSUE TITLE
[0.9.5-nightly] CQ with derivative() broken 

### ISSUE THREAD

**Issue by dswarbrick** [influxdb/influxdb#4613] opened 2015-10-29 13:42 UTC
On 0.9.5-nightly-542efbb, the following CQ would produce values:

```
CREATE CONTINUOUS QUERY io_sectors_read_delta ON testdb BEGIN
  SELECT derivative(mean("read")) AS read_delta INTO io_sectors_delta FROM iolatency
  WHERE plugin_instance = 'md400' AND type = 'iostats_sectors' GROUP BY time(1m), *
END
```

However the same query on 0.9.5-nightly-66a31ee consistently inserts zeros. Running the query interactively (i.e., not as a CQ), it produces the desired derivatives. Also if I remove the derivative from the CQ, and just have it calculate mean(), this inserts the correct values into the io_sectors_delta measurement. But I don't want mean().... I want derivative(mean()) :(

**Comment by beckettsean** [comment] 2015-10-29 16:53
Closing as duplicate of https://github.com/influxdb/influxdb/issues/3247.

**Closed by beckettsean** 2015-10-29 16:53 UTC
Labels: category/functions
