### ISSUE TITLE
[0.9.5-rc2]The datas shared with three machines in cluster are Inconsistent, "show shards" has only two onwers

### ISSUE THREAD

**Issue by guaiguaihw** [influxdb/influxdb#4800] opened 2015-11-15 10:21 UTC
I update influxdb to 0.9.5-rc2 with three machines, but the last one does not have any datas.
My output information is below:
![image](https://cloud.githubusercontent.com/assets/11972366/11168308/22a7369a-8bc5-11e5-9f8c-ce78750fd0c1.png)
![image](https://cloud.githubusercontent.com/assets/11972366/11168312/3d10fdc2-8bc5-11e5-90e8-bb4258d59fb5.png)
when I want to "show measurements" ,error occurs：
![image](https://cloud.githubusercontent.com/assets/11972366/11168321/8d09780e-8bc5-11e5-9fef-444c54598c12.png)

**Comment by guaiguaihw** [comment] 2015-11-15 10:25
My configure file is below:

[meta]
  dir = "/data1/influxdb/meta"
  hostname = "10.222.11.70"
  bind-address = ":8088"
  retention-autocreate = true
  election-timeout = "1s"
  heartbeat-timeout = "1s"
  leader-lease-timeout = "500ms"
  commit-timeout = "50ms"
  cluster-tracing = false
  peers = ["10.222.12.134:8088", "10.222.11.81:8088", "10.222.11.70:8088"]

[data]
  dir = "/data1/influxdb/data"
  max-wal-size = 104857600 # Maximum size the WAL can reach before a flush. Defaults to 100MB.
  wal-flush-interval = "10m" # Maximum time data can sit in WAL before a flush.
  wal-partition-flush-delay = "2s" # The delay time between each WAL partition being flushed.

  # These are the WAL settings for the storage engine >= 0.9.3
  wal-dir = "/data1/influxdb/wal"
  wal-enable-logging = true

 [hinted-handoff]
  enabled = true
  dir = "/data1/influxdb/hh"
  max-size = 1073741824
  max-age = "168h"
  retry-rate-limit = 0

 [cluster]
  shard-writer-timeout = "10s" # The time within which a shard must respond to write.
  write-timeout = "5s" # The time within which a write operation must complete on the cluster.

[retention]
  enabled = true
  check-interval = "30m"

[shard-precreation]
  enabled = true
  check-interval = "10m"
  advance-period = "30m"

[monitor]
  store-enabled = true # Whether to record statistics internally.
  store-database = "_internal" # The destination database for recorded statistics
  store-interval = "10s" # The interval at which to record statistics

[admin]
  enabled = true
  bind-address = ":8081"
  https-enabled = false
  https-certificate = "/etc/ssl/influxdb.pem"

[http]
  enabled = true
  bind-address = ":8080"
  auth-enabled = false
  log-enabled = true
  write-tracing = false
  pprof-enabled = false
  https-enabled = false
  https-certificate = "/etc/ssl/influxdb.pem"

[continuous_queries]
  log-enabled = true
  enabled = true
  recompute-previous-n = 2
  recompute-no-older-than = "10m"
  compute-runs-per-interval = 10
  compute-no-more-than = "2m"
 ~/influxdb/conf/influxdb.conf

**Comment by guaiguaihw** [comment] 2015-11-15 10:35
I also confuse that my log shows  datas has been written into influxdb:
![image](https://cloud.githubusercontent.com/assets/11972366/11168366/59680324-8bc7-11e5-9807-09a3f96359d5.png)
but nothing left in my directory, there are all dropped???
![image](https://cloud.githubusercontent.com/assets/11972366/11168372/93416310-8bc7-11e5-9417-c23bcd4eb2ef.png)

**Comment by sergzin** [comment] 2015-11-15 16:07
Try to set replication factor equal to number of nodes in cluster.

**Comment by otoolep** [comment] 2015-11-15 22:10
@guaiguaihw - what replication factor are you using for the target retention policy?

@dgnorton -- the marshaling error looks like the issue you were looking at.

**Comment by beckettsean** [comment] 2015-11-16 18:59
closing as duplicate of https://github.com/influxdb/influxdb/issues/4550.

@guaiguaihw thanks for the report, please add any additional details to https://github.com/influxdb/influxdb/issues/4550, and if possible, copy/paste the text from the terminal rather than screenshots.

**Closed by beckettsean** 2015-11-16 18:59 UTC
