### ISSUE TITLE
[0.9.4.1] SLIMIT clause ignored

### ISSUE THREAD

**Issue by jacekgrzybowski** [influxdb/influxdb#4271] opened 2015-09-29 13:54 UTC
Hello, I've just upgraded to `0.9.4.1` and need to retrieve the latest point from a series identified by a single tag but without taking into consideration other tags.
![last_4](https://cloud.githubusercontent.com/assets/3914691/10165830/7eded5e0-66c1-11e5-8326-57ed73611613.png)

First I thought that `ORDER BY time DESC LIMIT 1` would be sufficient, but as presented on the screenshot above (and as stated in the docs as I found out) that is not going to work in my case as it is going to return points with various tags (datacenter_id in my case) not really giving me the option to retrieve that one last point by narrowing the LIMIT to 1. I find this behavior really surprising because in case I was interested in tags I could add `GROUP BY datacenter_id` to the query and get x last points for each datacenter instead of a flat list which is not really sorted by time.

So I read about the `SLIMIT` option and that should be exactly what I'm looking for, however in my case it does not work and is ignored, as you can see on the screenshot below:
![image](https://cloud.githubusercontent.com/assets/3914691/10165989/40704bc6-66c2-11e5-89cf-617f473d2008.png)

The question is whether `SLIMIT` is supposed to work in `0.9.4.1` and if not, how can I retrieve the very last point in my scenario?

**Comment by beckettsean** [comment] 2015-09-29 17:14
This is a duplicate of https://github.com/influxdb/influxdb/issues/4232.

Try either query with `GROUP BY *` and I believe you will get the results you expect

**Closed by beckettsean** 2015-09-29 17:14 UTC
