### ISSUE TITLE
How to set time zone?

### ISSUE THREAD

**Issue by airyland** [influxdb/influxdb#4030] opened 2015-09-08 10:27 UTC
If I count and group by time(1d) or time(1h), the data is not that correct or not the list I wanted.

**Comment by beckettsean** [comment] 2015-09-08 21:00
closing as duplicate of https://github.com/influxdb/influxdb/issues/1837 or https://github.com/influxdb/influxdb/issues/2074

**Closed by beckettsean** 2015-09-08 21:00 UTC
