### ISSUE TITLE
Feature request: support queries that cross retention policies

### ISSUE THREAD

**Issue by brettdh** [influxdb/influxdb#3003] opened 2015-06-16 20:09 UTC
Use case: I want to have a database with the following retention policies at the given data granularities:

  * 10sec bins for 1 hour
  * 5min bins for 1 day
  * 1 hour bins for 1 week

etc. Assume the continuous queries that implement these ensure that they are disjoint; e.g. there are no 5-minute bins for the past hour; just starting 1 hour ago.

Now, I would like to issue a single query for the past three days. This crosses three retention policies, and [there is currently no way to do this][mailinglist]; instead I must issue a separate query to each retention policy.

Not 100% sure what the response should look like; maybe each record should contain its retention policy? No, it seems more that the client doesn't care about the retention policy of the data it's querying; even the bin size seems like something the client should have to care about when making the query, though it will have to deal with them in the response.

I have very little experience with InfluxDB at the moment (still evaluating for my application), but based on what I have seen, I would expect something like `SELECT count FROM messages.* WHERE time > now() - 3d`, with a response containing three `series`, named `messages.10s`, `messages.5m`, and `messages.1h` or something. Again, wild speculation; not sure what the best interface would be here. The homegrown timeseries database we currently use returns the bin boundaries with each record, but it also automatically rolls newer, small bins into larger ones so that all the bins in the result are the same size. I'm not sure I like that approach (but I am glad to have the option with e.g. `GROUP BY time(5m)`).

Thanks for your consideration (and gentle correction if need be).

[mailinglist]: https://groups.google.com/forum/#!msg/influxdb/xJVpiS-VkB0/Aa0flPsfwmEJ

**Comment by scharissis** [comment] 2015-07-24 05:41
+1 - this would be cool.

Since the query format is:
`select value from <db>.<rp>.<measurement> ...`
Perhaps the query notation could be:
`select value from <db>.*.<measurement> ...`


What would also be nice is to be able to use the same series, but apply a 'downsampling policy' so that, for example, the latest 2 weeks of data is at raw/high granularity, 2weeks-1month is downsampled to hourly, 6m-1y to daily, etc. So your queries would remain the same.

**Comment by brettdh** [comment] 2015-07-27 18:37
Yeah, that sounds like exactly what I'm looking for too. That approach would definitely require the returned points to contain their bin width, since you'd now have one series with points representing different granularities of data.

**Comment by xo4n** [comment] 2015-08-11 12:13
+1 holy grail

**Comment by beckettsean** [comment] 2015-09-17 23:13
closed as dupe of #2625

**Closed by beckettsean** 2015-09-17 23:13 UTC
Labels: RFC
