### ISSUE TITLE
rc28 panic -- interface conversion: interface is string, not float64

### ISSUE THREAD

**Issue by ecables** [influxdb/influxdb#2456] opened 2015-04-29 22:59 UTC
Perhaps I'm doing something silly, but a simple sum() or mean() query against a measurement's values is causing a panic in rc28. I have the full panic output, if that's of interest.

The following query works fine:
SELECT value FROM output_bps limit 5;
time					value
2015-04-28T15:56:02Z	837367639
2015-04-28T15:56:02Z	269102821
2015-04-28T15:56:02Z	393390752
2015-04-28T15:56:02Z	169437859
2015-04-28T15:56:02Z	1067908009

If I issue a sum(value) for the same query above, influx panics, and crashes.

Example:
SELECT sum(value) FROM output_bps limit 5;

Error in influxd.log:
panic: interface conversion: interface is string, not float64
<followed by 1,000 lines of debug output>

**Comment by neonstalwart** [comment] 2015-04-30 13:49
i'm going to bet that you inserted `"value": "837367639"` rather than `"value": 837367639`.  can you possibly show the JSON response of `SELECT value FROM output_bps limit 5`?

**Comment by otoolep** [comment] 2015-04-30 18:49
Dupe of 2299.

**Comment by otoolep** [comment] 2015-04-30 18:50
https://github.com/influxdb/influxdb/issues/2299

Please be sure not to quote your numeric values when sending them into InfluxDB as they will then be interpreted as string.

**Closed by otoolep** 2015-04-30 18:49 UTC
