### ISSUE TITLE
influxdb crash with select mean(V1)+V2 from foo where sometag='someval'

### ISSUE THREAD

**Issue by ExaTad** [influxdb/influxdb#3875] opened 2015-08-27 22:57 UTC
This query causes influxdb 0.9.2 to crash reliably

cli:
```
$ influx
> use somedb
> select mean(V1)+V2 from foo where sometag='someval'
```
The console log from influxdb:
```
# /opt/influxdb/influxd -config /etc/influxdb/influxdb.conf 

 8888888           .d888 888                   8888888b.  888888b.
   888            d88P"  888                   888  "Y88b 888  "88b
   888            888    888                   888    888 888  .88P
   888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
   888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
   888   888  888 888    888 888  888   X88K   888    888 888    888
   888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
 8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"

using configuration at: /etc/influxdb/influxdb.conf
[metastore] 2015/08/27 15:51:21 [INFO] raft: Node at 127.0.0.1:8088 [Follower] entering Follower state
[metastore] 2015/08/27 15:51:21 read local node id: 1
[shard] 2015/08/27 15:51:21 flush 1 points in 0.003s
[shard] 2015/08/27 15:51:21 flush 1 points in 0.004s
[admin] 2015/08/27 15:51:21 listening on HTTP: [::]:8083
[httpd] 2015/08/27 15:51:21 authentication enabled: false
[httpd] 2015/08/27 15:51:21 listening on HTTP: [::]:8086
2015/08/27 15:51:21 InfluxDB starting, version 0.9.2, commit 6c0a91f775f9fc0e625d17ffa04a3fe86945ba09
2015/08/27 15:51:21 GOMAXPROCS set to 8
[run] 2015/08/27 15:51:21 listening for signals
[metastore] 2015/08/27 15:51:23 [WARN] raft: Heartbeat timeout reached, starting election
[metastore] 2015/08/27 15:51:23 [INFO] raft: Node at 127.0.0.1:8088 [Candidate] entering Candidate state
[metastore] 2015/08/27 15:51:23 [DEBUG] raft: Votes needed: 1
[metastore] 2015/08/27 15:51:23 [DEBUG] raft: Vote granted. Tally: 1
[metastore] 2015/08/27 15:51:23 [INFO] raft: Election won. Tally: 1
[metastore] 2015/08/27 15:51:23 [INFO] raft: Node at 127.0.0.1:8088 [Leader] entering Leader state
[metastore] 2015/08/27 15:51:23 [INFO] raft: Disabling EnableSingleNode (bootstrap)
[metastore] 2015/08/27 15:51:23 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
[metastore] 2015/08/27 15:51:23 [DEBUG] raft: Node 127.0.0.1:8088 updated peer set (2): [127.0.0.1:8088]
2015/08/27 15:51:23 Sending anonymous usage statistics to m.influxdb.com
[http] 2015/08/27 15:51:26 127.0.0.1 - - [27/Aug/2015:15:51:26 -0700] GET /ping HTTP/1.1 204 0 - InfluxDBShell/0.9.2 25f6f2ea-4d0e-11e5-8001-000000000000 89.72µs
[http] 2015/08/27 15:51:32 127.0.0.1 - - [27/Aug/2015:15:51:32 -0700] GET /query?db=&q=select+mean%28A3%29%2BA3+from+smart+where+drive%3D%27DriveID3%27 HTTP/1.1 200 72 - InfluxDBShell/0.9.2 293175f3-4d0e-11e5-8002-000000000000 1.408367ms
panic: runtime error: index out of range

goroutine 47 [running]:
github.com/influxdb/influxdb/influxql.func·016(0xc2080f30a0, 0x2, 0x2, 0x8fc9e0, 0xc2081a0218)
	/root/go/src/github.com/influxdb/influxdb/influxql/result.go:146 +0x4a
github.com/influxdb/influxdb/influxql.func·018(0xc2080f30a0, 0x2, 0x2, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/influxql/result.go:168 +0xa2
github.com/influxdb/influxdb/tsdb.processForMath(0xc208184038, 0x1, 0x1, 0xc2080f2fe0, 0x1, 0x1, 0x0, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/tsdb/engine.go:863 +0x4ad
github.com/influxdb/influxdb/tsdb.(*AggregateExecutor).execute(0xc2080fac00, 0xc2081866c0)
	/root/go/src/github.com/influxdb/influxdb/tsdb/engine.go:483 +0x1da2
created by github.com/influxdb/influxdb/tsdb.(*AggregateExecutor).Execute
	/root/go/src/github.com/influxdb/influxdb/tsdb/engine.go:337 +0x5a

goroutine 1 [chan receive]:
main.(*Main).Run(0xc208091ac0, 0xc20800a010, 0x2, 0x2, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:86 +0x73b
main.main()
	/root/go/src/github.com/influxdb/influxdb/cmd/influxd/main.go:38 +0xdc

goroutine 6 [syscall]:
os/signal.loop()
	/root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/root/.gvm/gos/go1.4.2/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/root/.gvm/gos/go1.4.2/src/runtime/asm_amd64.s:2232 +0x1

goroutine 8 [IO wait]:
net.(*pollDesc).Wait(0xc20800e370, 0x72, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20800e370, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc20800e310, 0x0, 0x7f5f8d3b9cc8, 0xc2080f6000)
	/root/.gvm/gos/go1.4.2/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208038a48, 0x0, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc208038a48, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:244 +0x4c
github.com/influxdb/influxdb/tcp.(*Mux).Serve(0xc2080c3aa0, 0x7f5f8d3bc270, 0xc208038a48, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/tcp/mux.go:45 +0x57
created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
	/root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:298 +0x7a8

goroutine 9 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc208038a50, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
github.com/influxdb/influxdb/meta.(*raftLayer).Accept(0xc2080c3ad0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/meta/store.go:1855 +0x64
github.com/hashicorp/raft.(*NetworkTransport).listen(0xc20800e3f0)
	/root/go/src/github.com/hashicorp/raft/net_transport.go:346 +0x50
created by github.com/hashicorp/raft.NewNetworkTransport
	/root/go/src/github.com/hashicorp/raft/net_transport.go:138 +0x2c4

goroutine 10 [select]:
github.com/hashicorp/raft.(*Raft).leaderLoop(0xc2080c01c0)
	/root/go/src/github.com/hashicorp/raft/raft.go:807 +0xc7c
github.com/hashicorp/raft.(*Raft).runLeader(0xc2080c01c0)
	/root/go/src/github.com/hashicorp/raft/raft.go:779 +0x74e
github.com/hashicorp/raft.(*Raft).run(0xc2080c01c0)
	/root/go/src/github.com/hashicorp/raft/raft.go:576 +0xc9
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.run)·fm()
	/root/go/src/github.com/hashicorp/raft/raft.go:241 +0x27
github.com/hashicorp/raft.func·011()
	/root/go/src/github.com/hashicorp/raft/state.go:152 +0x51
created by github.com/hashicorp/raft.(*raftState).goFunc
	/root/go/src/github.com/hashicorp/raft/state.go:153 +0xe3

goroutine 11 [select]:
github.com/hashicorp/raft.(*Raft).runFSM(0xc2080c01c0)
	/root/go/src/github.com/hashicorp/raft/raft.go:490 +0xf74
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runFSM)·fm()
	/root/go/src/github.com/hashicorp/raft/raft.go:242 +0x27
github.com/hashicorp/raft.func·011()
	/root/go/src/github.com/hashicorp/raft/state.go:152 +0x51
created by github.com/hashicorp/raft.(*raftState).goFunc
	/root/go/src/github.com/hashicorp/raft/state.go:153 +0xe3

goroutine 12 [select]:
github.com/hashicorp/raft.(*Raft).runSnapshots(0xc2080c01c0)
	/root/go/src/github.com/hashicorp/raft/raft.go:1594 +0x466
github.com/hashicorp/raft.*Raft.(github.com/hashicorp/raft.runSnapshots)·fm()
	/root/go/src/github.com/hashicorp/raft/raft.go:243 +0x27
github.com/hashicorp/raft.func·011()
	/root/go/src/github.com/hashicorp/raft/state.go:152 +0x51
created by github.com/hashicorp/raft.(*raftState).goFunc
	/root/go/src/github.com/hashicorp/raft/state.go:153 +0xe3

goroutine 13 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc208038a58, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
github.com/influxdb/influxdb/meta.(*Store).serveExecListener(0xc208072000)
	/root/go/src/github.com/influxdb/influxdb/meta/store.go:470 +0x8f
created by github.com/influxdb/influxdb/meta.(*Store).Open
	/root/go/src/github.com/influxdb/influxdb/meta/store.go:205 +0x1c2

goroutine 14 [select]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).monitorErrorChan(0xc2080ac0e0, 0xc208042240)
	/root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:421 +0x14a
created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
	/root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:304 +0x919

goroutine 15 [select]:
github.com/influxdb/influxdb/tsdb.(*Shard).autoflusher(0xc2080440b0, 0xc208043560)
	/root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:468 +0x39d
created by github.com/influxdb/influxdb/tsdb.func·010
	/root/go/src/github.com/influxdb/influxdb/tsdb/shard.go:149 +0x611

goroutine 16 [select]:
github.com/influxdb/influxdb/services/hh.(*Service).retryWrites(0xc2080714a0)
	/root/go/src/github.com/influxdb/influxdb/services/hh/service.go:98 +0x2e7
created by github.com/influxdb/influxdb/services/hh.(*Service).Open
	/root/go/src/github.com/influxdb/influxdb/services/hh/service.go:62 +0xef

goroutine 34 [select]:
github.com/influxdb/influxdb/services/hh.(*Service).expireWrites(0xc2080714a0)
	/root/go/src/github.com/influxdb/influxdb/services/hh/service.go:116 +0x2a4
created by github.com/influxdb/influxdb/services/hh.(*Service).Open
	/root/go/src/github.com/influxdb/influxdb/services/hh/service.go:63 +0x109

goroutine 35 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc208038a60, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
github.com/influxdb/influxdb/cluster.(*Service).serve(0xc20800e230)
	/root/go/src/github.com/influxdb/influxdb/cluster/service.go:79 +0x102
created by github.com/influxdb/influxdb/cluster.(*Service).Open
	/root/go/src/github.com/influxdb/influxdb/cluster/service.go:56 +0x67

goroutine 36 [select]:
github.com/influxdb/influxdb/services/precreator.(*Service).runPrecreation(0xc208034d70)
	/root/go/src/github.com/influxdb/influxdb/services/precreator/service.go:72 +0x407
created by github.com/influxdb/influxdb/services/precreator.(*Service).Open
	/root/go/src/github.com/influxdb/influxdb/services/precreator/service.go:50 +0xcb

goroutine 37 [chan receive]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc208038a68, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/tcp/mux.go:117 +0x80
github.com/influxdb/influxdb/services/snapshotter.(*Service).serve(0xc208034e60)
	/root/go/src/github.com/influxdb/influxdb/services/snapshotter/service.go:68 +0xad
created by github.com/influxdb/influxdb/services/snapshotter.(*Service).Open
	/root/go/src/github.com/influxdb/influxdb/services/snapshotter/service.go:46 +0x62

goroutine 38 [IO wait]:
net.(*pollDesc).Wait(0xc20800e920, 0x72, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20800e920, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc20800e8c0, 0x0, 0x7f5f8d3b9cc8, 0xc208028a10)
	/root/.gvm/gos/go1.4.2/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208114020, 0xc20801e700, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc208114020, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:244 +0x4c
net/http.(*Server).Serve(0xc20809e060, 0x7f5f8d3bc270, 0xc208114020, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1728 +0x92
net/http.Serve(0x7f5f8d3bc270, 0xc208114020, 0x7f5f8d3c0c20, 0xc208028a00, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1606 +0xa1
github.com/influxdb/influxdb/services/admin.(*Service).serve(0xc208034f00)
	/root/go/src/github.com/influxdb/influxdb/services/admin/service.go:105 +0x147
created by github.com/influxdb/influxdb/services/admin.(*Service).Open
	/root/go/src/github.com/influxdb/influxdb/services/admin/service.go:68 +0x431

goroutine 39 [select]:
github.com/influxdb/influxdb/services/continuous_querier.(*Service).backgroundLoop(0xc20800e2a0)
	/root/go/src/github.com/influxdb/influxdb/services/continuous_querier/service.go:151 +0x301
created by github.com/influxdb/influxdb/services/continuous_querier.(*Service).Open
	/root/go/src/github.com/influxdb/influxdb/services/continuous_querier/service.go:87 +0x1ed

goroutine 40 [IO wait]:
net.(*pollDesc).Wait(0xc20800ea70, 0x72, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20800ea70, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc20800ea10, 0x0, 0x7f5f8d3b9cc8, 0xc208029038)
	/root/.gvm/gos/go1.4.2/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208114028, 0xc20813ddc8, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc208114028, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:244 +0x4c
net/http.(*Server).Serve(0xc20812c060, 0x7f5f8d3bc270, 0xc208114028, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1728 +0x92
net/http.Serve(0x7f5f8d3bc270, 0xc208114028, 0x7f5f8d3c0bd0, 0xc2080aec00, 0x0, 0x0)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1606 +0xa1
github.com/influxdb/influxdb/services/httpd.(*Service).serve(0xc208035040)
	/root/go/src/github.com/influxdb/influxdb/services/httpd/service.go:107 +0x79
created by github.com/influxdb/influxdb/services/httpd.(*Service).Open
	/root/go/src/github.com/influxdb/influxdb/services/httpd/service.go:75 +0x590

goroutine 41 [select]:
github.com/influxdb/influxdb/services/retention.(*Service).deleteShardGroups(0xc208042960)
	/root/go/src/github.com/influxdb/influxdb/services/retention/service.go:67 +0x433
created by github.com/influxdb/influxdb/services/retention.(*Service).Open
	/root/go/src/github.com/influxdb/influxdb/services/retention/service.go:44 +0x67

goroutine 42 [select]:
github.com/influxdb/influxdb/services/retention.(*Service).deleteShards(0xc208042960)
	/root/go/src/github.com/influxdb/influxdb/services/retention/service.go:101 +0x821
created by github.com/influxdb/influxdb/services/retention.(*Service).Open
	/root/go/src/github.com/influxdb/influxdb/services/retention/service.go:45 +0x81

goroutine 43 [chan receive]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).startServerReporting(0xc2080ac0e0)
	/root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:372 +0x18e
created by github.com/influxdb/influxdb/cmd/influxd/run.func·003
	/root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:327 +0xdbe

goroutine 44 [select]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Command).monitorServerErrors(0xc20800fb90)
	/root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:125 +0x2da
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run
	/root/go/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:107 +0xbb4

goroutine 45 [chan receive]:
github.com/influxdb/influxdb/services/httpd.(*Handler).serveQuery(0xc2080aec00, 0x7f5f8d3c1548, 0xc2080f2840, 0xc20819c4e0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:268 +0xa44
github.com/influxdb/influxdb/services/httpd.*Handler.(github.com/influxdb/influxdb/services/httpd.serveQuery)·fm(0x7f5f8d3c1548, 0xc2080f2840, 0xc20819c4e0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:95 +0x4f
github.com/influxdb/influxdb/services/httpd.func·001(0x7f5f8d3c1548, 0xc2080f2840, 0xc20819c4e0)
	/root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:696 +0x78
net/http.HandlerFunc.ServeHTTP(0xc2080dfba0, 0x7f5f8d3c1548, 0xc2080f2840, 0xc20819c4e0)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/services/httpd.func·002(0x7f5f8d3c1470, 0xc2080f27e0, 0xc20819c4e0)
	/root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:754 +0x288
net/http.HandlerFunc.ServeHTTP(0xc2080dab50, 0x7f5f8d3c1470, 0xc2080f27e0, 0xc20819c4e0)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/services/httpd.func·003(0x7f5f8d3c1470, 0xc2080f27e0, 0xc20819c4e0)
	/root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:763 +0xba
net/http.HandlerFunc.ServeHTTP(0xc2080dfbc0, 0x7f5f8d3c1470, 0xc2080f27e0, 0xc20819c4e0)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/services/httpd.func·004(0x7f5f8d3c1470, 0xc2080f27e0, 0xc20819c4e0)
	/root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:796 +0x31a
net/http.HandlerFunc.ServeHTTP(0xc2080dab80, 0x7f5f8d3c1470, 0xc2080f27e0, 0xc20819c4e0)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/services/httpd.func·005(0x7f5f8d3c1470, 0xc2080f27e0, 0xc20819c4e0)
	/root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:806 +0x179
net/http.HandlerFunc.ServeHTTP(0xc2080daba0, 0x7f5f8d3c1470, 0xc2080f27e0, 0xc20819c4e0)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/services/httpd.func·006(0x7f5f8d3c1470, 0xc2080f27c0, 0xc20819c4e0)
	/root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:814 +0x123
net/http.HandlerFunc.ServeHTTP(0xc2080dfbe0, 0x7f5f8d3c1470, 0xc2080f27c0, 0xc20819c4e0)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/services/httpd.func·007(0x7f5f8d3c1438, 0xc2081a4280, 0xc20819c4e0)
	/root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:824 +0x12c
net/http.HandlerFunc.ServeHTTP(0xc2080dfc00, 0x7f5f8d3c1438, 0xc2081a4280, 0xc20819c4e0)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1265 +0x41
github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc208038950, 0x7f5f8d3c1438, 0xc2081a4280, 0xc20819c4e0)
	/root/go/src/github.com/bmizerany/pat/mux.go:109 +0x21c
github.com/influxdb/influxdb/services/httpd.(*Handler).ServeHTTP(0xc2080aec00, 0x7f5f8d3c1438, 0xc2081a4280, 0xc20819c4e0)
	/root/go/src/github.com/influxdb/influxdb/services/httpd/handler.go:175 +0x256
net/http.serverHandler.ServeHTTP(0xc20812c060, 0x7f5f8d3c1438, 0xc2081a4280, 0xc20819c4e0)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc2081a41e0)
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/root/.gvm/gos/go1.4.2/src/net/http/server.go:1751 +0x35e

goroutine 46 [chan receive]:
github.com/influxdb/influxdb/tsdb.(*QueryExecutor).executeSelectStatement(0xc208091800, 0x0, 0xc2081ba000, 0xc208186600, 0x2710, 0x0, 0x0)
	/root/go/src/github.com/influxdb/influxdb/tsdb/query_executor.go:282 +0x149
github.com/influxdb/influxdb/tsdb.func·006()
	/root/go/src/github.com/influxdb/influxdb/tsdb/query_executor.go:146 +0x6bd
created by github.com/influxdb/influxdb/tsdb.(*QueryExecutor).ExecuteQuery
	/root/go/src/github.com/influxdb/influxdb/tsdb/query_executor.go:196 +0x1f5
# 
'''

**Comment by otoolep** [comment] 2015-08-27 23:02
Dupe of https://github.com/influxdb/influxdb/issues/3200

**Comment by otoolep** [comment] 2015-08-27 23:02
Thanks for the report @ExaTad -- right now the query language does not support arithmetic involving two or more fields.

**Closed by otoolep** 2015-08-27 23:02 UTC
