### ISSUE TITLE
Client package has many dependencies

### ISSUE THREAD

**Issue by abh** [influxdb/influxdb#4093] opened 2015-09-13 20:22 UTC
Considering it's (mostly) just convenience methods to format text data and wrapping the http client the list of dependencies for github.com/influxdb/influxdb/client seems really excessive.

```
github.com/armon/go-metrics
github.com/boltdb/bolt
github.com/gogo/protobuf/proto
github.com/hashicorp/go-msgpack/codec
github.com/hashicorp/raft
github.com/hashicorp/raft-boltdb
github.com/influxdb/influxdb
golang.org/x/crypto/bcrypt
golang.org/x/crypto/blowfish
```

I was going to build the influxdb client into my app (using godep), but this gave me pause.

**Comment by corylanou** [comment] 2015-09-13 20:46
Duplicate of https://github.com/influxdb/influxdb/issues/3447

**Closed by corylanou** 2015-09-13 20:46 UTC
