### ISSUE TITLE
terminal prompt get lost after cli aborted

### ISSUE THREAD

**Issue by fffw** [influxdb/influxdb#4277] opened 2015-09-30 04:40 UTC
OS: Tested on Mac OS 10.10.5 and Ubuntu 14.04, but may not limited to them

InfluxDB Version: 0.9.3 ~ nightly build

How to reproduce: `influx -host=8.8.1.1` then `Ctrl^C`, all commands will not have prompt hereafter. `8.8.1.1` is randomly selected.

**Comment by beckettsean** [comment] 2015-09-30 04:52
closing as duplicate of https://github.com/influxdb/influxdb/issues/2609

**Closed by beckettsean** 2015-09-30 04:52 UTC
