### ISSUE TITLE
continuous queries with regex bug

### ISSUE THREAD

**Issue by rsmarques** [influxdb/influxdb#2559] opened 2015-05-13 13:45 UTC
Hello,

I've been experiencing some problems using continuous queries.

Briefly describing our data model, we have a game platform where users can perform several behaviours. Each of these events has an associated table (events.[event_name].count) and is mapped to two continuous queries through regex:

select count(user_id) from /^events\.\w+\.count$/ group by time(1d) into :series_name.1d.count
select distinct(user_id) from /^events\.\w+\.count$/ group by time(1d) into :series_name.1d.distinct

This has worked fine without any problem for weeks, until for some unknown reason it completed stopped from writting daily data to the continuous tables at May 4th, even though every day thousands of records are written to the other tables. We have also other continuous queries (without regex) that continue to work without any problem.

Any insights on this?

Specs:
Influxdb version: v0.8.8
Machine running influxdb (only runs influxdb, nothing more):
c4.xlarge (4 vCPU, 16 ECU, 7.5 GB RAM) running Ubuntu Server 14.04

Some Config file specs:
- write-buffer-size = 1000
- max-response-buffer-size = 100
- concurrent-shard-query-limit = 10
- flush-after = 1000
- bookmark-after = 1000
- index-after = 1000
- requests-per-logfile = 10000

Cheers,
Ricardo Marques

**Comment by neonstalwart** [comment] 2015-05-13 14:32
i think this is a duplicate of #2555.  as far as i understand, interpolation won't be part of 0.9.0 but i believe it is on the roadmap for 0.9.x

**Comment by neonstalwart** [comment] 2015-05-13 14:43
> Influxdb version: v0.8.8

my bad... my comment is not related to your case at all

**Comment by toddboom** [comment] 2015-05-13 17:56
@rsmarques i don't immediately see a reason that this should have stopped working. if you run the same count() and distinct() queries against the source data for the time range of the missing data, do the queries return successfully? have you tried restarting the daemon since you saw this behavior?

**Closed** 2015-06-09 23:25 UTC
Labels: obsoleted by v0.9.0
