### ISSUE TITLE
0.9.0_rc25: all socket ports used up

### ISSUE THREAD

**Issue by akaihola** [influxdb/influxdb#2310] opened 2015-04-16 11:01 UTC
When I install and start RC25 on my Ubuntu 14.04 box, I run out of local ports in a couple of minutes. As a result, other software isn't able to open TCP sockets.

I found one similar report [in the freenode IRC log](https://botbot.me/freenode/influxdb/2014-09-29/?msg=22535566&page=2).

    $ sudo apt-get purge influxdb
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    The following packages will be REMOVED:
      influxdb*
    0 upgraded, 0 newly installed, 1 to remove and 56 not upgraded.
    After this operation, 22.2 MB disk space will be freed.
    Do you want to continue? [Y/n] 
    (Reading database ... 385427 files and directories currently installed.)
    Removing influxdb (0.9.0-rc25) ...
    Purging configuration files for influxdb (0.9.0-rc25) ...
    dpkg: warning: while removing influxdb, directory '/opt/influxdb' not empty so not removed
    $ sudo rm -rf /opt/influxdb
    $ sudo dpkg -i influxdb_0.9.0-rc25_amd64.deb 
    Selecting previously unselected package influxdb.
    (Reading database ... 385416 files and directories currently installed.)
    Preparing to unpack .../influxdb_0.9.0-rc25_amd64.deb ...
    Unpacking influxdb (0.9.0-rc25) ...
    Setting up influxdb (0.9.0-rc25) ...
     Removing any system startup links for /etc/init.d/influxdb ...
       /etc/rc0.d/K20influxdb
       /etc/rc1.d/K20influxdb
       /etc/rc2.d/S20influxdb
       /etc/rc3.d/S20influxdb
       /etc/rc4.d/S20influxdb
       /etc/rc5.d/S20influxdb
       /etc/rc6.d/K20influxdb
     Adding system startup for /etc/init.d/influxdb ...
       /etc/rc0.d/K20influxdb -> ../init.d/influxdb
       /etc/rc1.d/K20influxdb -> ../init.d/influxdb
       /etc/rc6.d/K20influxdb -> ../init.d/influxdb
       /etc/rc2.d/S20influxdb -> ../init.d/influxdb
       /etc/rc3.d/S20influxdb -> ../init.d/influxdb
       /etc/rc4.d/S20influxdb -> ../init.d/influxdb
       /etc/rc5.d/S20influxdb -> ../init.d/influxdb
    $ while sleep 1; do netstat -tn|grep TIME_WAIT|wc --lines; done
    9
    9
    9
    9
    9
    9
    9
    9
    9^C
    $ sudo service influxdb start
    Starting the process influxd [ OK ]
    influxd process was started [ OK ]
    $ while sleep 1; do netstat -tn|grep TIME_WAIT|wc --lines; done
    10
    10
    10
    14
    18
    22
    31
    37
    67
    94
    128
    177
    236
    305
    353
    497
    632
    787
    1017
    1216
    1301
    1561
    1830
    2164
    2508
    2844
    3300
    3811
    4187
    4642
    4810
    5268
    5618
    5789
    6173
    6631
    6824
    7183
    7561
    7995
    8270
    8665
    9169
    9362
    9758
    10201
    10501
    10835
    11174
    11585
    11788
    12162
    12607
    12933
    13094
    13462
    13919
    14122
    14624
    14887
    15219
    15478
    15777
    16316
    16704
    16958
    17282
    17709
    18158
    18377
    18796
    19206
    18819
    19038
    19453
    19877
    20282
    20537
    20895
    21334
    21765
    22012
    22383
    22799
    21435
    21612
    22039
    22415
    22813
    22995
    23408
    23832
    24245
    24475
    25017
    25276
    25880
    23466
    23677
    24010
    24478
    24930
    25109
    25577
    25988
    25998
    25998
    25998
    23859
    24946
    24947
    24946
    24946
    24946
    24946
    24946
    24946
    22433
    22433
    22433
    22435
    22435
    22435
    22436
    23256
    20947
    21477
    21476
    21494
    21476
    21476
    21476
    19259
    22059
    23230
    23880
    24266
    24744
    24911
    24943
    24943
    24943
    24943
    21532
    24605
    24949
    25462
    25796
    25982
    25979
    25979
    25979
    25979
    25979
    23224
    23898
    25112
    25112
    25112
    25112
    25119
    25119
    23754
    25129
    25129
    25129
    25129
    25136
    25129
    25129
    23956
    23375
    23406
    23375
    23375
    23375
    23376
    23376
    23376
    23376
    23374
    23375
    23374
    23374
    22713
    22713
    22712
    22762
    22714
    23329
    23329
    17689
    20578
    20795
    21437
    21946
    22458
    22602^C
$

**Comment by akaihola** [comment] 2015-04-16 11:06
Maybe this is relevant: [Can’t create new network sockets? Maybe it isn’t user limits…](https://paperairoplane.net/?p=556) (from the blog of Oliver Hookins and Angela Collins)

**Comment by akaihola** [comment] 2015-04-16 11:33
After a rebot and InfluxDB reinstall, the TIME_WAIT socket count didn't start going up until I started to write data. When writing, I the number went through the roof again, and I saw this in `/var/log/influxdb/influxd.log`:

    [srvr] 2015/04/16 14:29:50 broker cq: error hitting data node: http://localhost:8086: Post http://localhost:8086/data/process_continuous_queries: net/http: request canceled while waiting for connection
    [srvr] 2015/04/16 14:30:04 broker cq: error hitting data node: http://localhost:8086: Post http://localhost:8086/data/process_continuous_queries: read tcp 127.0.0.1:8086: use of closed network connection
    [srvr] 2015/04/16 14:30:08 broker cq: error hitting data node: http://localhost:8086: Post http://localhost:8086/data/process_continuous_queries: read tcp 127.0.0.1:8086: use of closed network connection
    [srvr] 2015/04/16 14:30:25 broker cq: error hitting data node: http://localhost:8086: Post http://localhost:8086/data/process_continuous_queries: dial tcp 127.0.0.1:8086: cannot assign requested address

**Comment by toddboom** [comment] 2015-04-16 16:14
@akaihola I think we know what is causing this and should have an fix for rc26.

**Comment by spynode** [comment] 2015-05-07 13:56
With Graphite database configured to receive metrics in pretty random format e.g. env3.server6.app.internal.socket.latency.count (we have many different metrics with many different names, but no naming pattern which would resemble key.value pattern), with standart InfluxDB setting # name-separator = "-", metrics were not received and in logs there were reported errors: 

[graphite] 2015/05/06 12:08:47 unable to parse data: received "carbon.relays.idbtest.destinations.10_30_5_76:2003.wallTime_us" which doesn't conform to format of key.value.key.value.name or name 

After changing InfluxDB setting to name-separator = " ", InfluxDB can receive data. Problem arises when we try to query InfluxDB for data.
With query like 'select * from "carbon.relays.idbtest.destinations.10_30_5_76:2003.wallTime_us" limit 150', data is returned, but after a moment, CPU sys load goes up to 85% on the machine and we see following in InfluxDB log (several per second, could be on each received metric):
[graphite] 2015/05/07 12:39:40 failed to write data point to database "graphite": do: Post http://localhost:8086/messaging/messages?topicID=1&type=128: dial tcp 127.0.0.1:8086: cannot assign
 requested address

InfluxDB still responds to queries and returns data, but is slower and whole system is under serious load until InfluxDB restart.
Queries with other metric names without colons or other special symbols result in same state.
We are using InfluxDB 0.8.8 with same metrics without said issues.

**Comment by consense** [comment] 2015-05-27 06:12
Seeing the same behavior with rc31. reverting to rc30 gets rid of the problem

**Comment by kpweiler** [comment] 2015-05-28 14:25
+1

Having the same issue with rc31 (influxdb-0.9.0_rc31-1.x86_64.rpm)

**Comment by ShivanKaul** [comment] 2015-06-01 22:46
+1, reverting to rc30 fixed it.

**Comment by lokeshverizon** [comment] 2015-06-03 19:44
We are seeing client connection open around 24,863. Hence influx can not accept more connections. Is there anyway to increase the conenction limits.

**Comment by toddboom** [comment] 2015-06-05 19:52
I'm fairly certain this will be fixed in RC32 later today. In an attempt to keep the issue list clean for v0.9.0, I'm going to close this out for now, but let me know if it reappears.

**Comment by jshamash** [comment] 2015-06-09 19:12
+1, I am having this same issue with rc32. Running tests against Influx, everything works fine up to a point and then I get:
`[srvr] 2015/06/09 15:05:09 broker cq: error hitting data node: http://localhost:8086: Post http://localhost:8086/data/process_continuous_queries: read tcp 127.0.0.1:8086: use of closed network connection`

**Comment by lokeshverizon** [comment] 2015-06-13 06:41
@toddboom, what is the status of this? This seems to be very common problem if we have burst of input.

**Comment by beckettsean** [comment] 2015-06-15 17:59
@lokeshverizon are you experiencing this issue with 0.9.0 final? What OS? How did you install?

**Comment by beckettsean** [comment] 2015-06-16 22:21
We cannot reproduce this against 0.9.0 final. Closing issue until there are repro steps against 0.9.0

**Closed by beckettsean** 2015-06-16 22:21 UTC
Labels: category/internal
