### ISSUE TITLE
[0.9.3-rc2] huge performance loss after upgrade

### ISSUE THREAD

**Issue by thecodeassassin** [influxdb/influxdb#3825] opened 2015-08-25 08:49 UTC
After we upgraded to influxdb 0.9.3 we are experiencing a huge drop in performance when writing points. It takes (on average) about 10-15 seconds (sometimes 2-3 minutes) before the metrics show up in the database.

*Data:*
```
instance,host=server01,region=us-west cpucount=10i,free=1i 1440490134693504482
instance,host=server01,region=us-west cpucount=10i,free=2i 1440490134696936829
```

*Retention policy*
```
  [0] =>
  array(4) {
    'name' =>
    string(7) "default"
    'duration' =>
    string(1) "0"
    'replicaN' =>
    int(1)
    'default' =>
    bool(false)
  }
  [1] =>
  array(4) {
    'name' =>
    string(4) "test"
    'duration' =>
    string(7) "24h0m0s"
    'replicaN' =>
    int(1)
    'default' =>
    bool(true)
  }

```

*Log entry:*
[http] 2015/08/25 10:08:00 10.4.28.32 - - [25/Aug/2015:10:08:00 +0200] POST /write?db=test123&precision=n HTTP/1.1 204 0 - GuzzleHttp/6.0.2 curl/7.35.0 PHP/5.5.9-1ubuntu4.11 6725d0ba-4b00-11e5-81b0-000000000000 1.732971ms

We query influxdb from the CLI client, also tried queries via HTTP get.

**Comment by pauldix** [comment] 2015-08-25 13:48
How are you writing the data? How are you querying it? This is definitely not something we're seeing on this build.

**Comment by thecodeassassin** [comment] 2015-08-25 13:51
We are writing the data through the API (line protocol) and also tried to write it via UDP. Same result. 

We query using the CLI tool but also tried HTTP get.

**Comment by pauldix** [comment] 2015-08-25 13:51
can you show some sample queries? Is it possible that your timestamps are in the future?

**Comment by pauldix** [comment] 2015-08-25 23:21
Also, did you start with a fresh database or is this an upgrade from 0.9.2?

**Comment by thecodeassassin** [comment] 2015-08-26 11:41
It's a newly created database. Here are some of the queries we used:

HTTP post:
http://10.0.1.15/write?db=test123&precision=n

instance,host=server01,region=us-west cpucount=10i,free=1i,test="ZZ",bool=false 1440574049888475353
instance,host=server01,region=us-west cpucount=10i,free=2i,test="BB",bool=true 1440574049891246978

the timestamps are the current timestamps, not set in the future.

**Comment by pauldix** [comment] 2015-08-26 11:44
I'm at a loss on this. There's another person reporting something similar to this, but I can't reproduce it. And this kind of failure should trigger many failures in our test suite. Can you give exact steps to repro? A script maybe?

**Comment by dgnorton** [comment] 2015-08-26 15:26
I also cannot reproduce this.  If I insert the two points listed above using the CLI and then immediately do `select * from instance`, it returns both points.

**Comment by pauldix** [comment] 2015-08-26 15:53
Can you try again with RC3 released last night? There was one query bug in there that might have thrown things off. See #3829. Closing for now, please re-open if you see this again.

**Closed by pauldix** 2015-08-26 15:53 UTC
Labels: category/performance, category/writes
