### ISSUE TITLE
Influxdb time value on points

### ISSUE THREAD

**Issue by anudharm** [influxdb/influxdb#4458] opened 2015-10-15 16:58 UTC
I am using 9.4.2 cluster and trying to write points using Influxdb go client. The points are written with time values like "1970-01-01T00:00:01.44492616Z" though I set the UTC time in the Point Struct.
What is needed?

**Comment by beckettsean** [comment] 2015-10-15 17:57
duplicate of https://github.com/influxdb/influxdb/issues/4281

**Closed by beckettsean** 2015-10-15 17:57 UTC
