### ISSUE TITLE
Invalid query crashes

### ISSUE THREAD

**Issue by tsailiming** [influxdb/influxdb#4352] opened 2015-10-07 06:11 UTC
2015/10/07 14:09:17 InfluxDB starting, version 0.9.4.1, branch 0.9.4, commit c4f85f84765e27bfb5e58630d0dea38adeacf543
2015/10/07 14:09:17 Go version go1.5, GOMAXPROCS set to 2

[query] 2015/10/07 14:03:01 SELECT end_time - time FROM "data"."default".sensor_anomalies WHERE time > now() - 5m
panic: runtime error: index out of range

goroutine 419048 [running]:
github.com/influxdb/influxdb/influxql.newEchoProcessor.func1(0xc821d27e40, 0x2, 0x2, 0x9bb980, 0xc82013aec0)
	/tmp/build/src/github.com/influxdb/influxdb/influxql/result.go:151 +0x42
github.com/influxdb/influxdb/influxql.newBinaryExprEvaluator.func2(0xc821d27e40, 0x2, 0x2, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/influxql/result.go:182 +0xb3
github.com/influxdb/influxdb/tsdb.processForMath(0xc82002c050, 0x1, 0x1, 0xc820348000, 0x56, 0x80, 0x0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/executor.go:989 +0x44c
github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).processValues(0xc82121a300, 0xc82076a000, 0x56, 0x2710, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/executor.go:882 +0xdb1
github.com/influxdb/influxdb/tsdb.(*limitedRowWriter).Flush(0xc82121a300)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/executor.go:783 +0xb5
github.com/influxdb/influxdb/tsdb.(*SelectExecutor).executeRaw(0xc821cf29c0, 0xc820440840)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/executor.go:251 +0x52b
created by github.com/influxdb/influxdb/tsdb.(*SelectExecutor).Execute
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/executor.go:94 +0xa1

goroutine 1 [chan receive, 1173 minutes]:
main.(*Main).Run(0xc82004ff10, 0xc82000a060, 0x4, 0x4, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/main.go:91 +0xa16
main.main()
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/main.go:42 +0x29b

goroutine 17 [syscall, 1173 minutes, locked to thread]:
runtime.goexit()
	/home/philip/.gvm/gos/go1.5/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall, 1173 minutes]:
os/signal.loop()
	/home/philip/.gvm/gos/go1.5/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/home/philip/.gvm/gos/go1.5/src/os/signal/signal_unix.go:28 +0x37

goroutine 19 [IO wait, 1173 minutes]:
net.runtime_pollWait(0x7f689f5c12c8, 0x72, 0xc8200101b0)
	/home/philip/.gvm/gos/go1.5/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820110610, 0x72, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820110610, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8201105b0, 0x0, 0x7f68a63f66f8, 0xc82000f0a0)
	/home/philip/.gvm/gos/go1.5/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc8200fa0e0, 0x0, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc8200fa0e0, 0x0, 0x0, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/tcpsock_posix.go:264 +0x3d
github.com/influxdb/influxdb/tcp.(*Mux).Serve(0xc8200ff440, 0x7f689f5c1450, 0xc8200fa0e0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tcp/mux.go:48 +0x4b
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:345 +0xae9

goroutine 20 [chan receive, 1173 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc8200fa0e8, 0x0, 0x0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/meta.(*raftLayer).Accept(0xc82015fe60, 0x0, 0x0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/meta/store.go:2059 +0x51
github.com/hashicorp/raft.(*NetworkTransport).listen(0xc820110620)
	/tmp/build/src/github.com/hashicorp/raft/net_transport.go:346 +0x79
created by github.com/hashicorp/raft.NewNetworkTransport
	/tmp/build/src/github.com/hashicorp/raft/net_transport.go:138 +0x284

goroutine 21 [select]:
github.com/hashicorp/raft.(*Raft).leaderLoop(0xc82017e000)
	/tmp/build/src/github.com/hashicorp/raft/raft.go:849 +0xcce
github.com/hashicorp/raft.(*Raft).runLeader(0xc82017e000)
	/tmp/build/src/github.com/hashicorp/raft/raft.go:821 +0x936
github.com/hashicorp/raft.(*Raft).run(0xc82017e000)
	/tmp/build/src/github.com/hashicorp/raft/raft.go:602 +0xbb
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.run)-fm()
	/tmp/build/src/github.com/hashicorp/raft/raft.go:252 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc82017e000, 0xc82016e9e0)
	/tmp/build/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
	/tmp/build/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 22 [select, 333 minutes]:
github.com/hashicorp/raft.(*Raft).runFSM(0xc82017e000)
	/tmp/build/src/github.com/hashicorp/raft/raft.go:509 +0x10eb
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runFSM)-fm()
	/tmp/build/src/github.com/hashicorp/raft/raft.go:253 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc82017e000, 0xc82016e9f0)
	/tmp/build/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
	/tmp/build/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 23 [select, 1 minutes]:
github.com/hashicorp/raft.(*Raft).runSnapshots(0xc82017e000)
	/tmp/build/src/github.com/hashicorp/raft/raft.go:1636 +0x493
github.com/hashicorp/raft.(*Raft).(github.com/hashicorp/raft.runSnapshots)-fm()
	/tmp/build/src/github.com/hashicorp/raft/raft.go:254 +0x20
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc82017e000, 0xc82016ea00)
	/tmp/build/src/github.com/hashicorp/raft/state.go:152 +0x44
created by github.com/hashicorp/raft.(*raftState).goFunc
	/tmp/build/src/github.com/hashicorp/raft/state.go:153 +0x4d

goroutine 24 [select, 1173 minutes]:
github.com/influxdb/influxdb/meta.(*localRaft).logLeaderChanges(0xc8200f10e0)
	/tmp/build/src/github.com/influxdb/influxdb/meta/state.go:187 +0x4f5
created by github.com/influxdb/influxdb/meta.(*localRaft).open
	/tmp/build/src/github.com/influxdb/influxdb/meta/state.go:177 +0x1344

goroutine 25 [chan receive, 1173 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc8200fa0f0, 0x0, 0x0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/meta.(*Store).serveExecListener(0xc820114280)
	/tmp/build/src/github.com/influxdb/influxdb/meta/store.go:622 +0xa2
created by github.com/influxdb/influxdb/meta.(*Store).Open
	/tmp/build/src/github.com/influxdb/influxdb/meta/store.go:239 +0x364

goroutine 26 [chan receive, 1173 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc8200fa0f8, 0x0, 0x0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/meta.(*Store).serveRPCListener(0xc820114280)
	/tmp/build/src/github.com/influxdb/influxdb/meta/store.go:726 +0xa2
created by github.com/influxdb/influxdb/meta.(*Store).Open
	/tmp/build/src/github.com/influxdb/influxdb/meta/store.go:242 +0x3b6

goroutine 29 [select, 1173 minutes]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).monitorErrorChan(0xc82010d7a0, 0xc8201066c0)
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:491 +0x145
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:351 +0xc67

goroutine 30 [select]:
github.com/influxdb/influxdb/monitor.(*Monitor).storeStatistics(0xc820104750)
	/tmp/build/src/github.com/influxdb/influxdb/monitor/service.go:333 +0x187c
created by github.com/influxdb/influxdb/monitor.(*Monitor).Open
	/tmp/build/src/github.com/influxdb/influxdb/monitor/service.go:134 +0x30c

goroutine 8 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc820092380, 0xc8202147e0)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:604 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:240 +0x627

goroutine 9 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc820092460, 0xc820214c60)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:604 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:240 +0x627

goroutine 10 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc820092540, 0xc8202152c0)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:604 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:240 +0x627

goroutine 11 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc820092620, 0xc820215920)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:604 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:240 +0x627

goroutine 12 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc820092700, 0xc820215e60)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:604 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:240 +0x627

goroutine 13 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc8200927e0, 0xc82033e6c0)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:604 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:240 +0x627

goroutine 14 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc8200928c0, 0xc82033ee40)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:604 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:240 +0x627

goroutine 15 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc8200929a0, 0xc82033efc0)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:604 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:240 +0x627

goroutine 16 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc820092a80, 0xc82033f500)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:604 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:240 +0x627

goroutine 34 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc820092b60, 0xc82033faa0)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:604 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:240 +0x627

goroutine 35 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc820092c40, 0xc82033ff20)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:604 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:240 +0x627

goroutine 36 [select]:
github.com/influxdb/influxdb/services/hh.(*Service).retryWrites(0xc820124120)
	/tmp/build/src/github.com/influxdb/influxdb/services/hh/service.go:103 +0x314
created by github.com/influxdb/influxdb/services/hh.(*Service).Open
	/tmp/build/src/github.com/influxdb/influxdb/services/hh/service.go:67 +0x210

goroutine 37 [select, 34 minutes]:
github.com/influxdb/influxdb/services/hh.(*Service).expireWrites(0xc820124120)
	/tmp/build/src/github.com/influxdb/influxdb/services/hh/service.go:121 +0x2d1
created by github.com/influxdb/influxdb/services/hh.(*Service).Open
	/tmp/build/src/github.com/influxdb/influxdb/services/hh/service.go:68 +0x232

goroutine 38 [chan receive, 1173 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc8200fa100, 0x0, 0x0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/cluster.(*Service).serve(0xc8201103f0)
	/tmp/build/src/github.com/influxdb/influxdb/cluster/service.go:84 +0xdb
created by github.com/influxdb/influxdb/cluster.(*Service).Open
	/tmp/build/src/github.com/influxdb/influxdb/cluster/service.go:61 +0x135

goroutine 39 [select, 3 minutes]:
github.com/influxdb/influxdb/services/precreator.(*Service).runPrecreation(0xc8200fef80)
	/tmp/build/src/github.com/influxdb/influxdb/services/precreator/service.go:75 +0x44f
created by github.com/influxdb/influxdb/services/precreator.(*Service).Open
	/tmp/build/src/github.com/influxdb/influxdb/services/precreator/service.go:53 +0x21f

goroutine 40 [chan receive, 1173 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc8200fa108, 0x0, 0x0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/services/snapshotter.(*Service).serve(0xc8200f0a50)
	/tmp/build/src/github.com/influxdb/influxdb/services/snapshotter/service.go:75 +0xa9
created by github.com/influxdb/influxdb/services/snapshotter.(*Service).Open
	/tmp/build/src/github.com/influxdb/influxdb/services/snapshotter/service.go:48 +0x130

goroutine 41 [chan receive, 1173 minutes]:
github.com/influxdb/influxdb/tcp.(*listener).Accept(0xc8200fa110, 0x0, 0x0, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tcp/mux.go:129 +0x6f
github.com/influxdb/influxdb/services/copier.(*Service).serve(0xc8200ff000)
	/tmp/build/src/github.com/influxdb/influxdb/services/copier/service.go:78 +0xa9
created by github.com/influxdb/influxdb/services/copier.(*Service).Open
	/tmp/build/src/github.com/influxdb/influxdb/services/copier/service.go:51 +0x130

goroutine 42 [IO wait, 1173 minutes]:
net.runtime_pollWait(0x7f689f5c1208, 0x72, 0xc8200101b0)
	/home/philip/.gvm/gos/go1.5/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82038f100, 0x72, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82038f100, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82038f0a0, 0x0, 0x7f68a63f66f8, 0xc820424a00)
	/home/philip/.gvm/gos/go1.5/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc82002caa8, 0x455470, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc82002caa8, 0x0, 0x0, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/tcpsock_posix.go:264 +0x3d
net/http.(*Server).Serve(0xc820440480, 0x7f689f5c1450, 0xc82002caa8, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1887 +0xb3
net/http.Serve(0x7f689f5c1450, 0xc82002caa8, 0x7f68a63ff250, 0xc820422d40, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1765 +0x85
github.com/influxdb/influxdb/services/admin.(*Service).serve(0xc8200f0b40)
	/tmp/build/src/github.com/influxdb/influxdb/services/admin/service.go:107 +0x12f
created by github.com/influxdb/influxdb/services/admin.(*Service).Open
	/tmp/build/src/github.com/influxdb/influxdb/services/admin/service.go:70 +0x491

goroutine 43 [select]:
github.com/influxdb/influxdb/services/continuous_querier.(*Service).backgroundLoop(0xc820124240)
	/tmp/build/src/github.com/influxdb/influxdb/services/continuous_querier/service.go:192 +0x565
created by github.com/influxdb/influxdb/services/continuous_querier.(*Service).Open
	/tmp/build/src/github.com/influxdb/influxdb/services/continuous_querier/service.go:126 +0x2a4

goroutine 44 [IO wait]:
net.runtime_pollWait(0x7f689f5c1148, 0x72, 0xc8200101b0)
	/home/philip/.gvm/gos/go1.5/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82038f170, 0x72, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82038f170, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82038f110, 0x0, 0x7f68a63f66f8, 0xc821d260c0)
	/home/philip/.gvm/gos/go1.5/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc82002cab0, 0xc82045edc0, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc82002cab0, 0x0, 0x0, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/tcpsock_posix.go:264 +0x3d
net/http.(*Server).Serve(0xc820440540, 0x7f689f5c1450, 0xc82002cab0, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1887 +0xb3
net/http.Serve(0x7f689f5c1450, 0xc82002cab0, 0x7f68a63ff278, 0xc820101100, 0x0, 0x0)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1765 +0x85
github.com/influxdb/influxdb/services/httpd.(*Service).serve(0xc820106b40)
	/tmp/build/src/github.com/influxdb/influxdb/services/httpd/service.go:133 +0x6e
created by github.com/influxdb/influxdb/services/httpd.(*Service).Open
	/tmp/build/src/github.com/influxdb/influxdb/services/httpd/service.go:101 +0x6ca

goroutine 45 [select, 3 minutes]:
github.com/influxdb/influxdb/services/retention.(*Service).deleteShardGroups(0xc8200f0cd0)
	/tmp/build/src/github.com/influxdb/influxdb/services/retention/service.go:69 +0x351
created by github.com/influxdb/influxdb/services/retention.(*Service).Open
	/tmp/build/src/github.com/influxdb/influxdb/services/retention/service.go:45 +0x1b4

goroutine 46 [select, 3 minutes]:
github.com/influxdb/influxdb/services/retention.(*Service).deleteShards(0xc8200f0cd0)
	/tmp/build/src/github.com/influxdb/influxdb/services/retention/service.go:102 +0x7a0
created by github.com/influxdb/influxdb/services/retention.(*Service).Open
	/tmp/build/src/github.com/influxdb/influxdb/services/retention/service.go:46 +0x1d9

goroutine 47 [chan receive, 1173 minutes]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Server).startServerReporting(0xc82010d7a0)
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:442 +0x1eb
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Server).Open.func1
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/server.go:378 +0x1265

goroutine 48 [select, 1173 minutes]:
github.com/influxdb/influxdb/cmd/influxd/run.(*Command).monitorServerErrors(0xc820100200)
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:138 +0x2c5
created by github.com/influxdb/influxdb/cmd/influxd/run.(*Command).Run
	/tmp/build/src/github.com/influxdb/influxdb/cmd/influxd/run/command.go:120 +0xeeb

goroutine 49 [select, 1173 minutes, locked to thread]:
runtime.gopark(0xd19ec8, 0xc820443728, 0xbd5940, 0x6, 0x431018, 0x2)
	/home/philip/.gvm/gos/go1.5/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc820443728, 0x0, 0x18)
	/home/philip/.gvm/gos/go1.5/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc820443728)
	/home/philip/.gvm/gos/go1.5/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/home/philip/.gvm/gos/go1.5/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
	/home/philip/.gvm/gos/go1.5/src/runtime/asm_amd64.s:1696 +0x1

goroutine 419046 [chan receive]:
github.com/influxdb/influxdb/services/httpd.(*Handler).serveQuery(0xc820101100, 0x7f68a63ff5e8, 0xc821d26180, 0xc820116460, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/services/httpd/handler.go:286 +0xc2c
github.com/influxdb/influxdb/services/httpd.(*Handler).(github.com/influxdb/influxdb/services/httpd.serveQuery)-fm(0x7f68a63ff5e8, 0xc821d26180, 0xc820116460, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/services/httpd/handler.go:98 +0x48
github.com/influxdb/influxdb/services/httpd.authenticate.func1(0x7f68a63ff5e8, 0xc821d26180, 0xc820116460)
	/tmp/build/src/github.com/influxdb/influxdb/services/httpd/handler.go:673 +0x70
net/http.HandlerFunc.ServeHTTP(0xc820168a20, 0x7f68a63ff5e8, 0xc821d26180, 0xc820116460)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.gzipFilter.func1(0x7f68a63ff510, 0xc821d26140, 0xc820116460)
	/tmp/build/src/github.com/influxdb/influxdb/services/httpd/handler.go:734 +0x2af
net/http.HandlerFunc.ServeHTTP(0xc820168a40, 0x7f68a63ff510, 0xc821d26140, 0xc820116460)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.versionHeader.func1(0x7f68a63ff510, 0xc821d26140, 0xc820116460)
	/tmp/build/src/github.com/influxdb/influxdb/services/httpd/handler.go:743 +0xc0
net/http.HandlerFunc.ServeHTTP(0xc820168a60, 0x7f68a63ff510, 0xc821d26140, 0xc820116460)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.cors.func1(0x7f68a63ff510, 0xc821d26140, 0xc820116460)
	/tmp/build/src/github.com/influxdb/influxdb/services/httpd/handler.go:776 +0x328
net/http.HandlerFunc.ServeHTTP(0xc820168a80, 0x7f68a63ff510, 0xc821d26140, 0xc820116460)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.requestID.func1(0x7f68a63ff510, 0xc821d26140, 0xc820116460)
	/tmp/build/src/github.com/influxdb/influxdb/services/httpd/handler.go:786 +0x15d
net/http.HandlerFunc.ServeHTTP(0xc820168aa0, 0x7f68a63ff510, 0xc821d26140, 0xc820116460)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.logging.func1(0x7f68a63ff510, 0xc821d26120, 0xc820116460)
	/tmp/build/src/github.com/influxdb/influxdb/services/httpd/handler.go:794 +0x10b
net/http.HandlerFunc.ServeHTTP(0xc820168ac0, 0x7f68a63ff510, 0xc821d26120, 0xc820116460)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1422 +0x3a
github.com/influxdb/influxdb/services/httpd.recovery.func1(0x7f689f5c1d50, 0xc8200caa50, 0xc820116460)
	/tmp/build/src/github.com/influxdb/influxdb/services/httpd/handler.go:804 +0x114
net/http.HandlerFunc.ServeHTTP(0xc820168ae0, 0x7f689f5c1d50, 0xc8200caa50, 0xc820116460)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1422 +0x3a
github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc8200fa090, 0x7f689f5c1d50, 0xc8200caa50, 0xc820116460)
	/tmp/build/src/github.com/bmizerany/pat/mux.go:109 +0x244
github.com/influxdb/influxdb/services/httpd.(*Handler).ServeHTTP(0xc820101100, 0x7f689f5c1d50, 0xc8200caa50, 0xc820116460)
	/tmp/build/src/github.com/influxdb/influxdb/services/httpd/handler.go:172 +0x357
net/http.serverHandler.ServeHTTP(0xc820440540, 0x7f689f5c1d50, 0xc8200caa50, 0xc820116460)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8200ca6e0)
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/home/philip/.gvm/gos/go1.5/src/net/http/server.go:1910 +0x3f6

goroutine 272721 [select]:
github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).autoflusher(0xc820092000, 0xc8204406c0)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:604 +0x567
created by github.com/influxdb/influxdb/tsdb/engine/wal.(*Log).Open
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/engine/wal/wal.go:240 +0x627

goroutine 419047 [chan receive]:
github.com/influxdb/influxdb/tsdb.(*QueryExecutor).executeSelectStatement(0xc8200f07d0, 0x0, 0xc82121a000, 0xc820440720, 0x2710, 0x0, 0x0)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/query_executor.go:285 +0xeb
github.com/influxdb/influxdb/tsdb.(*QueryExecutor).ExecuteQuery.func1(0xc821d26280, 0xc82048607e, 0x4, 0xc8200f07d0, 0xc820440720, 0x2710)
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/query_executor.go:159 +0x757
created by github.com/influxdb/influxdb/tsdb.(*QueryExecutor).ExecuteQuery
	/tmp/build/src/github.com/influxdb/influxdb/tsdb/query_executor.go:213 +0x9b

**Comment by pqvst** [comment] 2015-10-07 12:48
This might be related to: 
https://github.com/influxdb/influxdb/issues/4325

I noticed a similar issue when trying to select the addition of two fields:
SELECT foo + bar FROM test

panic: runtime error: index out of range

**Comment by kostya-sh** [comment] 2015-10-08 13:33
As far as I can see query executor engine at the moment simply doesn't support arithmetic operations on multiple fields. This functionality is not implemented.

A simple way to fix this panic would be to return an error message in case if a select field references multiple variables.

Supporting all kind of arithmetic expressions requires much more work.

**Comment by kostya-sh** [comment] 2015-10-08 13:40
BTW, despite `TestServer_Query_Math` test from server_test.go works only by luck because it selects a single column.

The following query doesn't return anything in value column:

    select cpu, value*2 from cpu_usage_guest

**Comment by otoolep** [comment] 2015-10-16 05:17
Dupe of https://github.com/influxdb/influxdb/issues/4046

**Closed by otoolep** 2015-10-16 05:17 UTC
