### ISSUE TITLE
[0.9.0] Can not recreate a measurement

### ISSUE THREAD

**Issue by indrekj** [influxdb/influxdb#2955] opened 2015-06-12 10:45 UTC
v0.9.0

Replicate:
```sh
#!/bin/sh

echo ">> Recreating the database"
curl -G http://localhost:8086/query --data-urlencode "q=DROP DATABASE foobar"
curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE foobar"

echo
echo ">> Creating a measurement"
curl -XPOST 'http://localhost:8086/write?db=foobar' -d 'cpu,host=serverB,region=us-west value=1.0'

echo
echo ">> Dropping the measurement"
curl -G http://localhost:8086/query --data-urlencode "db=foobar" --data-urlencode "q=DROP MEASUREMENT cpu"

echo
echo ">> Recreating the measurement"
curl -XPOST 'http://localhost:8086/write?db=foobar' -d 'cpu,host=serverA,region=us-west value=1.0'

echo
echo ">> Querying the measurement"
curl -G http://localhost:8086/query --data-urlencode "db=foobar" --data-urlencode "q=SELECT COUNT(value) FROM cpu"
```

Output:
```
>> Recreating the database
{"results":[{}]}{"results":[{}]}
>> Creating a measurement

>> Dropping the measurement
{"results":[{"error":"bucket not found"}]}
>> Recreating the measurement
write failed: database not open
>> Querying the measurement
{"results":[{"error":"unknown field or tag name in select clause: value"}]}%
```

[#2940 might be also related]

**Comment by jonaz** [comment] 2015-06-12 11:18
I have the exact same issue with 0.9.0!

**Comment by beckettsean** [comment] 2015-06-12 21:49
Trivial to reproduce. Here's a slightly easier to parse example using the CLI:

```
> CREATE DATABASE drop_test
> USE drop_test
Using database drop_test
> INSERT cpu,host=serverB,region=us-west value=1.0
> SELECT * FROM cpu
name: cpu
tags: host=serverB, region=us-west
time				value
----				-----
2015-06-12T21:46:13.375960817Z	1

> DROP MEASUREMENT cpu
> INSERT cpu,host=serverB,region=us-west value=1.0
> SELECT * FROM cpu
ERR: select statement must include at least one field or function call
> SHOW MEASUREMENTS
name: measurements
------------------
name
cpu

> SELECT value FROM cpu
ERR: unknown field or tag name in select clause: value
> 
```

**Comment by consense** [comment] 2015-06-16 15:45
+1
very annoying for integration testing of our influxdb reliant code

**Comment by otoolep** [comment] 2015-06-16 16:17
I'm working on the query code at the moment, I'll take a look at this.

**Comment by otoolep** [comment] 2015-06-16 19:09
Should be fixed in 0.9.1 by https://github.com/influxdb/influxdb/pull/3002

**Comment by otoolep** [comment] 2015-06-16 19:11
An effective workaround is to restart the system after dropping the measurement. Once this change goes in, the restart will no longer be required.

**Comment by otoolep** [comment] 2015-06-16 19:18
All fixed.

**Comment by otoolep** [comment] 2015-06-16 19:18
Thanks for the excellent bug report @indrekj

**Closed by otoolep** 2015-06-16 19:18 UTC

**Comment by jacekgrzybowski** [comment] 2015-08-04 14:47
Connected to http://localhost:8086 version 0.9.2
    InfluxDB shell 0.9.2
    > CREATE DATABASE drop_test
    > USE drop_test
    Using database drop_test
    > INSERT response_times,server=honolulu value=44.44
    > SELECT * FROM response_times
    name: response_times
    tags: server=honolulu
    time                            value
    ----                            -----
    2015-08-04T14:45:21.546067507Z  44.44

    > DROP MEASUREMENT response_times
    ERR: database not open
    > SELECT * FROM response_times
    ERR: measurement not found: "drop_test"."default".response_times

@beckettsean I reproduced your steps as I encountered this error in my unit tests, I get `database not open` error while attempting to drop measurement.

**Comment by KrishnaPG** [comment] 2015-08-30 05:06
Getting the same error in latest version (0.9.3), after dropping a measurement and inserting later.

**Comment by beckettsean** [comment] 2015-08-31 18:32
@KrishnaPG can you please provide the steps to reproduce the issue, both the writes and the queries? I am unable to reproduce this error on 0.9.3:

```
> CREATE DATABASE drop_test1
> USE drop_test1
Using database drop_test1
> INSERT cpu,host=serverB,region=us-west value=1.0
> SELECT * FROM cpu
name: cpu
---------
time				host	region	value
2015-08-31T18:31:58.221415617Z	serverB	us-west	1

> DROP MEASUREMENT cpu
> INSERT cpu,host=serverB,region=us-west value=1.0
> SELECT * FROM cpu
name: cpu
---------
time				host	region	value
2015-08-31T18:32:10.046086765Z	serverB	us-west	1

```
