### ISSUE TITLE
TestBroker_Publish fails intermittently

### ISSUE THREAD

**Issue by corylanou** [influxdb/influxdb#1726] opened 2015-02-25 00:34 UTC
```sh
=== RUN TestBroker_Publish
[raft]  2015/02/24 17:29:00 log pending: waiting for initialization or join
[raft] 127.0.0.1:8080 2015/02/24 17:29:00 log state change: stopped => leader
[raft] 127.0.0.1:8080 2015/02/24 17:29:00 log initialize: promoted to 'leader' with cluster ID 7062665782330877934, log ID 1, term 1
panic: encode: encode header: write /var/folders/l7/3s7z7s1s4n72lvj4w6g_fdmm0000gn/T/influxdb-messaging-014408003/20: bad file descriptor

goroutine 16 [running]:
github.com/influxdb/influxdb/messaging.(*brokerFSM).MustApply(0xc20802e460, 0xc2080a4090)
        github.com/influxdb/influxdb/messaging/_test/_obj_test/broker.go:637 +0x2f7
github.com/influxdb/influxdb/raft.func·008(0x0, 0x0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/raft/log.go:1216 +0xebb
github.com/influxdb/influxdb/raft.(*Log).applier(0xc208082000, 0xc20800aba0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/raft/log.go:1224 +0x1bf
created by github.com/influxdb/influxdb/raft.(*Log).Open
        /Users/corylanou/go/src/github.com/influxdb/influxdb/raft/log.go:276 +0x55e

goroutine 1 [chan receive]:
testing.RunTests(0x42a2b8, 0x539740, 0x31, 0x31, 0x53c701)
        /usr/local/Cellar/go/1.4/libexec/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc20802e2d0, 0x543b40)
        /usr/local/Cellar/go/1.4/libexec/src/testing/testing.go:485 +0x6c
main.main()
        github.com/influxdb/influxdb/messaging/_test/_testmain.go:208 +0x291

goroutine 15 [runnable]:
syscall.Syscall(0x6, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/syscall/asm_darwin_amd64.s:20 +0x5
syscall.Close(0x4, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/syscall/zsyscall_darwin_amd64.go:402 +0x55
os.(*file).close(0xc20803db90, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/os/file_unix.go:106 +0x6d
os.(*File).Close(0xc20803a2c0, 0x0, 0x0)
        /usr/local/Cellar/go/1.4/libexec/src/os/file_unix.go:98 +0x61
github.com/influxdb/influxdb/messaging.(*topic).Close(0xc20803d740, 0x0, 0x0)
        github.com/influxdb/influxdb/messaging/_test/_obj_test/broker.go:852 +0x5d
github.com/influxdb/influxdb/messaging.(*Broker).closeTopics(0xc20802e460)
        github.com/influxdb/influxdb/messaging/_test/_obj_test/broker.go:141 +0x91
github.com/influxdb/influxdb/messaging.(*Broker).close(0xc20802e460, 0x0, 0x0)
        github.com/influxdb/influxdb/messaging/_test/_obj_test/broker.go:129 +0xad
github.com/influxdb/influxdb/messaging.(*Broker).Close(0xc20802e460, 0x0, 0x0)
        github.com/influxdb/influxdb/messaging/_test/_obj_test/broker.go:116 +0x7f
github.com/influxdb/influxdb/messaging_test.(*Broker).Close(0xc20803a058)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/messaging/broker_test.go:279 +0x6f
github.com/influxdb/influxdb/messaging_test.TestBroker_Publish(0xc208066090)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/messaging/broker_test.go:117 +0xcf4
testing.tRunner(0xc208066090, 0x539788)
        /usr/local/Cellar/go/1.4/libexec/src/testing/testing.go:447 +0xbf
created by testing.RunTests
        /usr/local/Cellar/go/1.4/libexec/src/testing/testing.go:555 +0xa8b

goroutine 18 [runnable]:
github.com/influxdb/influxdb/raft.(*Log).leaderLoop(0xc208082000, 0xc20800aba0, 0x0)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/raft/log.go:879 +0x53d
github.com/influxdb/influxdb/raft.(*Log).stateLoop(0xc208082000, 0xc20800aba0, 0x3)
        /Users/corylanou/go/src/github.com/influxdb/influxdb/raft/log.go:664 +0x28f
created by github.com/influxdb/influxdb/raft.(*Log).startStateLoop
        /Users/corylanou/go/src/github.com/influxdb/influxdb/raft/log.go:630 +0x6c

goroutine 28 [chan receive]:
github.com/influxdb/influxdb/messaging.(*Replica).WriteTo(0xc208036e40, 0x712280, 0xc208010a10, 0xc2080187b0, 0x0, 0x0)
        github.com/influxdb/influxdb/messaging/_test/_obj_test/broker.go:1107 +0x778
github.com/influxdb/influxdb/messaging_test.func·001()
        /Users/corylanou/go/src/github.com/influxdb/influxdb/messaging/broker_test.go:74 +0x9d
created by github.com/influxdb/influxdb/messaging_test.TestBroker_Publish
        /Users/corylanou/go/src/github.com/influxdb/influxdb/messaging/broker_test.go:77 +0x720
exit status 2
FAIL    github.com/influxdb/influxdb/messaging  0.188s
```

**Comment by corylanou** [comment] 2015-02-25 00:35
@benbjohnson this is on the current master branch

**Comment by otoolep** [comment] 2015-02-25 00:43
I've seen this too, rarely.

**Comment by otoolep** [comment] 2015-02-26 08:49
Dupe of issue #1592.

**Comment by beckettsean** [comment] 2015-04-20 22:43
Closed per @toddboom

**Closed** 2015-04-20 22:42 UTC
