### ISSUE TITLE
[0.9.4] Cannot query where tag value

### ISSUE THREAD

**Issue by eliperelman** [influxdb/influxdb#4499] opened 2015-10-19 16:21 UTC
Not sure if I'm missing something simple, but I cannot seem to query a particular record that matches a specific field value.

I have this record:

![where time](https://cldup.com/EysviqraY6-1200x1200.png)

I am able to find the record by specifying the time exactly. However, when trying to fetch it via its `revisionId`:

![where revisionId](https://cldup.com/bvpgaLx0fl-1200x1200.png)

Including time in the query doesn't seem to make a difference. Any thoughts? InfluxDB 0.9.4.

**Comment by otoolep** [comment] 2015-10-19 16:24
We need this repro'ed using `curl` to be able to work this issue. That is best for us.

https://github.com/influxdb/influxdb/blob/master/CONTRIBUTING.md#bug-reports

**Comment by eliperelman** [comment] 2015-10-19 16:26
In curl:

```sh
curl -G "$INFLUX_DB/query" -u ***:*** --data-urlencode "db=raptor" --data-urlencode "q=select * from annotation where revisionId = '8204b36ca3d4c5798579f9817c3eaf39ffd2bd64'"
{"results":[{}]}%
```

**Comment by eliperelman** [comment] 2015-10-19 16:27
This is also using the hosted InfluxDB.

**Comment by otoolep** [comment] 2015-10-19 16:30
What we need is:

-- a curl command showing data being input.
-- a curl command showing data being queried, both in its failing and passing state.

**Comment by beckettsean** [comment] 2015-10-19 19:08
@eliperelman what are the results of:

`curl -G "$INFLUX_DB/query" -u ***:*** --data-urlencode "db=raptor" --data-urlencode "q=select * from annotation where revisionId =~ /8204b36ca3d4c5798579f9817c3eaf39ffd2bd64"`?

**Comment by eliperelman** [comment] 2015-10-19 19:53
(n.b. I just realized this field is actually a tag)

@beckettsean as follows:

```sh
curl -G "$INFLUX_DB/query" -u ***:*** --data-urlencode "db=raptor" --data-urlencode "q=select * from annotation where revisionId =~ /8204b36ca3d4c5798579f9817c3eaf39ffd2bd64/"
```

```json
{"results":[{}]}
```

@otoolep I wasn't able to replicate by writing the results into a new series. Here is what I tried:

```sh
curl -X POST "$INFLUX_DB/write?db=raptor" -u ***:*** --data-binary 'annotation_test,branch=master,device=flame-kk,memory=512,test=cold-launch,title=Gaia,revisionId=8204b36ca3d4c5798579f9817c3eaf39ffd2bd64 text="3337e2b5a9f5acc8" 1444686164334000001'

# success
```

```sh
curl -G "$INFLUX_DB/query" -u ***:*** --data-urlencode "db=raptor" --data-urlencode "q=select * from annotation_test where revisionId =~ /8204b36ca3d4c5798579f9817c3eaf39ffd2bd64/"
```

```json
{"results":[{"series":[{"name":"annotation_test","columns":["time","branch","device","memory","revisionId","test","text","title"],"values":[["2015-10-12T21:42:44.334000001Z","master","flame-kk","512","8204b36ca3d4c5798579f9817c3eaf39ffd2bd64","cold-launch","3337e2b5a9f5acc8","Gaia"]]}]}]}
```

```sh
curl -G "$INFLUX_DB/query" -u ***:*** --data-urlencode "db=raptor" --data-urlencode "q=select * from annotation where revisionId =~ /8204b36ca3d4c5798579f9817c3eaf39ffd2bd64/"
```

```json
{"results":[{}]}
```

```sh
curl -G "$INFLUX_DB/query" -u ***:*** --data-urlencode "db=raptor" --data-urlencode "q=select * from annotation where time = '2015-10-12T21:42:44.334000001Z'"
```

```json
{"results":[{"series":[{"name":"annotation","columns":["time","branch","device","memory","revisionId","test","text","title"],"values":[["2015-10-12T21:42:44.334000001Z","master","flame-kk","512","8204b36ca3d4c5798579f9817c3eaf39ffd2bd64","cold-launch","3337e2b5a9f5acc8","Gaia"]]}]}]}
```

**Comment by otoolep** [comment] 2015-10-19 20:02
Perhaps something is going on between the browser and the database API. Using the browser's development tools might help you debug the issue, but this is not an area I know too much about.

**Comment by beckettsean** [comment] 2015-10-19 20:10
@eliperelman Right now regex matching isn't valid against fields, so that's an expected result to the query I proposed. 

In your most recent examples revisionID was written as a tag, so the regex matching did work.

The results from the final query suggest that the exact text stored is `8204b36ca3d4c5798579f9817c3eaf39ffd2bd64`, not something like `"8204b36ca3d4c5798579f9817c3eaf39ffd2bd64"` or `'8204b36ca3d4c5798579f9817c3eaf39ffd2bd64'`, which would confuse the equality.

I'm unable to repro with 0.9.4.2:

```
> insert stringy,foo=bar value="8204b36ca3d4c5798579f9817c3eaf39ffd2bd64"
> select * from stringy
name: stringy
-------------
time				foo	value
2015-10-19T20:09:25.768454642Z	bar	8204b36ca3d4c5798579f9817c3eaf39ffd2bd64

> select * from stringy where value='8204b36ca3d4c5798579f9817c3eaf39ffd2bd64'
name: stringy
-------------
time				foo	value
2015-10-19T20:09:25.768454642Z	bar	8204b36ca3d4c5798579f9817c3eaf39ffd2bd64
```

Is it only this particular point? If more than one point is affected, is it only when querying by that particular field?

**Comment by eliperelman** [comment] 2015-10-20 14:47
Sorry if I wasn't clear in my previous comment, but this is in fact a __tag__, not a __field__. 

@otoolep I replicate this in curl, so not sure how the browser is at play here.

@beckettsean so I went into our tool that generates line protocol to see what it is posting. This is actual data written today:

```
annotation,branch=master,device=flame-kk,memory=512,revisionId=349f91b84b0c7ca2f1de2de1e1e7dc285c0cae06,test=cold-launch,title=Gaia text="0ad8e1e3b51542dc" 1445339320606000001
```

The `revisionId` is written as a tag. Now, I'm going to attempt to use curl to get at this entry:

```sh
curl -G "$INFLUX_DB/query" -u ***:*** --data-urlencode "db=raptor" --data-urlencode "q=select * from annotation where revisionId = '349f91b84b0c7ca2f1de2de1e1e7dc285c0cae06'"
```

```json
{"results":[{}]}
```

So no luck. Now I'm going to try the timestamp:

```sh
curl -G "$INFLUX_DB/query" -u ***:*** --data-urlencode "db=raptor" --data-urlencode "q=select * from annotation where time = '2015-10-20T11:08:40.606000001Z'"
```

```json
{"results":[{"series":[{"name":"annotation","columns":["time","branch","device","memory","revisionId","test","text","title"],"values":[["2015-10-20T11:08:40.606000001Z","master","flame-kk","512","349f91b84b0c7ca2f1de2de1e1e7dc285c0cae06","cold-launch","0ad8e1e3b51542dc","Gaia"]]}]}]}
```

Querying by a different tag (`where memory = '512'`) produces a slew of data, so the other tags seem to be working properly.

**Comment by eliperelman** [comment] 2015-10-20 14:54
Just noticed something: even though the data is being written as tags, the JSON doesn't have a `tags` property, it appears that it is all in `columns` and `values`. When querying another measurement, the data comes back with a `tags` property with the `revisionId` in the correct place.

Is it possible that early on the data was written without tags, switched to tags, and is now stuck in fields? If that is the case, is there a way to convert some of these fields to tags?

**Comment by beckettsean** [comment] 2015-10-20 15:33
@eliperelman I'm puzzled. For one, I have zero issues querying by `revisionID` in my 0.9.4.2 system:

```
> insert annotation,branch=master,device=flame-kk,memory=512,revisionId=349f91b84b0c7ca2f1de2de1e1e7dc285c0cae06,test=cold-launch,title=Gaia text="0ad8e1e3b51542dc" 1445339320606000001

> select * from annotation where revisionId = '349f91b84b0c7ca2f1de2de1e1e7dc285c0cae06'
name: annotation
----------------
time				branch	device		memory	revisionId					test		text			title
2015-10-20T11:08:40.606000001Z	master	flame-kk	512	349f91b84b0c7ca2f1de2de1e1e7dc285c0cae06	cold-launch	0ad8e1e3b51542dc	Gaia
```

Thanks for clarifying that `revisionID` is a tag, I misread your earlier comment. That makes the query result quite puzzling, since the regex should have returned a match.

What are the results of `select * from annotation where revisionId =~ /^82.*/`?

>  When querying another measurement, the data comes back with a tags property with the revisionId in the correct place.

So `revisionID` exists as a tag on a measurement other than `annotation`? Can you query that measurement directly by `revisionID`?

> Just noticed something: even though the data is being written as tags, the JSON doesn't have a tags property, it appears that it is all in columns and values.

I'm doing a little research to see if this is expected behavior or not. 

> Is it possible that early on the data was written without tags, switched to tags, and is now stuck in fields? If that is the case, is there a way to convert some of these fields to tags?

That is not possible. Fields and tags cannot be converted or commingled. They exist in very separate parts of the database.

**Comment by eliperelman** [comment] 2015-10-20 15:43
`select * from annotation where revisionId =~ /^82.*/`

```json
{"results":[{}]}
```

> So revisionID exists as a tag on a measurement other than annotation? Can you query that measurement directly by revisionID?

Yes. The `annotation` measurement will be providing me a lookup of data that isn't stored in other measurements; it provides the data for which `revisionId` is the foreign key.

`show tag keys from annotation`

```json
{"results":[{"series":[{"name":"annotation","columns":["tagKey"],"values":[["branch"],["device"],["memory"],["revisionId"],["test"],["title"]]}]}]}
```

`show tag keys from measure`

``json
{"results":[{"series":[{"name":"measure","columns":["tagKey"],"values":[["branch"],["context"],["device"],["memory"],["metric"],["phase"],["revisionId"],["test"]]}]}]}
```

So I plan on being able to use the `revisionId` from an entry in the `measure` measurement to look up the revision IDs that match that entry in the `annotation` measurement.

> That is not possible. Fields and tags cannot be converted or commingled. They exist in very separate parts of the database.

Makes sense, and confirmed with the `show tag keys` which shows `revisionId` is in fact stored as a tag.

**Comment by eliperelman** [comment] 2015-10-20 15:44
Selecting from a different measurement:

`select * from measure where revisionId = '349f91b84b0c7ca2f1de2de1e1e7dc285c0cae06' limit 1`

```json
{"results":[{"series":[{"name":"measure","columns":["time","branch","context","device","epoch","memory","metric","phase","revisionId","test","value"],"values":[["2015-10-20T11:08:40.606000001Z","master","gallery.gaiamobile.org","flame-kk",1445345016392,"512","mediaEnumerated","coldlaunch","349f91b84b0c7ca2f1de2de1e1e7dc285c0cae06","cold-launch",1695]]}]}]}
```

**Comment by eliperelman** [comment] 2015-10-21 16:38
For most of the annotation records they come in pairs:

`select * from annotation order by desc limit 2`

```json
{
    "results": [
        {
            "series": [
                {
                    "name": "annotation",
                    "columns": [
                        "time",
                        "branch",
                        "device",
                        "memory",
                        "revisionId",
                        "test",
                        "text",
                        "title"
                    ],
                    "values": [
                        [
                            "2015-10-21T16:08:58.000000002Z",
                            "master",
                            "aries",
                            "2048",
                            "8a2cb4b18998639b7c4e48d9ed5cc79979d51e8f",
                            "cold-launch",
                            "d1fec0906e81116d",
                            "Gecko"
                        ],
                        [
                            "2015-10-21T16:08:58.000000001Z",
                            "master",
                            "aries",
                            "2048",
                            "8a2cb4b18998639b7c4e48d9ed5cc79979d51e8f",
                            "cold-launch",
                            "c047bf4f8212ecfc",
                            "Gaia"
                        ]
                    ]
                }
            ]
        }
    ]
}
```

`select * from annotation where revisionId = '8a2cb4b18998639b7c4e48d9ed5cc79979d51e8f'`

```json
{"results":[{}]}
```

`select * from annotation where text = 'c047bf4f8212ecfc'`

```json
{
    "results": [
        {
            "series": [
                {
                    "name": "annotation",
                    "columns": [
                        "time",
                        "branch",
                        "device",
                        "memory",
                        "revisionId",
                        "test",
                        "text",
                        "title"
                    ],
                    "values": [
                        [
                            "2015-10-21T16:08:58.000000001Z",
                            "master",
                            "aries",
                            "2048",
                            "8a2cb4b18998639b7c4e48d9ed5cc79979d51e8f",
                            "cold-launch",
                            "c047bf4f8212ecfc",
                            "Gaia"
                        ]
                    ]
                }
            ]
        }
    ]
}
```

I'm baffled. If someone wants to log into my InfluxDB-hosted instance to see if something is out of the ordinary and you feel we should go that route, I can file a ticket.

**Comment by beckettsean** [comment] 2015-10-22 23:45
@eliperelman I'd love to take a look at the machine. Please do drop a note to support@ and I'll investigate. As of this moment I have no idea what else to ask you, but maybe some idle poking at things will spur an *a ha* moment.

**Comment by eliperelman** [comment] 2015-10-23 00:42
Email sent.

**Comment by gunnaraasen** [comment] 2015-11-10 22:56
Closing in favor of https://github.com/influxdb/influxdb/issues/4630, which has a description of the root cause of this issue.

**Closed by gunnaraasen** 2015-11-10 22:56 UTC
