### ISSUE TITLE
last(value) returns 1970-01-01T00:00:00Z as the time

### ISSUE THREAD

**Issue by prashleo** [influxdb/influxdb#5216] opened 2015-12-23 20:22 UTC
**last(value) doesn't seem to work, below is the example**

**Full list of points in the time series total_objects**

vagrant@scaler-1:~$ curl --insecure -G 'https://scaler-1:8086/query?pretty=true' -u admin:CnxaYmsZQB7APRx --data-urlencode  "db=metrics" --data-urlencode 'q=select  value from total_objects'
{
    "results": [
        {
            "series": [
                {
                    "name": "total_objects",
                    "columns": [
                        "time",
                        "value"
                    ],
                    "values": [
                        [
                            "2015-12-23T19:13:27Z",
                            1
                        ],
                        [
                            "2015-12-23T19:18:26Z",
                            1
                        ],
                        [
                            "2015-12-23T19:23:27Z",
                            1
                        ],
                        [
                            "2015-12-23T19:28:26Z",
                            1
                        ],
                        [
                            "2015-12-23T19:33:27Z",
                            1
                        ],
                        [
                            "2015-12-23T19:38:26Z",
                            1
                        ],
                        [
                            "2015-12-23T19:43:27Z",
                            1
                        ],
                        [
                            "2015-12-23T19:48:26Z",
                            1
                        ]
                    ]
                }
            ]
        }
    ]
=====

**get the latest point from total_objects using order by**

vagrant@scaler-1:~$ curl --insecure -G 'https://scaler-1:8086/query?pretty=true' -u admin:CnxaYmsZQB7APRx --data-urlencode  "db=metrics" --data-urlencode 'q=select  value from total_objects group by machine order by desc limit 1'
{
    "results": [
        {
            "series": [
                {
                    "name": "total_objects",
                    "tags": {
                        "machine": "94b8b1c7-ce7f-46a4-893a-2d7593c1aefb"
                    },
                    "columns": [
                        "time",
                        "value"
                    ],
                    "values": [
                        [
                            **"2015-12-23T19:43:27Z",**
                            1
                        ]
                    ]
                }
            ]
        }
    ]
}
===============

**get the latest point from total_objects using last(value)**

vagrant@scaler-1:~$ curl --insecure -G 'https://scaler-1:8086/query?pretty=true' -u admin:CnxaYmsZQB7APRx --data-urlencode  "db=metrics" --data-urlencode 'q=select  last(value)  from total_objects group by machine order by desc'
{
    "results": [
        {
            "series": [
                {
                    "name": "total_objects",
                    "tags": {
                        "machine": "94b8b1c7-ce7f-46a4-893a-2d7593c1aefb"
                    },
                    "columns": [
                        "time",
                        "last"
                    ],
                    "values": [
                        [
                           **"1970-01-01T00:00:00Z",**
                            1
                        ]
                    ]
                }
            ]
        }
    ]
}

**Comment by beckettsean** [comment] 2015-12-28 19:05
@prashleo what version of the database are you using? This was fixed in 0.9.5: https://github.com/influxdb/influxdb/issues/1577

**Comment by prashleo** [comment] 2015-12-28 19:40
Latest version..0.9.6.1

**Comment by beckettsean** [comment] 2015-12-28 21:20
@rkuchan can you repro on 0.9.6?

**Comment by rkuchan** [comment] 2015-12-28 22:35
I am able to repro on 0.9.6.1. `last()` does return the relevant timestamp, but **not** if you `GROUP BY` a tag. I've encountered this behavior with other functions as well: https://github.com/influxdb/influxdb/issues/4680.

Specifying the tag in the `WHERE` clause works fine: 
```sh
> SELECT last(water_level) FROM h2o_feet WHERE location = 'santa_monica'
name: h2o_feet
--------------
time			        last
2015-09-18T21:42:00Z	4.938

> SELECT last(water_level) FROM h2o_feet WHERE location = 'coyote_creek'
name: h2o_feet
--------------
time			        last
2015-09-18T16:24:00Z	3.235
```

`GROUPing BY` a tag returns epoch 0:
```sh
> SELECT last(water_level) FROM h2o_feet GROUP BY location
name: h2o_feet
tags: location=coyote_creek
time			        last
----			        ----
1970-01-01T00:00:00Z	3.235


name: h2o_feet
tags: location=santa_monica
time			        last
----			        ----
1970-01-01T00:00:00Z	4.938
```

**Comment by prashleo** [comment] 2015-12-28 23:16
So last() and group by cannot be used together?? Is this a  influxdb restriction??

**Comment by beckettsean** [comment] 2015-12-28 23:42
@prashleo, this is an unintentional design limitation, not an intentional design feature. We will address it, soon I hope.

**Comment by beckettsean** [comment] 2015-12-28 23:43
closing as duplicate of https://github.com/influxdb/influxdb/issues/4680, which I updated to reference all selector functions, not just TOP.

**Closed by beckettsean** 2015-12-28 23:43 UTC
Labels: category/functions
