### ISSUE TITLE
Is there any way to auto limit sql result?

### ISSUE THREAD

**Issue by zjian1993** [influxdb/influxdb#3624] opened 2015-08-11 16:16 UTC
We hava used influxdb and someone often write sql without time condition and limit，it run out of server memory and let influxdb service down. I want to know is there any way to let the sql without time condition and limit don't run, or auto add limit in the end of sql?

**Comment by beckettsean** [comment] 2015-08-11 18:54
There is currently no way to monitor, suspend, or terminate a long-running query, other than restarting the database process.

Closing as duplicate of https://github.com/influxdb/influxdb/issues/654, https://github.com/influxdb/influxdb/issues/655, and https://github.com/influxdb/influxdb/issues/675

**Closed by beckettsean** 2015-08-11 18:54 UTC
