### ISSUE TITLE
[0.9.3] High Memory Consumption and weird WAL behavior.

### ISSUE THREAD

**Issue by jhorwit2** [influxdb/influxdb#3967] opened 2015-09-03 01:42 UTC
I started to notice since my upgrade to 0.9.3 that my memory usage has gone up significantly. The box I'm running only has about 10GB of ram, which was never an issue in the past; however, on the new release I notice that memory usage constantly goes up during the day until an OOM at night (current trend). The only way I can fix the memory issue is to clear my WAL directory completely on a restart. 

If I restart influx w/o clearing the wal directory my memory shoots right back up. Shouldn't the WAL be flushing / draining to boltdb? Because that doesn't seem to be the case. I could turn off certain databases and still see the WAL full for it. 

I have also start to notice influx not restarting cleanly when the WAL is large. Influx will start, then just die without anything in the logs. I have noticed this quite a few times and the only solution I have found is to clear the WAL directory.

**Comment by otoolep** [comment] 2015-09-03 02:12
Thanks @jhorwit2 -- what kind of load are you putting on the system? Which input? Are you batching? How many different series?

**Comment by jhorwit2** [comment] 2015-09-03 02:18
The database that has issues gets about 2k points per second across 3 series with a heavy emphasis (probably 75% going to 1 series). The points are batched, sorted, etc. The series have about 5 tags each.

Here is an example point (minus a few other tag fields)

![image](https://cloud.githubusercontent.com/assets/3876739/9649264/7e8424d0-51c0-11e5-9c46-21da83ec3454.png)

**Comment by otoolep** [comment] 2015-09-03 02:21
I suspect you have more than 3 series, I think you mean 3 Measurements, right?

**Comment by jhorwit2** [comment] 2015-09-03 02:22
I also noticed today that the write times progressively get slower as the day progresses. It starts at a normal sub 50ms time and before i turned it off this evening we were at an 800ms mean time with 95% percentile above 1.5s.

And yes, sorry. Long day haha.

**Comment by jhorwit2** [comment] 2015-09-03 02:24
My smaller databases seem unaffected for the most part though as they keep writes below 80ms all day.Those smaller database maybe see 1 point per second.

**Comment by jhorwit2** [comment] 2015-09-03 02:39
When you say `how many series` what do you mean exactly? `time series` and `measurement` are synonymous depending on which version of the docs you remember lol. You mean how many metric points?

**Comment by otoolep** [comment] 2015-09-03 02:45
Everything is specifically defined here:

https://influxdb.com/docs/v0.9/concepts/glossary.html

**Comment by jhorwit2** [comment] 2015-09-03 03:02
Each point has 4 tags (releaseVersion, edge, valid, browser). Some quick looking I have `216, 2, 2, 126` possible tag values for each, respectively. Which leaves us with ~100k possible combinations.

**Comment by olivierHa** [comment] 2015-09-03 13:20
I got the same behaviour.
Since I've upgraded to 0.9.3, influxdb eats "memory" 
Using 0.9.2, "only"  1 go real memory was used. Now it takes more than 4Go with the exact same plugin/traffic.

**Comment by Jhors2** [comment] 2015-09-03 17:41
+1, We have about 700K+ series, with 20 or so measurements.  This seems like a memory leak.  We have 64GB of RAM in our box.  It takes about 12 hours to completely run out of memory then the process is OOM killed by the system.

**Comment by benbjohnson** [comment] 2015-09-04 21:12
I pushed in a Bolt fix (https://github.com/boltdb/bolt/pull/413) where the last write transaction's pages would linger. I don't think this is the cause of the memory leak but it'll make the heap profile output clearer. That should be in the [nightly build](https://influxdb.com/download/#version-0-9-4-nightly) tonight.

@jhorwit2 @olivierHa @Jhors2 Can you grab a heap profile while it's running with high memory consumption?

You'll need `go` installed and then run:

```sh
$ go tool pprof  /path/to/influxd http://localhost:8086/debug/pprof/heap
```

(Change `/path/to/influxd` to the actual path of your `influxd` binary)

You should see a message like this:

```
Fetching profile from http://localhost:8086/debug/pprof/heap
Saved profile in /home/yourname/pprof/pprof.influxd.localhost:8086.inuse_objects.inuse_space.005.pb.gz
Entering interactive mode (type "help" for commands)
```

Then at the `(pprof)` prompt type "`web`" and hit enter:

```
(pprof) web
```

It should pop up an SVG graph in your browser. You may need to install graphviz first if you don't already have it installed. Then can you post the SVG? That should give us some more insight.

**Comment by otoolep** [comment] 2015-09-04 21:18
Also, when https://github.com/influxdb/influxdb/pull/3999 is merged, Go memory usage will be written once-a-minute to the system, in a database called `_internal`. This will allow us to easily track memory usage of the system. The data returned can be plotted by all the normal processes.

**Comment by lokeshverizon** [comment] 2015-09-06 19:40
I also see huge memory leaks when writing around 10k msg per second. Memory shoots to 8GB and influxdb dies as I have set upper limit of my app to 8GB. 


2015/09/06 19:23:47 InfluxDB starting, version 0.9, branch unknown, commit unknown
2015/09/06 19:23:47 Go version go1.4.1, GOMAXPROCS set to 1
2015/09/06 19:23:47 Using configuration at: /etc/opt/influxdb/config.toml
[monitor] 2015/09/06 19:23:47 Starting monitor system
[monitor] 2015/09/06 19:23:47 'runtime:map[]' registered for monitoring
[metastore] 2015/09/06 19:23:47 Using data dir: /var/opt/influxdb/meta
[metastore] 2015/09/06 19:23:47 Skipping cluster join: already member of cluster: nodeId=1 raftEnabled=true peers=[10.2.22.1:8088]
[store] 2015/09/06 19:23:47 Using data dir: /var/opt/influxdb/data
[wal] 2015/09/06 19:23:47 WAL starting with 30720 ready series size, 0.50 compaction threshold, and 20971520 partition size threshold
[wal] 2015/09/06 19:23:47 WAL writing to /var/opt/influxdb/wal/logging/default/3
[monitor] 2015/09/06 19:23:47 storing statistics in database '_internal', interval 5m0s
[metastore] 2015/09/06 19:23:47 Node at 10.2.22.1:8088 [Follower]
[metastore] 2015/09/06 19:23:49 Node at 10.2.22.1:8088 [Leader]. peers=[10.2.22.1:8088]
[metastore] 2015/09/06 19:23:49 Updated node id=1 hostname=10.2.22.1:8088
[handoff] 2015/09/06 19:24:01 Starting hinted handoff service
[handoff] 2015/09/06 19:24:01 Using data dir: /var/opt/influxdb/hh
[tcp] 2015/09/06 19:24:01 Starting cluster service
[shard-precreation] 2015/09/06 19:24:01 Starting precreation service with check interval of 10m0s, advance period of 30m0s
[snapshot] 2015/09/06 19:24:01 Starting snapshot service
[admin] 2015/09/06 19:24:01 Starting admin service
[admin] 2015/09/06 19:24:01 Listening on HTTP: [::]:8083
[continuous_querier] 2015/09/06 19:24:01 Starting continuous query service
[httpd] 2015/09/06 19:24:01 Starting HTTP service
[httpd] 2015/09/06 19:24:01 Authentication enabled: false
[httpd] 2015/09/06 19:24:01 Listening on HTTP: [::]:8086
[retention] 2015/09/06 19:24:01 Starting retention policy enforcement service with check interval of 10m0s
[run] 2015/09/06 19:24:01 Listening for signals
[wal] 2015/09/06 19:24:14 Flush due to memory. Flushing 1 series with 10375754 points and 1976730707 bytes from partition 4. Compacting 0 series

Killed

**Comment by Jhors2** [comment] 2015-09-08 23:26
@benbjohnson If I were to get the raw text output of the above URL and pass it along could you debug from there?  I can of course give you my proper version number and such.  It's difficult for us to run the commands on our boxes in prod that we can repro this on.

**Comment by sudabon** [comment] 2015-09-09 06:56
I use Bolt fix (boltdb/bolt#413) version above.
Progress of memory consumption still bothers me.

We have 91 measurements and retension policy is only 1h.
So data size is very small, i.e. about 70MB

```
$ sudo du -sk /var/opt/influxdb/
70820	/var/opt/influxdb/
$ sudo du -sk /var/opt/influxdb/wal/
5104	/var/opt/influxdb/wal/
$ sudo du -sk /var/opt/influxdb/data/
65696	/var/opt/influxdb/data/
```

However, Influxd holds about 3G memory.
I suspect influxd leeks memory.
OOM killer will kill this a week later.

```
$ top
Cpu(s):  1.7%us,  0.0%sy,  0.0%ni, 97.8%id,  0.4%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:  12185260k total,  6619100k used,  5566160k free,   275212k buffers
Swap:  2097148k total,   247312k used,  1849836k free,  2583704k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                   
 8847 root      20   0 3028m 2.9g  56m S  9.3 25.3 539:35.08 influxd                                                    
```

I attach the screenshot of pprof SVG file.
Hope this helps

![pprof](https://cloud.githubusercontent.com/assets/140196/9755208/2371a95a-570b-11e5-8177-b7c5a2adec04.png)

**Comment by hajs** [comment] 2015-09-10 13:04
Hello I was experiencing the same while trying to import one week of metrics from an other database into Influx. The memory usage grows continuously. I could see the problem with 0.9.2, 0.9.3 and the daily snapshot from yesterday.

If you provide me your email-address I can point you to my private server where you can download the anonymized data-set to reproduce the problem (220 MB tar.bz2/5.3 GB extracted). The line-protocol-encoded files can be directly imported into Influx with curl.

**Comment by pauldix** [comment] 2015-09-10 18:01
After a bunch of testing, we've determined that the underlying index just can't keep up with the insertion load that the WAL makes possible. To prevent the system from going OOM and dying we're going to put back pressure on the write clients and start failing writes when memory gets too high. See #4066.

We're also working on a massive storage engine upgrade that will fix this. Should be available in the nightlies within a week or two. It will have much better compression and be able to keep up with the write load of the WAL.

More soon...

**Comment by jhorwit2** [comment] 2015-09-10 18:08
So, if I understood that correctly, once memory gets too high it's just going to fail every write instead of OOMing?

**Comment by jhorwit2** [comment] 2015-09-10 18:09
Because from what I have noticed, i could not write to a database for hours and the WAL doesn't get flushed.

**Comment by pauldix** [comment] 2015-09-10 18:13
Right, it's going to fail writes until it is able to flush everything to the index to relieve memory pressure. This will only happen if you're sending more writes than the underlying index can handle.

Before, if you OOM'd and then tried to bring things back up, it would spend a large amount of time reading the WAL from disk. This should limit that a bit since it won't just keep filling up the WAL until it dies.

At least that's the theory. Bolt is going to get removed from the whole system in the next storage engine, which should be testable in a nightly build within a few weeks.

**Comment by jhorwit2** [comment] 2015-09-10 18:23
` Bolt is going to get removed from the whole system in the next storage engine, which should be testable in a nightly build within a few weeks.`

Does that mean a migration?

**Comment by dswarbrick** [comment] 2015-09-10 21:53
This is the second storage backend replacement since the 0.8 series was announced as being EOL. IMHO, this really erodes its credibility as a viable solution for scalable time series metrics.

**Comment by pauldix** [comment] 2015-09-11 02:27
@jhorwit2: No migration will be required, you'll be able to run both in parallel. Older data will still be stored in Bolt. Newer data will be stored in the new engine. Our target is to get the engine out in the 0.9.5 release, but that will depend greatly on how testing goes.

@dswarbrick: To your comment, we went with Bolt because we thought it would be the most stable way to get something that was able to do hot backups, not have problems with the number of file handles and generally work (i.e. stable). We knew we'd be taking a hit on write throughput, but thought it would be good enough.

However, we've found that while it works for a good number of people, a large group have throughput needs that it is just unable to meet. You may be in that group or not, but with people that have higher throughput needs we're seeing very heavy IOPS and there's just no way to solve the problem with Bolt.

In the past 3 months we've added many people to the team. The good news is that we finally have more resources to start building out performance test suites. We're now running write performance tests on every nightly build and we'll be expanding this suite over time. 9 months ago we were 4 people, with not everyone focused on code (for instance I was fundraising then we were hiring). Things are much different today.

I've already been testing a prototype of the new engine and I can tell you that the on disk size and overall throughput are significantly better than either Bolt or the 0.8 release. It should make it into a nightly build in a few weeks.

InfluxDB's credibility as a scalable time series database would be eroded if we simply punted on the hard problem and told anyone with throughput needs higher than what Bolt can handle to go away. That's not what we're doing. We're working on solving the problem to make a time series database that scales better than any other solution out there. This takes time, effort, learning, and occasional missteps. If I knew 18 months ago what I know now, it would already be done.

I've been talking about writing a storage engine for our needs for over a year. Now we're finally getting to that piece of the puzzle. I invite you to test it out as soon as it's available in a nightly build. I think you'll be pleasantly surprised.

**Comment by hajs** [comment] 2015-09-11 06:20
@pauldix: So what is the best practice if a write failure message will be returned? Should the client wait a second or send a smaller chunk?
When I am bulk importing a lot of data will the whole write http-request be disregarded or will only a part of the data be saved?

**Comment by dswarbrick** [comment] 2015-09-11 07:40
@pauldix Thanks Paul, I appreciate your detailed response, and look forward to testing the new storage engine in a few weeks. You can be sure we'll hit it hard ;-)

**Comment by xo4n** [comment] 2015-09-11 09:44
@pauldix might I ask why not keeping leveldb as storage engine as in 0.8.8? what will the new storage engine address better than leveldb? We are still using 0.8.8  with leveldb and we are handling at the moment an incoming traffic of 2.5Mbps, with daily shards of 30GB aprox and a total db size of 3TB.

**Comment by pkittenis** [comment] 2015-09-11 11:18
Many thanks for your detailed explanation Paul - we are eagerly awaiting the new release and will surely test its limits :)

While 0.9 is not quite there yet and performance is a bit poorer compared to 0.8, every subsequent release has increased both performance and stability and the development team has been very engaging and forth coming with reported issues.

@xo4n - I suspect the answer to that is write amplification. Write throughput in 0.8 has been shown to increase linearly with number of incoming metrics eventually saturating the disk subsystem.

FWIW, InfluxDB's implementation of leveldb far exceeded the write performance of other implementations, for example cassandra where a very large cluster is required to get even half the write performance of a single Influxdb 0.8 node.

**Comment by pauldix** [comment] 2015-09-11 14:30
@hajs: The entire write request will be rejected. The client should wait a few seconds and then restart. If you hit a point where writes are getting rejected because its that backed up, it can take as much as 10-30 seconds for it to flush out.

@xo4n: LevelDB won't work for us because it isn't able to do hot backups and the number of file handles it opens up were a problem for a number of users. To make retention policies possible, we have to open up a new underlying database for each block of time. For users that had multiple RPs (then known as shard spaces) and multiple databases, they were exhausting the number of file handles available. In fact, two days ago we had a customer on managed hosting hit that limit.

However, in a delicious bit of irony, the new storage engine looks very much like a LSM Tree (the same type of storage engine as LevelDB). It just has a few modifications that make it custom for our use case of time series data and how we're indexing it. We can also get better compression than you'd get in LevelDB (and thus better compression than what you see in 0.8.8).

@pkittenis: To your comment about write amplification, I've found that isn't the primary concern. The biggest problem we have in the current engine is massive IOPS spikes. I'm fine with writing 5 or 10GB to disk for every 1GB of compressed, indexed storage, as long as it's steady and amortized over time. A steady load of 100-300 IOPS is much better than being really low then spiking in the thousands.

I'll be writing up all the gory details as soon as it's ready for testing in a nightly.

**Comment by jhorwit2** [comment] 2015-09-11 15:10
Is there a ticket tracking the new work?

**Comment by pkittenis** [comment] 2015-09-11 15:18
Was referring to write amplification in the 0.8 series. It's true 0.9 is more heavy on iops with very large spikes, 0.8 had a constant but low iops rate which was great.

**Comment by pauldix** [comment] 2015-09-11 15:28
@jhorwit2 Sure, I just opened #4086.

@pkittenis sure, knew you meant that. I just meant that I think write amplification is better than big IOPS for this use case so we're headed back in that direction :)

Closing this issue out now since it was fixed by #4066, but the real underlying issue is that we need to support higher write throughput. That will be fixed when #4086 is resolved. Please watch and comment on that issue for more.

**Closed by pauldix** 2015-09-11 15:28 UTC
Labels: category/performance, category/writes

**Comment by igorcanadi** [comment] 2015-09-11 16:43
I am really excited to learn more about your new storage engine. It's good to have more people innovating in that space.

Are you still considering having an option of multiple storage engine backends? I think RocksDB could be a viable alternative, especially for users with high write rate. We use RocksDB as a storage for time series data at Facebook.

> LevelDB won't work for us because it isn't able to do hot backups and the number of file handles it opens up were a problem for a number of users.

RocksDB can do hot incremental backups: https://github.com/facebook/rocksdb/wiki/How-to-backup-RocksDB%3F. We also just open sourced our tool for backing up MongoDB+RocksDB: http://blog.parse.com/learn/engineering/strata-open-source-library-for-efficient-mongodb-backups/

Regarding the file handles problem, I just committed https://github.com/facebook/rocksdb/commit/ac9bcb55ce3b67317c5153748ea7a3fac55108fe which should help. However, better fix would be to increase your file size: https://github.com/facebook/rocksdb/blob/rocksdb-3.13.1/include/rocksdb/options.h#L376. Our default is 2MB which is too low (we're very careful about changing defaults). We usually run with 32/64MB. If you increase that to 256MB, a 1TB database will use only 4000 file handles.

There's some more tuning you could do and I'm happy to help if you have any questions.

**Comment by sudabon** [comment] 2015-09-14 03:22
Thanks @pauldix for your clarification.
I'm willing to cooperate with you.
I would like you to announce the release of nightly build on #4086.
I stay tunned.

**Comment by ericwuseattle** [comment] 2016-02-05 00:59
@sudabon totally agree with you, I have the same issue on 0.9.6.1 version, that influxdb is holding about 3G memory output by debug/pprof/heap, and ps aux showing around 11G. It should be a memory leak issue, I do not believe it is a golang gc not returning the memory to system.

**Comment by pauldix** [comment] 2016-02-05 20:30
@ericwuseattle please test against 0.10.0, released yesterday. This is resolved in that release.

**Comment by ericwuseattle** [comment] 2016-02-17 17:18
@pauldix thanks, seems like the issue is fixed. Good Job!

**Comment by Sahasrara** [comment] 2016-07-06 22:52
I just restored a backup from a 0.10 to a 0.13 and when i start the database, it quickly consumes all 12GB on the box then dies without an error.  Could this be related?

**Comment by timo-klarshift** [comment] 2016-07-22 11:23
Just if helpful for someone. I also had the problem that after starting influxdb was consuming all of the 8GB being left on that machine within a few minutes. After nothing of the suggested tips helped (I am also using beta3 atm) I found out that I had more than 500K series in one my databases. This is due wrong configuration of one of the sending node which send far to much tags. After stopping sending data and dropping the database I have constant memory consumption (~600MB).
