### ISSUE TITLE
Malformed delete query will cause PANIC

### ISSUE THREAD

**Issue by dever860** [influxdb/influxdb#1769] opened 2015-02-27 00:41 UTC
Malformed delete query will cause PANIC.

URL:
http://[[HOSTNAME]]:8086/query?u=root&p=root&q=DELETE%20FROM%20blah%20WHERE%20time%20%3C%20now%28%29%20-%207d&db=ANALYTICS

Error:
`[srvr] 2015/02/26 19:34:56 http: panic serving [[X.X.X.X]]:54036: unsupported statement type: *influxql.DeleteStatement
goroutine 4306 [running]:
net/http.func·011()
	/root/.gvm/gos/go1.4/src/net/http/server.go:1130 +0xbb
github.com/influxdb/influxdb.(*Server).ExecuteQuery(0xc2080348f0, 0xc2083c6720, 0xc208372fa9, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/server.go:1759 +0x753
github.com/influxdb/influxdb/httpd.(*Handler).serveQuery(0xc2084b4180, 0x7f601f1f01e8, 0xc2083c6680, 0xc208360820, 0x0)
	/root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/httpd/handler.go:162 +0x36e
github.com/influxdb/influxdb/httpd.*Handler.(github.com/influxdb/influxdb/httpd.serveQuery)·fm(0x7f601f1f01e8, 0xc2083c6680, 0xc208360820, 0x0)
	/root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/httpd/handler.go:61 +0x4f
github.com/influxdb/influxdb/httpd.func·003(0x7f601f1f01e8, 0xc2083c6680, 0xc208360820)
	/root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/httpd/handler.go:483 +0x77
net/http.HandlerFunc.ServeHTTP(0xc208207ac0, 0x7f601f1f01e8, 0xc2083c6680, 0xc208360820)
	/root/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·004(0x7f601f1eff98, 0xc2083c6520, 0xc208360820)
	/root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/httpd/handler.go:530 +0x288
net/http.HandlerFunc.ServeHTTP(0xc2084ae270, 0x7f601f1eff98, 0xc2083c6520, 0xc208360820)
	/root/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·005(0x7f601f1eff98, 0xc2083c6520, 0xc208360820)
	/root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/httpd/handler.go:539 +0xb0
net/http.HandlerFunc.ServeHTTP(0xc208207ae0, 0x7f601f1eff98, 0xc2083c6520, 0xc208360820)
	/root/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·006(0x7f601f1eff98, 0xc2083c6520, 0xc208360820)
	/root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/httpd/handler.go:572 +0x31a
net/http.HandlerFunc.ServeHTTP(0xc2084ae2b0, 0x7f601f1eff98, 0xc2083c6520, 0xc208360820)
	/root/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·007(0x7f601f1eff98, 0xc2083c6520, 0xc208360820)
	/root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/httpd/handler.go:582 +0x164
net/http.HandlerFunc.ServeHTTP(0xc2084ae2d0, 0x7f601f1eff98, 0xc2083c6520, 0xc208360820)
	/root/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·008(0x7f601f1eff98, 0xc2083c6500, 0xc208360820)
	/root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/httpd/handler.go:590 +0x123
net/http.HandlerFunc.ServeHTTP(0xc208207b00, 0x7f601f1eff98, 0xc2083c6500, 0xc208360820)
	/root/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/influxdb/influxdb/httpd.func·009(0x7f601f1daa98, 0xc208030be0, 0xc208360820)
	/root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/httpd/handler.go:600 +0x12c
net/http.HandlerFunc.ServeHTTP(0xc208207ba0, 0x7f601f1daa98, 0xc208030be0, 0xc208360820)
	/root/.gvm/gos/go1.4/src/net/http/server.go:1265 +0x41
github.com/bmizerany/pat.(*PatternServeMux).ServeHTTP(0xc20839ddf0, 0x7f601f1daa98, 0xc208030be0, 0xc208360820)
	/root/.gvm/pkgsets/go1.4/global/src/github.com/bmizerany/pat/mux.go:109 +0x21c
github.com/influxdb/influxdb/httpd.(*Handler).ServeHTTP(0xc2084b4180, 0x7f601f1daa98, 0xc208030be0, 0xc208360820)
	/root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/httpd/handler.go:144 +0x4a
main.(*Handler).ServeHTTP(0xc2080ba240, 0x7f601f1daa98, 0xc208030be0, 0xc208360820)
	/root/.gvm/pkgsets/go1.4/global/src/github.com/influxdb/influxdb/cmd/influxd/handler.go:41 +0x1f5
net/http.serverHandler.ServeHTTP(0xc20800a4e0, 0x7f601f1daa98, 0xc208030be0, 0xc208360820)
	/root/.gvm/gos/go1.4/src/net/http/server.go:1703 +0x19a
net/http.(*conn).serve(0xc208031720)
	/root/.gvm/gos/go1.4/src/net/http/server.go:1204 +0xb57
created by net/http.(*Server).Serve
	/root/.gvm/gos/go1.4/src/net/http/server.go:1751 +0x35e`

**Comment by pauldix** [comment] 2015-02-27 01:03
This is a duplicate of #1427

**Closed by pauldix** 2015-02-27 01:03 UTC
