### ISSUE TITLE
influxd crash when query specifies exact time

### ISSUE THREAD

**Issue by ctrlrsf** [influxdb/influxdb#2031] opened 2015-03-20 18:49 UTC
influxd crashes when querying with an exact time using `=`. Using a `>` or `<` returns results as expected. See below for sample queries.

Line responsible: https://github.com/influxdb/influxdb/blob/master/influxql/engine.go#L132

Other possibly related issues: #1983 and #2002 

```
> select value from cpu_load_short where time = '2009-10-10T23:00:00Z'
ERR: Get http://localhost:8086/query?db=lol&q=select+value+from+cpu_load_short+where+time+%3D+%272009-10-10T23%3A00%3A00Z%27: EOF

> select value from cpu_load_short where time > '2009-10-10T23:00:00Z'
name: cpu_load_short
--------------------
time			value
2009-11-10T23:00:00Z	0.64
```

Series content:
```
> select * from cpu_load_short
name: cpu_load_short
--------------------
time			value
2009-09-10T23:00:00Z	0.44
2009-10-10T23:00:00Z	0.54
2009-11-10T23:00:00Z	0.64
```

Stack trace:
```
panic: runtime error: integer divide by zero
[signal 0x8 code=0x7 addr=0x267ac0 pc=0x267ac0]

goroutine 884 [running]:
github.com/influxdb/influxdb/influxql.(*MapReduceJob).Execute(0xc208397dc0, 0xc2083a4cc0, 0x379f00)
	/Users/rsf/gocode/src/github.com/influxdb/influxdb/influxql/engine.go:132 +0x6c0
github.com/influxdb/influxdb/influxql.(*Executor).execute(0xc2083b0a00, 0xc2083a4cc0)
	/Users/rsf/gocode/src/github.com/influxdb/influxdb/influxql/engine.go:658 +0xba
created by github.com/influxdb/influxdb/influxql.(*Executor).Execute
	/Users/rsf/gocode/src/github.com/influxdb/influxdb/influxql/engine.go:637 +0x12b

goroutine 1 [chan receive (nil chan)]:
main.execRun(0xc20800a010, 0x0, 0x0)
	/Users/rsf/gocode/src/github.com/influxdb/influxdb/cmd/influxd/main.go:126 +0x880
main.main()
	/Users/rsf/gocode/src/github.com/influxdb/influxdb/cmd/influxd/main.go:68 +0x650
```

**Comment by pauldix** [comment] 2015-03-20 18:51
Closing this out since it's now a duplicate of #2002 and I just commented there :)

**Closed by pauldix** 2015-03-20 18:51 UTC
