### ISSUE TITLE
Clustering - add duplicate node - crash

### ISSUE THREAD

**Issue by easyrasta** [influxdb/influxdb#2438] opened 2015-04-27 13:48 UTC
with new default config to localhost, I started a second server without setting hostname. So It joins to first cluster with giving locahost. Resulting a crash of first server:
```
[raft] 2015/04/27 13:44:38 apply: add node: duplicate node url
panic: apply: add node: duplicate node url

goroutine 10 [running]:
log.(*Logger).Panicf(0xc20800a6e0, 0x9fc410, 0x13, 0xc208185d58, 0x1, 0x1)
	/root/.gvm/gos/go1.4.2/src/log/log.go:200 +0xd1
github.com/influxdb/influxdb/raft.(*Log).mustApplyAddPeer(0xc208038820, 0xc2080ffa70)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/raft/log.go:1519 +0x2ce
github.com/influxdb/influxdb/raft.(*Log).applyNextUnappliedEntry(0xc208038820, 0xc20805a540, 0x0, 0x0)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/raft/log.go:1437 +0x752
github.com/influxdb/influxdb/raft.(*Log).applier(0xc208038820, 0xc20805a540)
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/raft/log.go:1383 +0x161
created by github.com/influxdb/influxdb/raft.func·002
	/root/.gvm/pkgsets/go1.4.2/global/src/github.com/influxdb/influxdb/raft/log.go:389 +0x764
```

**Comment by cboggs** [comment] 2015-04-27 20:49
Mostly a duplicate of #2279. Good to point out that the 'stock' config leaves the hostnames identically empty and thus causes this behavior. Not sure if that should be considered a bug or not, but worth noting.

**Comment by beckettsean** [comment] 2015-04-30 23:18
Thanks for the extra context, this does appear to be a duplicate of #2279.

**Closed by beckettsean** 2015-04-30 23:18 UTC
