### ISSUE TITLE
Starting influxdb through debian services utility fails

### ISSUE THREAD

**Issue by 256dpi** [influxdb/influxdb#1341] opened 2015-01-20 22:08 UTC
I recently noticed that starting influxdb with `sudo service influxdb start` does not work, without any special log entries made.

The manpage says that the `services` removes unneeded environment variables. Could that be the source of the problem?

http://manpages.ubuntu.com/manpages/precise/man8/service.8.html

If this is not possible, the documentation should maybe include this caveat.

**Comment by steverweber** [comment] 2015-03-19 18:19
confirmed.
I think the issue is a bad init.d script.
Why this thing needs to be so complex... I don't know...
but I found the issue to be when using the `nohup start-stop-daemon` 

vi /etc/init.d/influxdb
```
nohup start-stop-daemon --chuid influxdb:influxdb -d --start --oknodo --pidfile $pidfile --exec $daemon -- -pidfile $pidfile -config $config >> $STDOUT 2>&1 &
```
notice that `-d` has no path...
perhaps use something like...
```
nohup start-stop-daemon --chuid influxdb:influxdb -d /opt/influxdb/shared  --start --oknodo --pidfile $pidfile --exec $daemon -- -pidfile $pidfile -config $config >> $STDOUT 2>&1 &
```

**Comment by otoolep** [comment] 2015-03-19 18:27
Which version of InfluxDB does this concern? It must not be 0.9, since its `init.d` script is fine.  Please be sure to include the version of the software you are running when opening tickets.

https://github.com/influxdb/influxdb/blob/master/scripts/init.sh#L109

**Comment by otoolep** [comment] 2015-03-19 18:29
The 0.8 init script is also OK, so it's not clear to me how your init.d script is missing a path.

https://github.com/influxdb/influxdb/blob/v0.8.8/scripts/init.sh

**Comment by otoolep** [comment] 2015-03-19 18:40
I am closing this ticket, since the line from the output shown above is nowhere to be found in master source. Please re-open if I a mistaken. The 0.9.0 releases also start fine.

**Closed by otoolep** 2015-03-19 18:40 UTC

**Comment by steverweber** [comment] 2015-03-19 21:20
Opps i was using the older release...
http://s3.amazonaws.com/influxdb/influxdb_latest_amd64.deb
```
root@oat-mon-1-dev:/# influxdb -v
InfluxDB v0.8.8 (git: afde71e) (leveldb: 1.15)
```
I'll check the 0.9 rc

**Comment by steverweber** [comment] 2015-03-19 21:25
confirmed 0.9 corrected the issue.
