### ISSUE TITLE
Column names beginning with 'stats.' no longer work

### ISSUE THREAD

**Issue by joshuawarner32** [influxdb/influxdb#3559] opened 2015-08-05 14:33 UTC
Previously, with 0.9.0-RC28 (and maybe before that; I'm not sure), we were using columns names like, "stats.nb_received_packets_lost".  0.9.0-RC28 dealt with these fine, but 0.9.2 no longer works correctly with them.

In particular, it accepts them (with a 204), but then all queries from that series fail, with a bizarre parse error (see below).  The behavior is the same, independent of whether the old JSON format or the new comma/space-separated format is used for insertion.

Here's the issue: I completely understand having "reserved" column names.  It's not great (IMHO), but it's fine.  The problem is that writes are succeeding, but later reads fail.

If names beginning with "stats." are genuinely not allowed, trying to write data with that column name should return an error, rather than corrupting the data.

Reproduction steps:

```
$ # Install influx 0.9.2, then:

$ curl -G http://localhost:8086/query --data-urlencode "q=CREATE DATABASE mydb"
{"results":[{}]}

$ curl -i -XPOST 'http://localhost:8086/write?db=mydb' --data-binary 'cpu_load_short,host=server01,region=us-west stats.nb_received_packets=0.64 1434055562000000000'
HTTP/1.1 204 No Content
Request-Id: 68094e80-3b7e-11e5-87c2-000000000000
X-Influxdb-Version: 0.9.2
Date: Wed, 05 Aug 2015 14:29:41 GMT

$ curl -G 'http://localhost:8086/query' --data-urlencode "db=mydb" --data-urlencode "q=SELECT * FROM cpu_load_short;"
{"results":[{"error":"found STATS, expected identifier, string, number, bool at line 1, char 8"}]}
```

**Comment by joshuawarner32** [comment] 2015-08-05 14:55
Actually, looks like this is probably related to https://github.com/influxdb/influxdb/issues/3547

**Comment by beckettsean** [comment] 2015-08-05 18:09
Agreed, closing as duplicate of #3547, which is under active development right now.

**Closed by beckettsean** 2015-08-05 18:09 UTC
