### ISSUE TITLE
Disabled CQ blocks write/create db

### ISSUE THREAD

**Issue by easyrasta** [influxdb/influxdb#2657] opened 2015-05-26 15:52 UTC
After writing problem in #2655  I tried to disabled continuous_queries:
[srvr] 2015/05/26 15:49:42 Not running continuous queries. [continuous_queries].disabled is set to true.

 Then my db disapear and I could create any db and write to previous db.

**Comment by dgnorton** [comment] 2015-06-10 16:47
@easyrasta can you recreate this issue?

**Comment by beckettsean** [comment] 2015-06-16 22:21
Cannot reproduce with 0.9.0 final. Closing issue until repro steps exist.

**Closed by beckettsean** 2015-06-16 22:21 UTC
Labels: 1 - Ready, category/continuous queries
