### ISSUE TITLE
bug: cannot drop database in influxdb 0.9

### ISSUE THREAD

**Issue by rucka** [influxdb/influxdb#3496] opened 2015-07-29 09:34 UTC
I'm running Influxdb from a docker ubuntu 14.04

If I try to delete the existing db 'mydb' from web admin I receive the success message: 'Successfully removed database: mydb' but the command SHOW DATABASES return a list containng 'mydb'.

When I try to delete the db from the shell this is the result:

```
root@19cc64b376f5:/# /opt/influxdb/influx -username 'root' -password 'root'
Connected to http://localhost:8086 version FIXME
InfluxDB shell 0.9.0
> DROP DATABASE mydb
ERR: remove /data: device or resource busy
Warning: It is possible this error is due to not setting a database.
Please set a database with the command "use <database>".
> use mydb
Using database mydb
> DROP DATABASE mydb
ERR: remove /data: device or resource busy
> USE test-db
Using database test-db
> DROP DATABASE mydb
ERR: remove /data: device or resource busy
> SHOW DATABASES
name: databases
---------------
name
dev-statistics
test-db
mydb
testdb

```

Regards
Gianluca

**Comment by mjdesa** [comment] 2015-07-29 17:29
@rucka can you reproduce this error in 0.9.2?

**Comment by rucka** [comment] 2015-07-29 18:04
Hi Michael,
yes I tried both 0.9 and in 0.9.2.1.

**Comment by beckettsean** [comment] 2015-07-29 22:20
@rucka the error strongly implies that the mount point is unavailable or otherwise locked up.

Could there be a docker conflict preventing access to the `/data` directory? What are the results of `ls -l` for the `/data` directory?

**Comment by kvesterling** [comment] 2015-08-18 13:43
Confirmed... Evidently if the DB has a non alpha-numeric character in it, influx will not drop the DB.  Attempts to escape it with \, or enclose in single quotes fail as well.  This is not a docker install, VM w/ Influx.  *(Nightly build - 8/17)


Observe:

> create database deleteme
> drop database deleteme
> drop database o3b-noc
ERR: error parsing query: found -, expected SELECT, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET at line 1, char 18
Warning: It is possible this error is due to not setting a database.
Please set a database with the command "use <database>".
> drop database o3b\-noc
ERR: error parsing query: found \, expected SELECT, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET at line 1, char 18
Warning: It is possible this error is due to not setting a database.
Please set a database with the command "use <database>".
>

**Comment by mjdesa** [comment] 2015-08-18 16:54
@kvesterling this behavior is expect. To create a database named `o3b-noc` it must be double-quoted (e.g. `create database "o3b-noc"`). See the documentation on [identifiers](https://influxdb.com/docs/v0.9/administration/administration.html#identifiers)

**Comment by beckettsean** [comment] 2015-08-18 22:19
@rucka did you ever figure out if it was a mount point issue or not?

**Comment by beckettsean** [comment] 2015-08-25 20:52
Seems to be a system-level issue, not one with InfluxDB. Closing.

**Closed by beckettsean** 2015-08-25 20:52 UTC
