### ISSUE TITLE
Request for new Aggregate function  "Difference" 

### ISSUE THREAD

**Issue by chaithrar** [influxdb/influxdb#3874] opened 2015-08-27 21:39 UTC
we would like to have a new aggregate function "Difference", which would calculate the difference between given time range 

i.e we are using grafana to show network throughput and bandwidth. We are calculating the difference for each of them and then sending to influxdb. If influxDB supports difference like sum and other aggregate functions it would be really helpful.

Please let us know if its feasible

**Comment by beckettsean** [comment] 2015-08-27 23:18
closing as duplicate of https://github.com/influxdb/influxdb/issues/1825

**Closed by beckettsean** 2015-08-27 23:18 UTC
