### ISSUE TITLE
wrong date returned when using last()

### ISSUE THREAD

**Issue by jacekgrzybowski** [influxdb/influxdb#3396] opened 2015-07-20 12:51 UTC
When using `last()` function the beginning of unix epoch is always returned as timestamp. Its a little troublesome because I cannot use `ORDER BY time DESC limit 1` yet and I simply want to get the latest value with its timestamp.

Query:

    SELECT last(value) FROM /^response_times.service_1.*/ LIMIT 1

Response:

    {"results":[{"series":[{"name":"response_times.service_1.pl.warsaw.dc1","columns":["time","last"],"values":[["1970-01-01T00:00:00Z",0.036371598]]},{"name":"response_times.service_1.us.new-york.dc3","columns":["time","last"],"values":[["1970-01-01T00:00:00Z",0.999999999]]}]}]}

**Comment by beckettsean** [comment] 2015-07-20 20:47
Duplicate of https://github.com/influxdb/influxdb/issues/1577

**Closed by beckettsean** 2015-07-20 20:47 UTC
