### ISSUE TITLE
panic: runtime error: slice bounds out of range (0.9.5 *stable*)

### ISSUE THREAD

**Issue by pfischermx** [influxdb/influxdb#4890] opened 2015-11-24 02:39 UTC
I saw some git issues reporting this but some of them were quiet old, so feel free to close this and use the other git issues if you are working on any of them.

I upgraded to latest influxdb (0.9.5), we were running the nightly build for maybe 3-4 weeks but we were seeing the "panic: runtime error: slice bounds out of range" every now and then, not big deal. Now that we are on 0.9.5 (the "stable" version, not nightly) we seem to be getting this more often.

panic: runtime error: slice bounds out of range

Is there any work around? I'm guessing it is a bad HTTP request (query)?

**Comment by cxreg** [comment] 2015-11-24 04:08
Ths looks like a duplicate of #4869 which was reported 2 days ago, and which mentions there is a tsm1 refactor happening.  A strange situation for a new system recently declared stable, but there you go.

**Comment by otoolep** [comment] 2015-11-24 04:11
Just so there is no misunderstanding 0.9.5 is considered stable but not
with the tsm1 engine. That engine is not the default and is still
experimental. You must explicitly enable it.

**Comment by cxreg** [comment] 2015-11-24 04:15
Thank you for that clarification, makes more sense

**Comment by beckettsean** [comment] 2015-11-25 23:00
closing as duplicate of #4869

**Closed by beckettsean** 2015-11-25 23:00 UTC
