### ISSUE TITLE
Ordering by time DESC doesn't work properly

### ISSUE THREAD

**Issue by pga23** [influxdb/influxdb#4428] opened 2015-10-13 16:22 UTC
Below you can find example with return data set ordered in the wrong way:

> SELECT * FROM my_metrics ORDER BY time DESC

time | count | package | seq | status
-----|-------|---------|-----|-------
2015-10-12T21:04:25Z | 85 | 140c8db92b786400 | 183 | 33
2015-10-12T21:00:25Z | 85 | 140c8db92b786400 | 182 | 33
2015-10-12T20:56:25Z | 85 | 140c8db92b786400 | 181 | 33
2015-10-12T20:52:20Z | 85 | 140c8db92b786400 | 180 | 33
2015-10-12T20:48:20Z | 85 | 140c8db92b786400 | 179 | 33
2015-10-12T20:44:15Z | 85 | 140c8db92b786400 | 178 | 33
2015-10-12T20:40:20Z | 85 | 140c8db92b786400 | 177 | 33
2015-10-12T20:36:20Z | 85 | 140c8db92b786400 | 176 | 33
2015-10-12T20:32:14Z | 85 | 140c8db92b786400 | 175 | 33
2015-10-12T20:28:04Z | 85 | 140c8db92b786400 | 174 | 33
2015-10-12T20:23:54Z | 85 | 140c8db92b786400 | 173 | 33
2015-10-12T20:19:59Z | 85 | 140c8db92b786400 | 172 | 33
2015-10-12T20:15:48Z | 85 | 140c8db92b786400 | 171 | 33
2015-10-12T20:11:54Z | 85 | 140c8db92b786400 | 170 | 33
2015-10-13T15:36:36Z | 85 | 140cc9befb3e7400 | 202 | 33
2015-10-13T15:32:31Z | 85 | 140cc9befb3e7400 | 201 | 33
2015-10-13T15:28:21Z | 85 | 140cc9befb3e7400 | 200 | 33
2015-10-13T15:20:26Z | 85 | 140cc9befb3e7400 | 198 | 33
2015-10-13T15:12:21Z | 85 | 140cc9befb3e7400 | 196 | 33
2015-10-13T15:08:21Z | 85 | 140cc9befb3e7400 | 195 | 33
2015-10-13T15:04:15Z | 85 | 140cc9331b952200 | 194 | 33
2015-10-13T15:04:15Z | 85 | 140cc9befb3e7400 | 194 | 33
2015-10-13T15:00:20Z | 85 | 140cc9befb3e7400 | 193 | 33
2015-10-13T15:00:20Z | 85 | 140cc9331b952200 | 193 | 33
2015-10-13T14:56:20Z | 85 | 140cc9331b952200 | 192 | 33
2015-10-13T14:56:20Z | 85 | 140cc9befb3e7400 | 192 | 33
2015-10-13T14:48:05Z | 85 | 140cc9331b952200 | 190 | 33
2015-10-13T14:43:55Z | 85 | 140cc9331b952200 | 189 | 33
2015-10-13T14:43:55Z | 85 | 140cc9befb3e7400 | 189 | 33

In above example **package** are tag, other fields are integer.

With the same data ordering by time ASC work properly.

I use the 0.9.4.2 version of InfluxDB.

**Comment by beckettsean** [comment] 2015-10-13 19:20
Closing as duplicate of https://github.com/influxdb/influxdb/issues/4235

**Closed by beckettsean** 2015-10-13 19:20 UTC
