### ISSUE TITLE
ORDER by time DESC issues

### ISSUE THREAD

**Issue by oshoemaker** [influxdb/influxdb#4772] opened 2015-11-12 22:16 UTC
I checked the previous open issues and it looked like this has been resolved.  I just tested and I am still having issues with this.  Ordering seems inconsistent.  Am I missing something?  Is this broken again in 9.5?

root@db1:/app# influxd version
InfluxDB v0.9.5-nightly-2fe5e6b (git: master 2fe5e6b4f7192445deec0898ec702d1f8cbba5da, built '2015-10-27T04:00:42+0000')

```
> select * from alarm 
name: alarm
-----------
time			alarm	baseId	bsid			locationId
2015-11-12T20:10:25Z	on	209	d0:63:be:ef:de:ad	2
2015-11-12T20:14:23Z	off	209	d0:63:be:ef:de:ad	2
2015-11-12T20:23:02Z	on	209	d0:63:be:ef:de:ad	2
2015-11-12T20:24:43Z	off	209	d0:63:be:ef:de:ad	2
2015-11-12T20:42:09Z	on	209	d0:63:be:ef:de:ad	2
2015-11-12T20:42:38Z	off	209	d0:63:be:ef:de:ad	2
2015-11-12T20:51:15Z	on	209	d0:63:be:ef:de:ad	2
2015-11-12T20:51:58Z	off	209	d0:63:be:ef:de:ad	2

> select * from alarm ORDER by time DESC
name: alarm
-----------
time			alarm	baseId	bsid			locationId
2015-11-12T20:51:15Z	on	209	d0:63:be:ef:de:ad	2
2015-11-12T20:42:09Z	on	209	d0:63:be:ef:de:ad	2
2015-11-12T20:23:02Z	on	209	d0:63:be:ef:de:ad	2
2015-11-12T20:51:58Z	off	209	d0:63:be:ef:de:ad	2
2015-11-12T20:42:38Z	off	209	d0:63:be:ef:de:ad	2
2015-11-12T20:24:43Z	off	209	d0:63:be:ef:de:ad	2
2015-11-12T20:14:23Z	off	209	d0:63:be:ef:de:ad	2
2015-11-12T20:10:25Z	on	209	d0:63:be:ef:de:ad	2
```

**Comment by beckettsean** [comment] 2015-11-12 22:30
closing as duplicate of https://github.com/influxdb/influxdb/issues/4235 (which did have an overly specific title)

**Closed by beckettsean** 2015-11-12 22:30 UTC
