### ISSUE TITLE
Writes that go into non-leader fail

### ISSUE THREAD

**Issue by pauldix** [influxdb/influxdb#1870] opened 2015-03-06 18:05 UTC
If running in a cluster and writes go into a server that is not the Raft leader, you get an error message

```json
{"error":"not leader"}
```

At least I think this is what's happening. Need to verify this and if it's the case, make sure the writes get forwarded to the raft leader.

**Comment by otoolep** [comment] 2015-03-06 21:36
I cannot reproduce this. I forced an election to occur by killing the leader before a write occurred. When a data node then directs a write to a non-leading broker node, the data node is redirected to the actual leader. The data node follows the redirection and then writes the data successfully.

**Comment by otoolep** [comment] 2015-03-06 21:39
@benbjohnson -- is there anywhere in the code missing leader-redirection?

**Comment by benbjohnson** [comment] 2015-03-06 21:43
I don't know off the top of my head. @pauldix do you know if this consistently happens or if it just happens sometimes when there is no current leader?

**Comment by otoolep** [comment] 2015-03-06 21:53
Drive-by enhancement related to this issue. Not a fix.

https://github.com/influxdb/influxdb/pull/1877

**Comment by otoolep** [comment] 2015-03-06 22:04
@benbjohnson -- I presume writes should be blocked, and retried, if they take place during an election?

**Comment by otoolep** [comment] 2015-03-06 22:05
Same thing applies if a data node finds itself on the wrong side of a network partition too, I guess.

**Comment by benbjohnson** [comment] 2015-03-06 22:18
Yeah, we should do retries if it's unavailable -- at least for a little bit.

**Comment by otoolep** [comment] 2015-03-06 23:22
I guess it's plausible that a write happened during a leader election on the cluster (or a network partition) -- I could check into that path.

**Comment by otoolep** [comment] 2015-03-09 18:40
@benbjohnson : https://github.com/influxdb/influxdb/blob/master/raft/log.go#L1025

Could this actually happen? Or if it did, would it be sign there was a bug in the code? Or could this error still be raised, in certain circumstances, without it necessarily being a bug?

**Comment by otoolep** [comment] 2015-03-09 22:29
Right now I can't repro this, and have tested the write path. Writes to a healthy cluster are re-directed correctly. I do have 1 question for @benbjohnson, as noted above.

**Comment by benbjohnson** [comment] 2015-03-18 00:52
I think this should be fixed with the `stateless-broker` changes.

**Closed** 2015-03-18 00:56 UTC
Labels: 2 - Working
