### ISSUE TITLE
InfluxDb rc30 returns only columns and no values

### ISSUE THREAD

**Issue by abeninskibede** [influxdb/influxdb#2627] opened 2015-05-21 15:22 UTC
Hi guys,

I get a response without any values when I do `select * from localBankingEvent`

```
{
    "results": [
        {
            "series": [
                {
                    "name": "localBankingEvent",
                    "columns": [
                        "time",
                        "Amount",
                        "BaseAmount",
                        "BaseBingo_BonusBalance",
                        "BaseBingo_BronzeBalance",
                        "BaseBingo_GoldBalance",
                        "BaseBingo_PointsBalance",
                        "BaseBingo_RechargePointsBalance",
                        "BaseBingo_SilverBalance",
                        "BaseCashBalance",
                        "BaseCasino_BonusBalance",
                        "Bingo_BonusBalance",
                        "Bingo_BronzeBalance",
                        "Bingo_GoldBalance",
                        "Bingo_PointsBalance",
                        "Bingo_RechargePointsBalance",
                        "Bingo_SilverBalance",
                        "BonusPromoCode",
                        "CashBalance",
                        "Casino_BonusBalance",
                        "CompletedAtUtc",
                        "CorrelationToken",
                        "Count",
                        "Currency",
                        "CurrencyCode",
                        "Description",
                        "Environment",
                        "InitiatedByAdmin",
                        "IsCompleted",
                        "LicenseHolder",
                        "Partner",
                        "RemoteRef",
                        "StartedAtUtc",
                        "TransactionId",
                        "TransactionType",
                        "UserName",
                        "Wallet",
                        "WalletVersion",
                        "site",
                        "timestamp",
                        "userId"
                    ]
                }
            ]
        }
    ]
}
```

I send the following JSON:

```
{  
   "database":"testing",
   "points":[  
      {  
         "tags":{  
            "bedeUserId":"1",
            "siteCode":"test"
         },
         "fields":{  
            "Amount":100.00,
            "BaseAmount":100.00,
            "BonusPromoCode":"",
            "CompletedAtUtc":"2015-05-21T15:05:41Z",
            "Count":314,
            "CurrencyCode":"GBP",
            "Description":"",
            "InitiatedByAdmin":"False",
            "IsCompleted":"True",
            "RemoteRef":"",
            "StartedAtUtc":"2015-05-21T15:05:41Z",
            "TransactionType":"Deposit",
            "Wallet":"Cash",
            "UserName":"testplayer1",
            "TransactionId":"2148294039",
            "userId":"271661",
            "CorrelationToken":"GEN18c4adba-11f5-4404-846e-29235616a598",
            "timestamp":1432220741,
            "site":"test",
            "LicenseHolder":"IP&S",
            "Partner":"IP&S",
            "Currency":"GBP",
            "Environment":"local",
            "WalletVersion":2,
            "CashBalance":893230.51,
            "BaseCashBalance":893230.51,
            "Casino_BonusBalance":2761.12,
            "BaseCasino_BonusBalance":2761.12,
            "Bingo_BonusBalance":100.00,
            "BaseBingo_BonusBalance":100.00,
            "Bingo_PointsBalance":333.00,
            "BaseBingo_PointsBalance":333.00,
            "Bingo_GoldBalance":45.00,
            "BaseBingo_GoldBalance":45.00,
            "Bingo_SilverBalance":15.00,
            "BaseBingo_SilverBalance":15.00,
            "Bingo_BronzeBalance":0.00,
            "BaseBingo_BronzeBalance":0.00,
            "Bingo_RechargePointsBalance":0.00,
            "BaseBingo_RechargePointsBalance":0.00
         },
         "time":1432220741000,
         "name":"localBankingEvent"
      }]
}

```

When I do the same with another series it returns values.

What am I doing wrong?

**Comment by abeninskibede** [comment] 2015-05-21 15:31
Could this be because I have another series with the same tags?  
 "tags":{  
            "bedeUserId":"271661",
            "siteCode":"test"
         },

**Comment by abeninski** [comment] 2015-05-21 15:45
I can see tags when using show series.

**Comment by toddboom** [comment] 2015-05-21 19:43
@abeninskibede this is a dupe of #1997 - we should have this fixed in the next week or so.

**Closed by toddboom** 2015-05-21 19:43 UTC

**Comment by abeninski** [comment] 2015-05-22 06:13
@toddboom are you sure it is the same issue because apart from not getting tags in not getting column values - just column names?

**Comment by abeninskibede** [comment] 2015-05-22 07:09
Aggretages like sum(Amount) returns null:

```
{
    "results": [
        {
            "series": [
                {
                    "name": "localBankingEvent",
                    "columns": [
                        "time",
                        "count"
                    ],
                    "values": [
                        [
                            "1970-01-01T00:00:00Z",
                            null
                        ]
                    ]
                }
            ]
        }
    ]
}
```

**Comment by abeninskibede** [comment] 2015-05-22 08:09
Ah found the problem: was supplying time as milliseconds without specifying a precision.
