### ISSUE TITLE
[Request] A command to show the inferred/static field types

### ISSUE THREAD

**Issue by bigKS** [influxdb/influxdb#5175] opened 2015-12-20 03:50 UTC
https://github.com/influxdb/influxdb/issues/5155  makes it clear that the field types are very strict (i.e., you cannot write a floating point number after writing an integer ... ).

I think we need a command to show the static inferred types on the fields within a series.  Can we add this information to an existing query command or create a new one?

**Comment by beckettsean** [comment] 2015-12-21 18:14
Duplicate of https://github.com/influxdb/influxdb/issues/3451

**Closed by beckettsean** 2015-12-21 18:14 UTC
