### ISSUE TITLE
[0.9.2] Reserved keywords in tags are non-queryable

### ISSUE THREAD

**Issue by jportoles** [influxdb/influxdb#3915] opened 2015-09-01 03:08 UTC
It looks like as of 0.9.2 double quoting doesn't anymore work to use reserved words in queries:

     > SELECT sum(value) FROM stat WHERE "banana"=1
    ERR: unknown field or tag name in where clause: banana

     > SELECT sum(value) FROM stat WHERE "group-cluster"=1
    ERR: found GROUP, expected identifier, string, number, bool at line 1, char 68

Both should return "unknown field or tag" according to the issue [here](https://github.com/influxdb/influxdb/issues/3162#issuecomment-115863425).

**Comment by beckettsean** [comment] 2015-09-01 19:15
Duplicate of https://github.com/influxdb/influxdb/issues/3547, fixed in 0.9.3

**Closed by beckettsean** 2015-09-01 19:15 UTC
Labels: category/queries
