### ISSUE TITLE
[feature request] Reintroduce group by month, year, or any datetime format

### ISSUE THREAD

**Issue by clongbottom** [influxdb/influxdb#4908] opened 2015-11-25 18:28 UTC
This functionality was removed in 0.9, but existed in 0.8. 

Grouping by month and year is absolutely essential for many applications. Not being able to do this makes it less powerful than pretty much any other non-time-series database for storing time series.

Why isn't this a priority? Surely things like grouping by quarter or any strange date bin are absolutely key for a time series database?

This omission suddenly means I can't even consider using InfluxDB for our system. Shame, as I'd already got started assuming that this functionality would be in there. :-(

**Comment by pauldix** [comment] 2015-11-25 19:01
The functionality in 0.8 was limited to UTC boundaries and didn't give you the flexibility to group by any format.

This is something we'll be adding in (although more feature complete), but it won't be until the end of March or end of May release. Until then we're focused on the new storage engine and clustering, which is important for every use case (many of which don't require these group by intervals)

**Comment by clongbottom** [comment] 2015-12-06 12:54
Paul, that seems fair enough, I'm pleased you'll be adding it back in. Is there somewhere I can track the progress of this specific issue?

**Comment by beckettsean** [comment] 2015-12-06 20:47
duplicate of https://github.com/influxdb/influxdb/issues/3991

**Closed by beckettsean** 2015-12-06 20:47 UTC
