### ISSUE TITLE
Unable to Delete Continuous Query rc27 & rc29

### ISSUE THREAD

**Issue by tbaudais-va** [influxdb/influxdb#2511] opened 2015-05-07 20:18 UTC
Steps to reproduce:

1. Create a continuous query. For example:
```
CREATE CONTINUOUS QUERY test ON "core-test" BEGIN SELECT count(value) INTO "core-test"."default"."something.1h" FROM "core-test"."default".api WHERE status >= 200.000 AND status <= 299.000 AND url = '/somethingelse/' GROUP BY time(1h) END
```
2. Try to delete it by 
```
DROP CONTINUOUS QUERY test
```
3. You get a result:
```
Execute QueryERROR: {"error":"error parsing query: found EOF, expected ON at line 1, char 28"}
```

Notes:
- Auth is turned on

**Comment by neonstalwart** [comment] 2015-05-07 20:45
@tbaudais-va did you try adding the `ON` like the error says...

```
DROP CONTINUOUS QUERY test ON "core-test"
```

**Comment by tbaudais-va** [comment] 2015-05-07 20:58
Yup we did try that on rc29 and it doesn't work. In trying it again here, it does seem to work on rc27 though.

On a side note, here's the docs that should be updated when the time comes (I know you're heavy in development and there's no expectation right now that these are correct):
http://influxdb.com/docs/v0.9/concepts/continuous_queries.html
https://github.com/influxdb/influxdb/blob/master/QUERIES.md

Thanks!
Tod.

**Comment by gunnaraasen** [comment] 2015-05-07 21:42
Yup, we're aware the docs are out of date. I'm going to start revising the continuous query documentation next week. We're planning to have all of the docs in good shape by the time 0.9.0 is released.

I can't comment on the regression, but I'll look into it next week if this issue is still open.

**Comment by tbaudais-va** [comment] 2015-05-07 22:04
Cool thanks. We're looking forward to the release version!

**Comment by toddboom** [comment] 2015-05-11 22:53
@tbaudais-va I just tried this against master (pre-RC30) and couldn't reproduce this error. I did have to specify the `ON "core-test"` part of the query (which is required), but then it worked as expected. Since I don't think there's anything actionable, I'm closing this out for now.

**Closed by toddboom** 2015-05-11 22:53 UTC
Labels: category/continuous queries
