### ISSUE TITLE
CLI allows "use <db>" when db does not yet exist

### ISSUE THREAD

**Issue by beckettsean** [influxdb/influxdb#2758] opened 2015-06-03 22:50 UTC
Maybe not the worst behavior, actually, but I wanted to make sure it's intentional.

```
> show databases
name: databases
---------------
name
mon
mydb
telegraf
tivan

> use foo
Using database foo
> show measurements
ERR: database not found: foo (/private/tmp/influxdb20150528-82093-7zu91/influxdb-0.9.0-rc31/src/github.com/influxdb/influxdb/server.go:2710)
```

**Comment by corylanou** [comment] 2015-06-04 02:27
It's intentional in the sense that it's expected behavior.  Should it be smarter than this?  It certainly could be.  Different databases have different behavior.  I think it would be a nice enhancement to warn the user that the database doesn't exists, but still leave it in that context.  We don't know their intention.

For instance, this is perfectly valid:

```sql
use foo
create database foo
select * from cpu
```

The only error they will get there is if the measurement `cpu` doesn't exist, however, if they were logging data in the background, once they created the database, the writes will start succeeding and their query would have worked.

Certainly this is an edge case, but demonstrating that we don't actually know the intention, and therefore don't really know if this is in fact an error in user usage.

**Comment by nemesisdesign** [comment] 2015-07-16 08:00
Instead of this:
```
> show databases;
name: databases
---------------
name
nodeshot

> use nodeshot;
Using database nodeshot;

> SELECT * FROM i_do_not_exist
ERR: database not found: nodeshot;
```

I would expect:

```
> SELECT * FROM i_do_not_exist
ERR: i_do_not_exist measurement not found;
```

Instead of this:

```
> use IDONOTEXIST
Using database IDONOTEXIST
````

I would expect:

```
> use IDONOTEXIST
ERR: database not found: IDONOTEXIST;
````

I personally find the current influxdb behaviour pretty awkward. Initially it baffled me, I thought I found  another bug.

postgres:
```
postgres=# \connect IDONOTEXIST
FATAL:  database "IDONOTEXIST" does not exist
```

mysql:
```
mysql> use IDONOTEXIST
ERROR 1049 (42000): Unknown database 'IDONOTEXIST'
```

One of the reasons I chose influxdb is because the SQL like query language is familiar and it allowed me to start working with it straightaway in no time.

So my advice is to be consistent with these conventions, you are already implementing innnovative features and innovative ways of doing things in other parts which matter more.

**Comment by pires** [comment] 2015-12-22 14:40
@otoolep this is fixed by #5183.

**Comment by otoolep** [comment] 2015-12-22 15:08
Thanks @pires

**Closed by otoolep** 2015-12-22 15:08 UTC
Labels: category/queries, RFC

**Comment by nemesisdesign** [comment] 2015-12-27 18:52
:+1:
