### ISSUE TITLE
All InfluxDB query fails for a measurement when tag keys are all digits stored as string

### ISSUE THREAD

**Issue by mehulbt** [influxdb/influxdb#3822] opened 2015-08-24 23:41 UTC
Tag key-value are stored as string, as I read from the document - 
The key is the measurement name and any optional tags separated by commas. Measurement names, tag keys, and tag values must escape any spaces or commas using a backslash (\). For example: \ and \,. All tag values are stored as strings and should not be surrounded in quotes.

On another page, there is additional info - 
Measurements, tags, and field names containing any character other than (A-Z,a-z,0-9,_) or starting with a digit must be double-quoted.

I want to store tag key as a string, but our key is a set of digits. Is that supported?
I was able to store the key (with all digits) in the DB, but query printed an error.

name: XXXX
tags: 200=true 340=true

select * from XXX where 200 = 'true'
ERR: only time and tag dimensions allowed

**Comment by beckettsean** [comment] 2015-08-24 23:44
On Mon, Aug 24, 2015 at 4:41 PM, mehulbt <notifications@github.com> wrote:

> Tag key-value are stored as string, as I read from the document -
> The key is the measurement name and any optional tags separated by commas.
> Measurement names, tag keys, and tag values must escape any spaces or
> commas using a backslash (). For example: \ and \,. All tag values are
> stored as strings and should not be surrounded in quotes.
>

The above all refers to the WRITE syntax


> On another page, there is additional info -
> Measurements, tags, and field names containing any character other than
> (A-Z,a-z,0-9,_) or starting with a digit must be double-quoted.
>

That refers to the QUERY syntax

> I want to store tag key as a string, but our key is a set of digits. Is
> that supported?
>
All tags are strings. There is no way to store a tag key or value as
anything other than a string.


> I was able to store the key (with all digits) in the DB, but query printed
> an error.
>
> name: XXXX
> tags: 200=true 340=true
>
> select * from XXX where 200 = 'true'
> ERR: only time and tag dimensions allowed
>
QUERY syntax requires that identifiers starting with a digit must be
double-quoted. This is the right syntax:

select * from XXX where "200" = 'true'


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/influxdb/influxdb/issues/3822>.
>



-- 
Sean Beckett
Director of Support and Professional Services
InfluxDB

**Comment by mehulbt** [comment] 2015-08-24 23:52
Tried to double-quote the tag key, and that didn't work.

> select * from XXX where "200" = 'true'
ERR: only time and tag dimensions allowed

**Comment by beckettsean** [comment] 2015-08-24 23:57
@mehulbt what version are you running?

**Comment by beckettsean** [comment] 2015-08-25 00:01
I'm gonna bet you're on 0.9.2. This looks like a duplicate of https://github.com/influxdb/influxdb/issues/3683, which is fixed in the latest 0.9.3-rc2.

Verified this case is fixed in 0.9.3-rc2:

```
Connected to http://localhost:8086 version 0.9.3-rc2
InfluxDB shell 0.9.3-rc2
> use mydb
Using database mydb
> insert numcheck,200=true value=42
> insert numcheck,200=true value=44
> insert numcheck,200=true value=46
> insert numcheck,200=false value=99
> insert numcheck,200=false value=97
> insert numcheck,200=false value=95
> select * from numcheck
name: numcheck
--------------
time				200	value
2015-08-25T00:00:26.030822096Z	true	42
2015-08-25T00:00:27.892570025Z	true	44
2015-08-25T00:00:29.388967774Z	true	46
2015-08-25T00:00:35.34124812Z	false	99
2015-08-25T00:00:36.805425913Z	false	97
2015-08-25T00:00:37.989688351Z	false	95

> select * from numcheck where "200" = 'true'
name: numcheck
--------------
time				200	value
2015-08-25T00:00:26.030822096Z	true	42
2015-08-25T00:00:27.892570025Z	true	44
2015-08-25T00:00:29.388967774Z	true	46
```

**Closed by beckettsean** 2015-08-25 00:01 UTC

**Comment by mehulbt** [comment] 2015-08-25 01:11
I was actually on 0.9.1. Will try out 0.9.3rc2, but I assume stable 0.9.3 will be available in a week?

Thanks for looking into this issue and verifying that it is fixed!

**Comment by beckettsean** [comment] 2015-08-25 05:42
0.9.3 should be out this week.
